### ISSUE TITLE
Can't update from 0.2.5 to 0.2.7

### ISSUE THREAD

**Issue by Simonell** [roleoroleo/yi-hack-MStar#100]
I've flashed y203c, and now I'm trying to update firmware to 0.2.7, and camera skipping firmware update process. I'm using same card with same file names. I've tried other file names like rootfs instead of sys, and another variations, nothing works.

**Comment by roleoroleo** [comment]
Reformat the sd and retry.
Don't change the name of the files.

**Comment by Simonell** [comment]
I tried to format it undex Linux with "mkfs.vfat -F32" and under Windows, even with another micro sd card, nothing works.

**Comment by roleoroleo** [comment]
Try 0.2.6.

**Comment by roleoroleo** [comment]
Closing without response from issue filer for >14 days.
