### ISSUE TITLE
Turning off motion detection is impossible

### ISSUE THREAD

**Issue by Ne00n** [roleoroleo/yi-hack-MStar#101]
Hey,

I recently flashed the newest Firmware on my YYS2016.
Besides the already reported hostname canno't be changed bug.

I found 2 more.
When I uncheck the checkbox for "Save video when a motion is detected", it still saves Videos on the SD Card file when motion is detected.

Also when I try to block the saving's of files, by set "SD free space (%)" to 99% it still saves Video's to the SD Card.

Any idea on this?

**Comment by roleoroleo** [comment]
This is the correct behavior.
If enabled, video will be saved only when a motion is detected.
If disabled, video will be always saved.

**Comment by Ne00n** [comment]
Could you add an option to disable it completely?
Since I just need a RSTP stream and nothing else.

Killing the process seems to disable it but I would need to do that manually at each reboot.

**Comment by roleoroleo** [comment]
Disable "Recording without cloud".

**Comment by Ne00n** [comment]
Oh yea I see, thanks
