### ISSUE TITLE
Audio with ONVIF

### ISSUE THREAD

**Issue by scaule** [roleoroleo/yi-hack-MStar#102]
Hi,

Thks for this hack ! 
Audio can be used with onvif ?

**Comment by roleoroleo** [comment]
Audio is not available even in rtsp unfortunately.

**Comment by sonnar1800** [comment]
in other versions of yi-hack has audio aac.
Couldn't you put on this one?

**Comment by scaule** [comment]
@sonnar1800 No, i tried this : https://github.com/TheCrypt0/yi-hack-v4 but it doesn't work for me, same problem as this issue : https://github.com/TheCrypt0/yi-hack-v4/issues/192

@roleoroleo Do you think add audio to rtsp is hard ? i have to look at live555 but i'm busy atm.

**Comment by roleoroleo** [comment]
I think is hard.
I don't know ho to extract it from the kernel memory.

**Comment by roleoroleo** [comment]
Solved in 0.3.2.
