### ISSUE TITLE
Updated to 0.2.8 but in the terminal appears 0.2.3 Version

### ISSUE THREAD

**Issue by sonnar1800** [roleoroleo/yi-hack-MStar#103]
I have updated the camera to version 0.2.8 but in terminal it appears yi-hack for MStar platform - v. 0.2.3

I need to do a factory reset and then reinstall the 0.2.8 firmware version?

**Comment by sonnar1800** [comment]
after having installed the version I have been downloaded alone to the source version 0.2.3

**Comment by sonnar1800** [comment]
Nor does the Motion Event work for me in version 0.2.3 or 0.2.7, not in 0.2.8, why can it be?

**Comment by roleoroleo** [comment]
Which version do you see in the status page of the web interface?

**Comment by sonnar1800** [comment]
after updating, version 0.2.8 but then I don't know why I go back to 0.2.3

Now I have updated again and it already appears well on the web and in the terminal.

but the Motion event option still doesn't work

**Comment by roleoroleo** [comment]
What do you mean with "doesn't work"?

**Comment by roleoroleo** [comment]
Closing without response from issue filer for >14 days.
