### ISSUE TITLE
Request. Hi3518e Chipset support after TheCrypt0's

### ISSUE THREAD

**Issue by majkers** [roleoroleo/yi-hack-MStar#104]
Hi. Is it possible for You to take TheCrypt0's job and develop all features You have in Your work in His? It seems that TheCrypt0 is doing very little in his repository...

**Comment by roleoroleo** [comment]
I miss the hardware.
Furthermore, I have no knowledge of the Hi3518e platform. A lot of code is strictly related to the platform: rtsp, snapshot, etc...
I have no plan to develop it.
Sorry.

**Comment by majkers** [comment]
Thanks for the answer.
