### ISSUE TITLE
9FUS and BFUS, don't work using rtsp high res with NVR

### ISSUE THREAD

**Issue by VikIborra** [roleoroleo/yi-hack-MStar#106]
NVR only detect camera with run un low-res.
Sample NVR: https://es.aliexpress.com/item/33002289315.html?spm=a2g0o.productlist.0.0.16701c6erBMV3X&dp=213.98.92.130-IN%2FkQ3iamws&af=d99%3A35011&cn=33002289315&aff_platform=api&sk=_d7cjgaP&aff_trace_key=67bd966300314da68b3c5fc87947b92d-1583836101712-01099-_d7cjgaP&terminal_id=ddf65750697a40fabda9230da9453a36&aff_request_id=67bd966300314da68b3c5fc87947b92d-1583836101712-01099-_d7cjgaP

Maybe the same thing happens with the rest of the cameras.

**Comment by roleoroleo** [comment]
The rtsp stream has a known problem with ffmpeg and I can't solve it.
But I have successfully tested it with shinobi and motion and it works.
I don't know how to help you.
