### ISSUE TITLE
nas recording

### ISSUE THREAD

**Issue by divemasterjm** [roleoroleo/yi-hack-MStar#109]
hi is there any way/option to record on NAS / Directory? would be very useful to have an option where to decide where we want to record.

**Comment by roleoroleo** [comment]
The normal way would be nfs but it is not supported.
You can only export the saved files after creation.

**Comment by divemasterjm** [comment]
Anyway i dont have videos recorded on se card when motion is detected, can you please help me?

**Comment by roleoroleo** [comment]
Did you configure the cam correctly?
Cloud feature is enabled or disabled?

**Comment by divemasterjm** [comment]
Cloud is diaabled, sd is the same I insert with hack, didn’t remove. Do you mean about configure in yi app?
By the way is the hack working removing ads after?

JuanMa

**Comment by roleoroleo** [comment]
Did you enable "Recording without Cloud"?

**Comment by divemasterjm** [comment]
Yes

Saludos
Juan Manuel

**Comment by roleoroleo** [comment]
If you enable Cloud feature, does it work?

**Comment by divemasterjm** [comment]
Nop, also yi app tells me sd card needs to be formatted on both cameras with hack, I didn’t try it cause i dont know if hack works without sd.

Saludos
Juan Manuel

**Comment by roleoroleo** [comment]
The hack will works even without sd card.
Please, keep cloud enabled and try to configure the app until sd recording works.
After that, disable cloud feature.
