### ISSUE TITLE
Custom firmware refusing to flash.

### ISSUE THREAD

**Issue by xfceKris** [roleoroleo/yi-hack-MStar#110]
I feel like I'm doing something wrong, but I'm following the directions to the letter. I've downloaded and extracted the latest .tgz for my 6fus cameras, format the 8gb sd card using the yi app (as per a recommendation from another issue here). Every time I reboot, I get a normal boot up procedure. I've checked tons of open and closed issues to see if anyone else had the same issue, and found nothing of note except for a mention of firmware version being 4.6. Currently, my cameras are running the stock firmware version 2.1.0.0E. I've seen nothing here mentioning this firmware version, and I checked the yi website for updated firmware, and see that this is the latest version. I feel like I'm simply missing something, but I know I've read the documentation thoroughly.

**Comment by roleoroleo** [comment]
I think your cam is not MStar based.
Check if you can use https://github.com/TheCrypt0/yi-hack-v4

**Comment by xfceKris** [comment]
That's a no-go. I've tried V4, V6, and MStar. None of them flash. They all have the exact same behavior. That is, a normal boot up and connection to wifi.

**Comment by rogerb831** [comment]
I'm having the same experience on a BFUS I just bought yesterday.

**Comment by rogerb831** [comment]
Actually my issue seems to be related to issue #91

**Comment by roleoroleo** [comment]
If it's the same issue, your cam is not MStar based.
So this hack is not compatible.
You can check it connecting a serial adapter and dumping the log.

**Comment by xfceKris** [comment]
If it's not MStar based, then one of the other hacks should work either V4 or V6, and neither one of those works either. Could it be that the manufacturer is simply mix and matching hardware and software as a way to block these hacks?

How would I go about connecting a serial adapter to dump logs? And what would another solution be if I can't get that done? simply try different hacks until one works (or bricks the camera)?

**Comment by roleoroleo** [comment]
See the wiki for the dump:
https://github.com/roleoroleo/yi-hack-MStar/wiki/Dump-your-backup-firmware

**Comment by Matchlighter** [comment]
I'm running into this with a 9FUS as well. I cracked it open and it is indeed not an MStar chip - it doesn't have a discernible manufacturer, but it has a logo and `QG2101A`. I'll see about trying to find the UART lines and getting some logs.

![IMG_20200316_224905](https://user-images.githubusercontent.com/2131857/76823042-7f074080-67d8-11ea-92b6-253b73399440.jpg)

**Comment by roleoroleo** [comment]
Use TX and RX.
And see this issue:
https://github.com/roleoroleo/yi-hack-MStar/issues/91

**Comment by roleoroleo** [comment]
@Matchlighter 
Could you take a picture of the other side?

**Comment by Matchlighter** [comment]
![IMG_20200323_100133](https://user-images.githubusercontent.com/2131857/77340705-4e049f80-6cf3-11ea-8d70-1f140d534493.jpg)

**Comment by roleoroleo** [comment]
Thank you.

**Comment by xfceKris** [comment]
Any update as to weather or not this will be updated to work with the 6fus with stock firmware 2.1.0.0E?

**Comment by roleoroleo** [comment]
Please connect a serial adapter and dump the log.
I will check which platform is.

**Comment by roleoroleo** [comment]
See here:
https://github.com/roleoroleo/yi-hack-Allwinner/

**Comment by CaptianNemo** [comment]
If you re-read the OP, you'll see he has a 6FUS and not the 9FUS that Matchlighter has. You will also see his camera reports running 2.1.0.0E and not 8.2.0.0A which is Matchlighter's version.
I also have a 6FUS running 2.1.0.0E and have taken it apart, it is not the same as Matchlighter's. It does have an MStar chip. I belive this is a valid issue and should be re-opened.
![IMG_0234](https://user-images.githubusercontent.com/1875246/80554615-5e173b00-8993-11ea-878a-dccb18c789b3.JPG)
![IMG_0230](https://user-images.githubusercontent.com/1875246/80554618-61aac200-8993-11ea-814d-85570ee66e57.JPG)
![IMG_0232](https://user-images.githubusercontent.com/1875246/80554624-64a5b280-8993-11ea-9046-fee60f5bac34.JPG)
![IMG_0233](https://user-images.githubusercontent.com/1875246/80554631-67a0a300-8993-11ea-8abb-c8c0acab97f7.JPG)

**Comment by roleoroleo** [comment]
I need a log of the boot to study this model.
At the moment is not supported.

**Comment by CaptianNemo** [comment]
I'll see if I can get those logs for you. Might be about a week though, I ordered a flux pen for the tiny solder job, and amazon says it'll take about a week to get here.

**Comment by CaptianNemo** [comment]
[Yii_log_boot.log](https://github.com/roleoroleo/yi-hack-MStar/files/4596131/Yii_log_boot.log)

**Comment by roleoroleo** [comment]
It seems a MStar based cam with a different wifi chip.
The model prefix is y23.
I could try to add this model to the hack but I need the dump of the flash.

**Comment by CaptianNemo** [comment]
Dumping the flash is covered in https://github.com/roleoroleo/yi-hack-MStar/wiki/Dump-your-backup-firmware under "dump sys_XXX" and "dump home_XXX", correct?

**Comment by roleoroleo** [comment]
Yes.

**Comment by CaptianNemo** [comment]
[new_6fus_dump.zip](https://github.com/roleoroleo/yi-hack-MStar/files/4625162/new_6fus_dump.zip)

**Comment by roleoroleo** [comment]
Try this beta:
https://drive.google.com/open?id=1yb22W8clLFR8sDAjiwyDctTM4uZSzV83

**Comment by CaptianNemo** [comment]
Flashed successfully and camera's webpage shows up. Is there anything you want me to test while I still have wires soldered to it? I really appreciate you taking time to add this model.

**Comment by roleoroleo** [comment]
Please, try the main feature:
1. RTSP
2. Snapshot
3. ONVIF
4. Mqtt

**Comment by CaptianNemo** [comment]
RTSP - Working normally.
Snapshot - Working normally.
ONVIF - I think it's working, but the app I used (lingodigit) is having problems. 
Mqtt - I don't think I can test this, it seems to require a raspberry pi. The only raspberry pi I own is a zero (regular, not zero-w), which the home assistant website says is not recommended.

**Comment by roleoroleo** [comment]
You can test mqtt with a generic broker, home assistant is not necessary.
But if you can test it, it doesn't matter.
I will add y23 support in the next release.
