### ISSUE TITLE
Y25 becomes bricks after updating official firmware.

### ISSUE THREAD

**Issue by imakou** [roleoroleo/yi-hack-MStar#116]
Hi Guys,

I don't know where I can get help.
I hope you don't mind that I am asking the questions here.

So, yesterday, my two Yi home camera3 died back to back after updating official firmware through mobile APP. 
The worth thing is that the reset function doesn't work.
The camera just restarts itself with "click" sound and flashes orange light slowly.
I cannot rest and repair my cameras.

Does anyone know how to fix the camera in this situation?
Thanks.

**Comment by roleoroleo** [comment]
Please, give me the version number you installed.

**Comment by imakou** [comment]
> Please, give me the version number you installed.

I'm not sure the version I installed.
Because I lost the paired cameras in my app since this failing.
But, I check the website, it seems that the latest version for Y25 is `4.2.0.0H_201909041620`.

Thanks.

**Comment by roleoroleo** [comment]
You could try to reload the firmware.
Download the file, copy it on a SD card, insert in the cam and start.
Try with 4.2.0H.
If the firmware upgrade doesn't start try with the 4.2.0F.

http://download.eu.xiaoyi.com/yifirmware/smarthomecam/familymonitor-y25/4.2.0.0F_201905241332home_y25m
http://download.eu.xiaoyi.com/yifirmware/smarthomecam/familymonitor-y25/4.2.0.0H_201909041620home_y25m

Please, let me know when you "copy & paste" this message because I will remove the links.

**Comment by imakou** [comment]
> You could try to reload the firmware.
> Download the file, copy it on a SD card, insert in the cam and start.
> Try with 4.2.0H.
> If the firmware upgrade doesn't start try with the 4.2.0F.
> 
> http://download.eu.xiaoyi.com/yifirmware/smarthomecam/familymonitor-y25/4.2.0.0F_201905241332home_y25m
> http://download.eu.xiaoyi.com/yifirmware/smarthomecam/familymonitor-y25/4.2.0.0H_201909041620home_y25m
> 
> Please, let me know when you "copy & paste" this message because I will remove the links.

Copied.
Will try when I get my sd card. It's on the way to my home.
Thanks.

**Comment by imakou** [comment]
Update:
I just went to a local store to buy a 64GB Class10 microSDXC.
And I format it as fat32 and put the files you recommend into the sd card.
BUT, it seems nothing happen....

**Comment by roleoroleo** [comment]
Mmmmh
Probably an older sd it's better.
Do you have something smaller?

**Comment by imakou** [comment]
No. I don't.
Should I buy another 16GB sd card?
The 16GB sd card's price is the same as 32GB, lol.
BTW, I can see the camera wrote `log` folder to my SD card.

**Comment by imakou** [comment]
I think that I may need to return these two cameras.
That is very frustrating because I really need cameras to monitor my baby.
Starting to order Yi Camara 1080P version, not Camera 3.
It's very hard to get information about Camera 3 from Google.

**Comment by roleoroleo** [comment]
The cam sees the sd card when the fw is loaded.
But the upgrade procedure is started from the bootloader and you don't know if it sees the card.
Try to reformat the card from a linux machine.

**Comment by imakou** [comment]
I re-formated my card by MacOs.
The card shows its format is `DOS_FAT_32`.
Is it expected? Thanks.

**Comment by roleoroleo** [comment]
I think it's correct.
Copy the file on the card.
Rename it home_y25.
Insert the sd card.
Reboot.

**Comment by imakou** [comment]
Hi,
I'm thinking of buying another 16GB SDXC.
But, I don't know if we can fix my problem by re-loaded firmware?
Is my case fixed by re-loaded firmware..?

Thanks.

**Comment by imakou** [comment]
Roleo,
I very appreciate for the help.
It seems that something is changed.
The camera doesn't make the "Click" sound after I renamed the file name.
But, the camera doesn't reboot....

**Comment by roleoroleo** [comment]
Ok, try this:
https://drive.google.com/open?id=1GC9Aw1SvOpTi6fma52O5Ub2hjAGhh-Pa

Copy the file on the card.
Don't rename it.
Insert the sd card.
Reboot.

**Comment by imakou** [comment]
Roleo,
The file WOKRS!
My cameras are ALIVE!!!!!!!!!
THANKS VERY MUCH!!

But, what happens? How can this file work?

**Comment by roleoroleo** [comment]
Because this file completely rewrite your partition and renew all the content.

**Comment by imakou** [comment]
Roleo,
How do you know that I should use that file to rewrite my camera?
 I could not find a file which fits my camera, but yours works.

**Comment by roleoroleo** [comment]
This file is a dump of a real camera (same model as yours).

**Comment by imakou** [comment]
> This file is a dump of a real camera (same model as yours).

I see.
Thanks for your help.
BTW, I couldn't get the firmware from YI official website which doesn't make sense :(

**Comment by roleoroleo** [comment]
You can download a firmware from Yi site but it's only a partial update.
It isn't useful for recovery purposes.

**Comment by imakou** [comment]
Yi tech just announces the mistake they made and provides a solution.
It's the same as you provided.

[Link](https://forum.yitechnology.com/t/yi-home-camera-3-firmware-revision/223?utm_source=NA+Audience&utm_campaign=84d7c09af3-EMAIL_CAMPAIGN_2020_03_23_03_29&utm_medium=email&utm_term=0_fa305f78ea-84d7c09af3-95687410&mc_cid=84d7c09af3&mc_eid=69ec5d6c13)

**Comment by roleoroleo** [comment]
No, is not the same but probably it works.
