### ISSUE TITLE
0.2.9 Can't change camera settings

### ISSUE THREAD

**Issue by dnorman12345** [roleoroleo/yi-hack-MStar#118]
Can't make chages to camera settings page. Says "Sensitivity not valid" when you try to save. It doesn't matter which option you choose for sensitivity. I was just trying to turn off IR.

Using y203c on 6FUS

**Comment by Extreme79** [comment]
Try to simply clear browser cache (or with chrome, reload page with ctrl pressed).
After firmware update I got many issues (no logo, unable to save config, unable to choose free sd space percentage..). Reloaded ignoring cache solved anything (dome bfus and home )

**Comment by dnorman12345** [comment]
Thanks. That worked.
