### ISSUE TITLE
Feature Request: Just audio recording

### ISSUE THREAD

**Issue by agsola** [roleoroleo/yi-hack-MStar#119]
Just audio recording possibility.

**Comment by roleoroleo** [comment]
If you mean audio when you record mp4 yes.
Otherwise I tried but I have not succeeded.
See https://github.com/roleoroleo/yi-hack-MStar/issues/21
and https://github.com/roleoroleo/yi-hack-MStar/issues/32

**Comment by agsola** [comment]
Ok. It's a pity. Thank you.
