### ISSUE TITLE
Feature Request: Motion sensor (MQTT) working while not recording

### ISSUE THREAD

**Issue by agsola** [roleoroleo/yi-hack-MStar#123]
I've seen that when the camera is off (using config "Switch on/off the camera") I can still stream the camera (as desired), but I can't use the motion sensor through MQTT.
Therefore, the only option to use the MQTT sensor is to record in the SD Card.

Could an option to use the sensor while not recording be added?

**Comment by roleoroleo** [comment]
This is related to Yi's original firmware.
I can not do anything about it.
