### ISSUE TITLE
Can't flash 4FUS

### ISSUE THREAD

**Issue by vekexasia** [roleoroleo/yi-hack-MStar#124]
Hello, I downloaded the y203 and followed the instructions.

The camera seems to not want to flash as when it boots up the yellow will appear for a couple of seconds and then it turns blue.

Checking the app the camera has 4.2.0 firmware

**Comment by vekexasia** [comment]
I tried both y25 and y203c but always the same habit. seems to not care about the sdcard at all. Checked and the sdcard is fat32 16Gig and files were placed in the root folder.

**Comment by rafal98** [comment]
same behaviours with a 9FUS and y203c (0.2.9). Tested with a 32 GB and a 16 GB sd card (FAT32)

**Comment by roleoroleo** [comment]
@vekexasia 
Try another SD card.
It's a common problem.
