### ISSUE TITLE
can't Flash 9FUS Y21XD9

### ISSUE THREAD

**Issue by fjcabello** [roleoroleo/yi-hack-MStar#126]
Hi,
I have this camera and I have tried flashing with (sys_y25 and home_y25)
Firmware version is 4.5.0.0C_201910080934.

Is it possible to flash this camera?

Thanks!

**Comment by roleoroleo** [comment]
Read the readme.
You have to use y203c, not y25.

**Comment by fjcabello** [comment]
Thanks, you are right. Sorry for the mistake.
