### ISSUE TITLE
log continue saying dispatch.c(p_worker-3375) rcd may crashed 

### ISSUE THREAD

**Issue by divemasterjm** [roleoroleo/yi-hack-MStar#130]
[3/30/14:6:31:523]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:7:32:563]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:8:33:422]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:9:34:207]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:10:35:55]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:11:35:838]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:12:36:791]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:13:37:642]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:14:38:428]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:15:39:310]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:15:41:471]: dispatch.c(check_wifi_connect-1596) signal_quality(100)[
][3/30/14:16:40:147]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:17:41:223]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:18:42:74]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:19:43:188]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:20:43:957]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:21:44:631]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:22:21:251]: mp4record.c(send_mp4rcd_heartbeat_msg-911) msg snd success[
][3/30/14:22:21:345]: dispatch.c(do_mq_process-4915) got rcd heartbeat
[
][3/30/14:23:22:159]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:24:22:902]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:25:23:365]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:25:43:589]: dispatch.c(check_wifi_connect-1596) signal_quality(87)[
][3/30/14:26:24:186]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:27:25:286]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:28:26:121]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:29:27:7]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:30:27:778]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:31:28:590]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:32:29:549]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:33:30:242]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:34:31:179]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:35:8:215]: p2p_tnp.c(p2p_set_debug_info-1503) p2p_set_debug_info send_msg ok!
[
][3/30/14:35:8:306]: p2p_tnp.c(state_statistics-6247) check_login fail 0
[
][3/30/14:35:8:306]: dispatch.c(do_mq_process-5109) invalid msg 0x6008
[
][3/30/14:35:8:520]: cloud.c(yi_report_debug_info-4354) yi_report_debug_info cmd: /home/app/cloudAPI -c 415 -url "http://log.eu.xiaoyi.com/info.gif?function=p2ptrack&version=4.5.0.0C_201910080934&did=9FUSY21VILNHFX191010" -filename /tmp/debug_p2p.txt
[
][3/30/14:35:9:415]: cloud.c(yi_report_debug_info-4358) yi_report_debug_info ret_string: src_len = 218, out_len = 114, base64_len = 152, 2, 0
{"code":20000}

[
][3/30/14:35:9:415]: cloud.c(yi_report_debug_info-4364) yi_report_debug_info success
[
][3/30/14:35:31:930]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:35:45:674]: dispatch.c(check_wifi_connect-1596) signal_quality(100)[
][3/30/14:36:32:827]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:37:33:625]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:38:34:509]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:39:3:273]: mp4record.c(send_mp4rcd_heartbeat_msg-911) msg snd success[
][3/30/14:39:3:348]: dispatch.c(do_mq_process-4915) got rcd heartbeat
[
][3/30/14:40:3:866]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:41:4:762]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:42:5:608]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:43:6:635]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:44:7:515]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:45:8:505]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:45:47:375]: dispatch.c(check_wifi_connect-1596) signal_quality(100)[
][3/30/14:46:9:396]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:47:10:240]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:48:11:53]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:49:11:890]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:50:12:611]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:51:13:455]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:52:14:191]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:53:15:216]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:54:15:896]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:55:16:795]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:55:45:314]: mp4record.c(send_mp4rcd_heartbeat_msg-911) msg snd success[
][3/30/14:55:45:388]: dispatch.c(do_mq_process-4915) got rcd heartbeat
[
][3/30/14:55:49:275]: dispatch.c(check_wifi_connect-1596) signal_quality(100)[
][3/30/14:56:45:809]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:57:46:782]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:58:47:599]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/14:59:48:707]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:0:49:588]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:1:50:355]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:2:51:258]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:3:51:938]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:4:52:692]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:5:35:680]: dispatch.c(p_worker-3270) write_flash num = 0
[
][3/30/15:5:45:83]: p2p_tnp.c(tnp_proc-6589) PPPP_Listen_With_Key failed, ret = -3003
[
][3/30/15:5:51:526]: dispatch.c(check_wifi_connect-1596) signal_quality(96)[
][3/30/15:5:53:665]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:6:54:490]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:7:55:193]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:8:56:60]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:9:56:792]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:10:57:617]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:11:58:626]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:12:27:334]: mp4record.c(send_mp4rcd_heartbeat_msg-911) msg snd success[
][3/30/15:12:27:423]: dispatch.c(do_mq_process-4915) got rcd heartbeat
[
][3/30/15:13:27:668]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:14:28:571]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:15:29:444]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:15:53:535]: dispatch.c(check_wifi_connect-1596) signal_quality(99)[
][3/30/15:16:30:187]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:17:31:228]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:18:32:114]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:19:33:0]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:20:33:940]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:21:34:777]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:22:35:599]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:23:36:394]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:24:37:127]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:25:38:31]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:25:55:889]: dispatch.c(check_wifi_connect-1596) signal_quality(100)[
][3/30/15:26:38:946]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:27:39:797]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:28:40:635]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:29:9:352]: mp4record.c(send_mp4rcd_heartbeat_msg-911) msg snd success[
][3/30/15:29:9:424]: dispatch.c(do_mq_process-4915) got rcd heartbeat
[
][3/30/15:30:9:598]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:31:10:483]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:32:11:381]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:33:12:78]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:34:12:972]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:35:13:703]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:35:57:779]: dispatch.c(check_wifi_connect-1596) signal_quality(100)[
][3/30/15:36:14:536]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:37:15:320]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:38:16:108]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:39:16:917]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:40:17:893]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:41:18:739]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:42:19:743]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:43:20:582]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:44:21:369]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:45:22:156]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:45:51:389]: mp4record.c(send_mp4rcd_heartbeat_msg-911) msg snd success[
][3/30/15:45:51:452]: dispatch.c(do_mq_process-4915) got rcd heartbeat
[
][3/30/15:46:0:162]: dispatch.c(check_wifi_connect-1596) signal_quality(100)[
][3/30/15:46:52:540]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:47:53:498]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:48:54:321]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:49:55:177]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:50:55:948]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:51:56:666]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:52:57:527]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:53:58:289]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:54:59:212]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:55:59:949]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:56:2:115]: dispatch.c(check_wifi_connect-1596) signal_quality(100)[
][3/30/15:57:0:925]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:58:1:801]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/15:59:2:695]: dispatch.c(p_worker-3375) rcd may crashed
[
][3/30/16:0:3:531]: dispatch.c(p_worker-3375) rcd may crashed

**Comment by roleoroleo** [comment]
This is a component of the original firmware.
I can't solve it.
