### ISSUE TITLE
Yi IOT Outdoor camera supported ?

### ISSUE THREAD

**Issue by vinceHH** [roleoroleo/yi-hack-MStar#132]
Hello,

First of all, thanks for your work, I'm curently using your firmware for 2 Yi 1080p home and it's working really fine !

I've just bought a new model : Yi IOT Outdoor camera and it seems not supported for now :(

I can telnet to port 23 with root (no password), and read some logs, but nothing else.

/proc/cpuinfo is like this:

```
system type             : RLX Linux for IPCam Platform
machine                 : Unknown
processor               : 0
cpu model               : Taroko V0.2  FPU V0.1
BogoMIPS                : 497.66
tlb_entries             : 64
mips16 implemented      : yes
```
Really appreciated your comments

**Comment by roleoroleo** [comment]
Sorry, is not supported.
