### ISSUE TITLE
0.3.0 bricked y203c 

### ISSUE THREAD

**Issue by myromeo** [roleoroleo/yi-hack-MStar#137]
Updated one home 1080p y203c camera via web interface, failed but camera online. No info shown on web interface. 

Updated second home 1080p y203c camera via SD following download and extract, failed, camera wont boot, stuck on amber light. 

Both ok previously in 0.2.9. 

Roll back please?

**Comment by roleoroleo** [comment]
Please, try to reload 0.2.9.

**Comment by myromeo** [comment]
0.2.9 reinstalled without issue. I’ll format card, redownload 0.3.0 tomorrow and try again. 

Keep up the great work

**Comment by myromeo** [comment]
Re downloaded 0.3.0 and installed ok with SD card, must have been corrupt download. Thanks.
