### ISSUE TITLE
latest still image

### ISSUE THREAD

**Issue by divemasterjm** [roleoroleo/yi-hack-MStar#138]
Hi there is a time lap between still frame and last frame, how we can get the current frame on notification? my homekit notifications gets always non current live frame.

**Comment by roleoroleo** [comment]
Sorry, I don't understand.

**Comment by divemasterjm** [comment]
the snapshots are not in realtime.

**Comment by roleoroleo** [comment]
Compared to the rtsp stream?

**Comment by divemasterjm** [comment]
yes, when i receive notification with snapshot or look for snapshot on homekit app always is not real time snapshot

**Comment by divemasterjm** [comment]
here is my config
"videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.8.221:554/ch0_0.h264",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://192.168.8.221:554/ch0_0.h264 -vframes 1 -r 1",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "debug": false,
                        "audio": false

**Comment by roleoroleo** [comment]
Try to use (if it's possible with homekit) the http protocol.
http://192.168.8.221:8080/cgi-bin/snapshot.sh
The image retrieved with ffmpeg could be very slow.

**Comment by divemasterjm** [comment]
do you know how to say to ffmpeg to retreive http?

**Comment by roleoroleo** [comment]
No, sorry.
