### ISSUE TITLE
9FUS Y25 / Y203C

### ISSUE THREAD

**Issue by paulioliolio** [roleoroleo/yi-hack-MStar#139]
Yi 1080p Home v3 on stock 4.2.0.0H_201909041620  firmware.
I have tried the Y25 and the Y203C firmware here and the Home 1080P firmware from yihack v4 each on 2 separate 16GB SD cards, but none will flash, the device just starts as normal. 

Looks like an MStar device to me!

![20200406_121101](https://user-images.githubusercontent.com/6709056/78560999-eb40f700-780e-11ea-95f1-88d5bc90aa99.jpg)

![Inked20200406_112127_LI](https://user-images.githubusercontent.com/6709056/78560816-91403180-780e-11ea-8777-37e377653215.jpg)

![20200406_112350](https://user-images.githubusercontent.com/6709056/78560543-27c02300-780e-11ea-8435-3c91c991b4a4.jpg)

**Comment by roleoroleo** [comment]
Your fw is y25.
Try again with a different sd card.

**Comment by paulioliolio** [comment]
Thanks, re-formatted both cards on my Linux machine (formatted under windows previously) and tried again with Y25 files (both in root) but still not flashing new firmware.

**Comment by paulioliolio** [comment]
Third time lucky! Found another card and this one works perfectly. Thanks!

**Comment by paulioliolio** [comment]
Took me a while to discover that FTP uses same credentials as telnet. And I can't get the camera working on my QNAP (no alarm recording!) but I suspect that's because it's not the best NVR. Thanks for the great work.
