### ISSUE TITLE
0.3.0 camera stop working after some time from homebridge

### ISSUE THREAD

**Issue by divemasterjm** [roleoroleo/yi-hack-MStar#140]
SInce upgrade firmware, camera stops working on homebridge/homehit after some time, i have to reboot everytime to work, web interface is working but rtsp no

**Comment by roleoroleo** [comment]
Try to downgrade to 0.2.9 and repeat the upgrade to 0.3.0.

**Comment by divemasterjm** [comment]
I did but same results, had to go back to 0.2.9

JuanMa

**Comment by divemasterjm** [comment]
can be having both streams activated? after some testing leaving only one channel seems to work, after 3h still running.

**Comment by roleoroleo** [comment]
The cpu and memory performance is very low.
I think it's a good idea to use only one stream.
