### ISSUE TITLE
Alexa support

### ISSUE THREAD

**Issue by fjcabello** [roleoroleo/yi-hack-MStar#142]
Hi,
I guess Alexa support is not working with the firmware. Do you have an idea how to enable it?
Also, I was wondering how you managed to maintain compatibility with yihome app. Did you implement the same API? Do you have a daemon to connect with yihome servers? Any documentation about how this is implemented?

Thanks

**Comment by roleoroleo** [comment]
All my feature are added.
If you set cloud enable, the yi processes are running.
You cannot have alexa with cloud disabled.

**Comment by fjcabello** [comment]
Thanks. It should be a different issue not related to yi-hack.
One question, in this firmware, are you including the original yihome applications? I mean, in order to keep compatibility with the app.

Thanks

**Comment by roleoroleo** [comment]
Th original app are untouched.
Are stopped only if cloud option is disabled.
