### ISSUE TITLE
Adding remote control

### ISSUE THREAD

**Issue by metalnodeug** [roleoroleo/yi-hack-MStar#147]
Hi 

I don't know if you can help but this is my issue. I have a YI DOME 1080P model h20 and I use in the past the Yi-Hack original from TheCrypt0 but unfortunately the project is dead since 1 year.

I use my cam with disable cloud and I showing the stream with my Synology NAS but when my connection restart or I reboot the cam, she reset the position. 

I will know if it's possible to add to my cam, remote control ? And if it's possible, how ?

I have test to reset my camera for updating, upgrading and restore the firmware but nothing. Doesn't work and I don't know why ?!

Thanks a lot for your help.

**Comment by roleoroleo** [comment]
Do you mean ptz support?

**Comment by metalnodeug** [comment]
Yes I thing

**Comment by roleoroleo** [comment]
Probably Hisilicon cams use the same method as MStar.
On my fw, you can use ipc_cmd program to send ptz commands.
You can move left, right, up, down and go to a saved preset.
You could try to cross compile the sources and check if it works.

**Comment by metalnodeug** [comment]
I can't upgrade or dowgrade the firmware. The process doesn't work.
I use an SD Card, upload the 2 files at root path, disconnect the cam, insert sd card, power on the cam and the cam boot normally :/ she will not launch the process. My process are faulty ? Have you an idea ?

**Comment by roleoroleo** [comment]
If you are using TheCrypt0 fw you can't use MStar firmware.
Different platform.
