### ISSUE TITLE
Timezone for UK

### ISSUE THREAD

**Issue by leeablett** [roleoroleo/yi-hack-MStar#150]
Hi there,

I live in the UK and when I set the timezone to "GMT0BST,M3.5.0/1,M10.5.0" it is either not setting or one hour out.

**Comment by roleoroleo** [comment]
When you set it and reload configuration page, can you see the correct value?

**Comment by leeablett** [comment]
No, it looks like the value is not saving....

**Comment by leeablett** [comment]
how odd, tried IE and it worked but there seems to be an issue with Chrome on MS Windows 10.

**Comment by leeablett** [comment]
Look like there may be a js error on chrome... DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map

**Comment by leeablett** [comment]
Ignore that error as that was lastpass and now removed. Still does not show the value in chrome though.  Have set through IE which works fine.

**Comment by roleoroleo** [comment]
Interesting.
