### ISSUE TITLE
9FUS unable to get wifi persistent

### ISSUE THREAD

**Issue by sfl3005** [roleoroleo/yi-hack-MStar#152]
Hi roleo,

I start my 1080p camera with y203c 0.3 on sd card, I try to add in xiaomi application but after device is connected to wifi (LED is blue) mobile phone application times out.
Yi-hack admin page is reachable but after camera restart I still heard "welcome to xiaoyi camera waiting to connect" and wifi connection is not persistent.

if I look to SD card, there is several logs files.
I try to install an earlier y203c version but y203c is still present with same version. It seems like I am unable to flash an other time.

I have SSH and telnet access to camera after wizard boot.
I tried on two SD card one of 16G and one of 8G same issue.
sadly,  disabled cloud feature or not is same issue 
![yi-hack](https://user-images.githubusercontent.com/6570108/79765677-371f9000-8327-11ea-849f-2d2f90cee113.jpeg)
![telnet](https://user-images.githubusercontent.com/6570108/79766982-017ba680-8329-11ea-85c6-c5cd031c22c0.jpeg)
![general](https://user-images.githubusercontent.com/6570108/79767206-4c95b980-8329-11ea-89df-f92bd142ef42.jpeg)

Please help me 
Kind regards
Sfl

**Comment by roleoroleo** [comment]
Try to reset the fw with the reset button.

**Comment by sfl3005** [comment]
Already done. Reset successful message heard but no change to the issue. Unable to add to xioami app.

**Comment by sfl3005** [comment]
I downgrade the camera successfully
![downgrade](https://user-images.githubusercontent.com/6570108/79788627-3dbeff00-8349-11ea-8279-a6105fd54611.jpeg)

And upgrade it online throught web interface but same issue
Every time camera reboot runs xiaomi startup wizard

**Comment by sfl3005** [comment]
I was used wrong mobile apps. xiaomi home vs YI HOME.
with the correct apps every thing works like a charm !

What a shame !
Thanks to have take time to read !
