### ISSUE TITLE
Camera Model 9FUSY21JRY

### ISSUE THREAD

**Issue by gr3k** [roleoroleo/yi-hack-MStar#158]
Hi, 
It looks like this hack doesn't work for my version of camera.
I have a model : 9FUSY21JRY61 with fw: 4.5.0.0C_201910080934 , Yi 1080p Home Camera : YYS.2016

I have tried y203c in version: 0.3.1 , 0.3.0 0.2.9 without any success.
When I powered on the camera. Led is solid orange and after a while blinking blue to solid blue. 
Camera is avaiable via YI Home app ... 
on card I don't have any log files to do any troubleshooting.

Previously i have tried also a fw TheCrypt0/yi-hack-v4 without any success too :( 

Do You have any idea with any workaround?

**Comment by roleoroleo** [comment]
I am 90% sure that y203c works.
Try again with another sd card.
