### ISSUE TITLE
Play multiple videos in a row?

### ISSUE THREAD

**Issue by Millennium-bug-82** [roleoroleo/yi-hack-MStar#159]
Is there an easy way to play multiple videos in a row?

What I do now is open the Motion Events in Firefox (Chrome downloads instead of plays), click a video, watch it, go back and repeat. Is there a way to start at a certain point and then automatically go to the next video?

**Comment by roleoroleo** [comment]
Probably with js coding.
But I'm not very experienced in this skill.
