### ISSUE TITLE
FW does not load on BFUSY YI HOME 1080P

### ISSUE THREAD

**Issue by LIR131** [roleoroleo/yi-hack-MStar#163]
Hi everybody,

I tried to install the yi-hack-MStar 0.3.1 following instructions.
Led does not blink yellow.
After power on the led is yellow for about 15 seconds, and after blinking blue, and finally stay blue.

Could someone give some help plz?

Note that my current fw is 8.2.0.0A_201912270941

**Comment by michael11123** [comment]
you use 16G or 32G SD?

**Comment by LIR131** [comment]
32G SD Samsung EVO Plus

**Comment by roleoroleo** [comment]
Your cam is not supported.
See here: https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by LIR131** [comment]
Ok thanks.
All winners flash it.
So rtsp is not reachable.
Can't watch the stream in vlc. Do allwinner-yi-hack implement rtsp for my camera?

**Comment by roleoroleo** [comment]
If the issue is not solved, please open a new issue in the allwinner repo.
