### ISSUE TITLE
YI 1080 9FCN error

### ISSUE THREAD

**Issue by michael11123** [roleoroleo/yi-hack-MStar#165]
hi everyone.
i just bought a yi 1080 9FCN. 
.i installed y203c to hack my Yi.
it's ok until " conneted wifi" and then a voice of chinese rang out.
so i finish process.
please support me.
thanks you so much.

**Comment by michael11123** [comment]
![IMG_20200430_112906](https://user-images.githubusercontent.com/46898583/80794426-16c3c100-8bc4-11ea-876f-858c7adedfd3.jpg)
Picture

**Comment by michael11123** [comment]
https://youtu.be/b3MEIlOYarY

**Comment by roleoroleo** [comment]
9FCN means that the cam is for the Chinese market.
Maybe other users with 6FCN can give you an answer.

**Comment by michael11123** [comment]
I hope so :(

**Comment by bonuzzz** [comment]
if wifi is connected so you should open camera web interface. btw my cams are not speaking at all with this custom firmware, so if web interface is not available, firmware probably has not been flashed successfully.

**Comment by michael11123** [comment]
Camera talk only be used in china. And the fw has not been flashed. So i can access web interface.

**Comment by menway** [comment]
> https://youtu.be/b3MEIlOYarY

Any luck with your camera? ^_^

What the Chinese voice said was: binding failed, wrong device type selected.

**Comment by roleoroleo** [comment]
Closed due to inactivity.
