### ISSUE TITLE
Setting timezone vs. yi app and rewind option

### ISSUE THREAD

**Issue by majkers** [roleoroleo/yi-hack-MStar#167]
Hi is possible for You to let someone set timezone via Your firmware and make rewind/playback option in yi app work properly? I have found this issues https://github.com/shadow-1/yi-hack-v3/issues/158 and https://github.com/TheCrypt0/yi-hack-v4/issues/68 but without solution. Is it possible?

**Comment by roleoroleo** [comment]
No sorry. It's not possible.
If you often use the app you should not change the timezone.

**Comment by Igonzalezz** [comment]
I know this is an old tread but this can be achieve by using a mod version of the Yi Home..

**Comment by majkers** [comment]
> mod version of the Yi Home

Any link?

**Comment by Igonzalezz** [comment]
Can't find the original link but it's the APK that I has been using since I changed the TZ file in the /etc path. I got that APK from a Russian thread from 4pda.ru.. hope this can help you..  [Link](https://drive.google.com/file/d/1BoUXBe2nBkeIJtOLOPNz-fmSJQAzREQ_/view?usp=drivesdk)
