### ISSUE TITLE
Sensitivity not valud after upgrade to 0.3.1

### ISSUE THREAD

**Issue by nicoolaro** [roleoroleo/yi-hack-MStar#168]
After upgrade i cant change any settings on "camera settings" page.
Throws error "sensitivity not valid".
Using bfus Yi 1080 Dome.
![Screenshot_20200504-234606](https://user-images.githubusercontent.com/51228711/81016986-c7022580-8e61-11ea-91c6-e8188322fed9.png)

**Comment by roleoroleo** [comment]
There are no changes in this piece of code in 0.3.1.
Did you try from a desktop browser?

**Comment by nicoolaro** [comment]
Desktop works, strange. Ok must be something with my mobile browser. thanks
