### ISSUE TITLE
unable to pair with yi app

### ISSUE THREAD

**Issue by fernando155** [roleoroleo/yi-hack-MStar#169]
Good afternoon.

I flash the sofware this morning, and everything work fine in the first 2h. After that, for no reason, the app wasn't able to connect to the camera and I just delete it from the app and now is not able to pair, and now I have to tell it with wifi to connect in every reset.

Any ideas?

Thank you

**Comment by roleoroleo** [comment]
See here:
https://github.com/roleoroleo/yi-hack-MStar/issues/52
