### ISSUE TITLE
getlastrecordedvideo.sh e topic prefix files

### ISSUE THREAD

**Issue by shandino** [roleoroleo/yi-hack-MStar#170]
hi,
how can i use topic prefix mqtt file?
is possible to recive the last file via mqtt using topix suffix for video list messages ?

and how can i use this new skill? about getlastrecordedvideo.sh  to get videos from http ??

**Comment by roleoroleo** [comment]
> how can i use topic prefix mqtt file?
> is possible to recive the last file via mqtt using topix suffix for video list messages ?
You can use "Topic Suffix for video list message" to get a list of mp4 files saved from the last motion event. This message is sent when the motion stops.

> and how can i use this new skill? about getlastrecordedvideo.sh to get videos from http ??
See the wiki.
