### ISSUE TITLE
Merge question

### ISSUE THREAD

**Issue by majkers** [roleoroleo/yi-hack-MStar#176]
Looks like someone is trying to merge some of Your code to yi hack https://github.com/TheCrypt0/yi-hack-v4/pull/230 Do you think it might work?

**Comment by roleoroleo** [comment]
It depends on the merge.
There are modules that can be ported in other platform without problem.
For example ptz and onvif.

**Comment by majkers** [comment]
In that case I would be much calmer if you'd do that merge...pleaaaase :)

**Comment by majkers** [comment]
Sorry for reopening but...You said that:

> There are modules that can be ported in other platform without problem.
For example ptz and onvif.

Can You please make a fork of  TheCrypt0 repo and port modules that can be ported on cameras with Hi3518e Chipset? I habe 4 yi cameras. One ooutdoor, one home, two dome. One dome plus home with MStar Infinity Chipset and other with Hi3518e Chipset. It drives me nuts that I can do so many cool staff with Your software and can't with Hi3518e Chipset :( Please. I am ready to donate You for this...

**Comment by roleoroleo** [comment]
It's not a donation problem.
I have no time for this.
Which features do you need?

**Comment by majkers** [comment]
It is hard to choose but PTZ and go to preset and FTPupload are the best

**Comment by roleoroleo** [comment]
See this project: https://github.com/alienatedsec/yi-hack-v4

**Comment by majkers** [comment]
Thanks for a tip. I keep my fingers crossed :)
