### ISSUE TITLE
No audio stream: 0.3.3

### ISSUE THREAD

**Issue by gr3k** [roleoroleo/yi-hack-MStar#177]
Hey,
I upgraded 0.3.1 to 0.3.3 
I saw in the changelog that it should be audio stream too.
I'm using vlc and rtsp://cameraip/ch0_0.h264 address stream.
VLC see only video stream, without audio...

**Comment by bonuzzz** [comment]
you should enable audio stream in web interface

**Comment by gr3k** [comment]
Its was enabled by default with HIGH value like a video has. 
I double checked it. 
It is very strange. I disabled cloud, disabled audio ,rebooted. enabled audio again rebooted and now I have audio stream.
