### ISSUE TITLE
rtsp streams in both qualities at the sme time don't work on 0.3.3

### ISSUE THREAD

**Issue by bonuzzz** [roleoroleo/yi-hack-MStar#181]
I think each stream needs own dedicated port anyway

**Comment by roleoroleo** [comment]
It's not necessary.
You can have both stream on the same port.

**Comment by bonuzzz** [comment]
I got working low only stream just right after reboot. It freezes for second each 4-5 seconds or it crashed after 14 sec of stream.  crashed without audio.

**Comment by roleoroleo** [comment]
What is your model suffix?

**Comment by bonuzzz** [comment]
y203c

**Comment by roleoroleo** [comment]
I'm using y203c to test the fw.
What's your config?

**Comment by roleoroleo** [comment]
Try this beta:
[y203c_0.3.3.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/4640008/y203c_0.3.3.tar.gz)

**Comment by bonuzzz** [comment]
https://gist.github.com/bonuzzz/1b6c7e968c880f89d81c0d0bb08488ce
this is my config

**Comment by roleoroleo** [comment]
Apart from the cloud, it is the same configuration that I use.

**Comment by bonuzzz** [comment]
on tested fw rtsp works only on high res profile without audio. highres with audio process doesn't crashed, but stream in vlc doesn't work. in low res profile without audio rrtspserver process crashed and restarted. both streams profile also doesn't work

**Comment by roleoroleo** [comment]
I would be grateful if you would help me do some diagnostics.
Here another version:
[y203c_0.3.3.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/4640197/y203c_0.3.3.tar.gz)

**Comment by bonuzzz** [comment]
no problem. what to check exactly?

**Comment by roleoroleo** [comment]
Rtsp high/low with and without audio.

**Comment by bonuzzz** [comment]
nothing changes

**Comment by roleoroleo** [comment]
What client are you using?

**Comment by bonuzzz** [comment]
vlc on macos

**Comment by roleoroleo** [comment]
Please go here:
https://github.com/roleoroleo/yi-hack-MStar/issues/183
