### ISSUE TITLE
Get motion detection and baby cry detection in homekit ?

### ISSUE THREAD

**Issue by mimes123** [roleoroleo/yi-hack-MStar#184]
Hi is it possible to get the motion detection in homekit and if so can someone please show me the config for it ?

and one more thing is it possible to see the last recorded video in homekit. and if so what is the config for this ?

sorry i am new in this. :)

**Comment by roleoroleo** [comment]
You can configure mqtt to send messages to your broker.
And you can get the last recorded video using web services (see wiki).

**Comment by mimes123** [comment]
Yes but how do I configure this in my config in homebridge ?
I can see the link in wiki but don’t know what to do with it ?

**Comment by roleoroleo** [comment]
Sorry but I don't use homebridge.
Wait for answers from other users.

**Comment by hairychris** [comment]
Easiest thing to do would be to add Home Assistant in the middle. You'd want to setup the MQTT plugin and then add an MQTT Binary Sensor. You can then expose this to HomeKit.
