### ISSUE TITLE
Offline camera on Official app after fw 0.33?

### ISSUE THREAD

**Issue by Extreme79** [roleoroleo/yi-hack-MStar#186]
I'm experiencing the issue in subject after the installation of the 0.3.3 fw.
It's only for me (so I have to search the cause somewhere else) or it's common?

**Comment by Extreme79** [comment]
After my post I downgraded to the fw 0.3.2 and all the cameras back online in the app.

**Comment by r3gamerz** [comment]
is it possible to downgrade the firmware? i'm currently using firmware 0.3.4

**Comment by roleoroleo** [comment]
Yes.
Simply put 0.3.3 on sd.

**Comment by r3gamerz** [comment]
ok, i thought i can't be downgraded
