### ISSUE TITLE
Old original firmware versions

### ISSUE THREAD

**Issue by hiol83** [roleoroleo/yi-hack-MStar#190]
Ok, this is not an issue it's only a question.
I've a Yi 1080p Home BFUS with last firmware installed 8.2.0.0A_201912270941
Where can i find 4.5.0* firmware?

**Comment by bonuzzz** [comment]
4.5.0 are for other camera revision
there are several bfus cameras. i think it's depend on region

**Comment by GeitjeG** [comment]
I had the same. Think it is a Allwinner chip. Check here: [](https://github.com/roleoroleo/yi-hack-Allwinner)
