### ISSUE TITLE
 48/5000 Is the XY-R9829-K2 camera compatible with yihack?

### ISSUE THREAD

**Issue by sonnar1800** [roleoroleo/yi-hack-MStar#191]
![photo_2020-06-05_07-32-05](https://user-images.githubusercontent.com/44772128/83840371-aea25680-a6fe-11ea-834c-0c73e3f51007.jpg)

in the camera does not put anything of X5FUS only XY-R9829-K2

Best regards.

**Comment by roleoroleo** [comment]
No, sorry.
It's not compatible.
