### ISSUE TITLE
yi hack Mstar

### ISSUE THREAD

**Issue by tummerry** [roleoroleo/yi-hack-MStar#193]
good

**Comment by tummerry** [comment]
There is a way to use outside of China. HFCN![image](https://user-images.githubusercontent.com/66394776/84085282-cee05700-aa17-11ea-9eb3-cb6bde28bfe0.jpeg)

**Comment by roleoroleo** [comment]
It depends on the model. HFCN is not enough.
I need to see a boot log as described in the wiki.

**Comment by tummerry** [comment]
Where do I look?

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-MStar/wiki/Dump-your-backup-firmware
