### ISSUE TITLE
Audio experiments to add audio to all streams + noise reduction

### ISSUE THREAD

**Issue by PieVo** [roleoroleo/yi-hack-MStar#194]
I've implemented a different approach for audio in the RTSP server:
- Implements noise reduction based on existing libraries in the camera
- Implements a replicator, so audio can be used for all streams
- Implements an audio only stream

The chain of audio is:
  Mic -> TinyAlsa -> Pipe -> RTSPserver 
And inside RTSP server:
                                                           
  Input -> [Noise reduction filter]* -> uLaw conversion -> Replicator-> stream 1,2,3 clients
                                                                                                    
(\*) Optional enabled
(**) For each additional client internally a replica is created (ReUseFirstSource).

So, the replicator stream is always active and whenever a client connects a new replica is created (and destroyed when the connection is close)

I've created two packages that can be used to test this on the existing 0.3.4 firmware. A short manual is in the release descriptions below:
https://github.com/PieVo/yi-hack-MStar/releases/tag/0.0.1
https://github.com/PieVo/yi-hack-MStar/releases/tag/0.0.2

Anybody cares to test this?

Pull requests can be made from this branch:
https://github.com/PieVo/yi-hack-MStar/tree/0_3_4-audio_replicator_with_noise_reduction
or
https://github.com/PieVo/yi-hack-MStar/tree/0_3_4_audio_replicator_with_noise_reduction_16khz

**Comment by roleoroleo** [comment]
> 
> 
> I can
> 
> y203c 8khz: all three streams are working
> 16khz is also working.
> will stay with last one and check after few hours
> 
> I have lost frames in log:
> frame lost: 100000
> frame lost: 99978
> frame lost: 100010
> frame lost: 99989
> frame lost: 99988
> frame lost: 99965
> frame lost: 99968
> frame lost: 99989
> frame lost: 100000
> frame lost: 99984
> frame lost: 99993
> frame lost: 99977
> frame lost: 99978
> frame lost: 99980
> frame lost: 99994
> frame lost: 100013
> frame lost: 99982
> frame lost: 99972
> frame lost: 99999
> frame lost: 99973
> frame lost: 99983

This is normal.
I don't know if audio management increase this problem, but it's normal.
When the cam processes the i-frame (tipically 10x bigger than p-frame) sometimes the buffer jumps directly to the 3rd frame (2P) and losts the 2nd frame (1P).
I -> 1P -> 2P -> 3P ...

I added the log "frame lost" to check this behavior.
The number in the log is the difference between the timestamps of the frames.
100000 means 100 ms, so one frame is missing @ 20 fps.

**Comment by bonuzzz** [comment]
after night audio stopped working. video continues streaming

**Comment by PieVo** [comment]
> after night audio stopped working. video continues streaming

Low or high stream?
What kind of client did you use? So I can run that too and check here..

**Comment by PieVo** [comment]
> > I can
> > y203c 8khz: all three streams are working
> > 16khz is also working.
> > will stay with last one and check after few hours
> > I have lost frames in log:
> > frame lost: 100000
> > frame lost: 99978
> > frame lost: 100010
> > frame lost: 99989
> > frame lost: 99988
> > frame lost: 99965
> > frame lost: 99968
> > frame lost: 99989
> > frame lost: 100000
> > frame lost: 99984
> > frame lost: 99993
> > frame lost: 99977
> > frame lost: 99978
> > frame lost: 99980
> > frame lost: 99994
> > frame lost: 100013
> > frame lost: 99982
> > frame lost: 99972
> > frame lost: 99999
> > frame lost: 99973
> > frame lost: 99983
> 
> This is normal.
> I don't know if audio management increase this problem, but it's normal.
> When the cam processes the i-frame (tipically 10x bigger than p-frame) sometimes the buffer jumps directly to the 3rd frame (2P) and losts the 2nd frame (1P).
> I -> 1P -> 2P -> 3P ...
> 
> I added the log "frame lost" to check this behavior.
> The number in the log is the difference between the timestamps of the frames.
> 100000 means 100 ms, so one frame is missing @ 20 fps.

I deliberately did not touch any of the H264 grabber code, but just shove the data into a pipe. I noticed the frame lost reports too, mainly on the low stream.

This audio processing chain adds some CPU but not excessive (~5%). Perhaps the gabber is just not scheduled for 100ms (e.g. due to a flash write io or something). 100ms is quite a lot.. Perhaps set a higher priority for the grabber tasks...

**Comment by roleoroleo** [comment]
> This audio processing chain adds some CPU but not excessive (~5%). Perhaps the gabber is just not scheduled for 100ms (e.g. due to a flash write io or something). 100ms is quite a lot.. Perhaps set a higher priority for the grabber tasks...

I tried a lot of experiments and I think it's not a grabber program.
If you try to open-read-close /proc/mstar/OMX/VMFE0/ENCODER_INFO/OBUF_nTimeStamp (the timestamp associated with the frame) sometimes skip a frame.
I don't know why.
In any case, I could try to increase priority.

**Comment by bonuzzz** [comment]
@PieVo I use vlc and blueiris
both streams lost audio, but I saw audio stream parameters in vlc media information

**Comment by bonuzzz** [comment]
after 1h20m I lost audio. vlc continues decoding audio, but only silence there

**Comment by PieVo** [comment]
Any warning/log messages in the console / nohup.out regarding the audio?

**Comment by bonuzzz** [comment]
I ran ./rtsp_restart.sh ... will test again with more debug

**Comment by bonuzzz** [comment]
after 13 hours everything is working good.  16khz

**Comment by bonuzzz** [comment]
it is still working. to be honest I don't why audio lost at first time, but now it is stable enough.

**Comment by PieVo** [comment]
Sounds good! Here the low 16k stream is open for ~20 hours and still in sync. I'll switch to the high stream and check that for a day...

**Comment by bonuzzz** [comment]
is it any sense here to test 8khz?

**Comment by PieVo** [comment]
> is it any sense here to test 8khz?

The actual frequency of 0.3.4 is 8kHz, I think mainly because that was considered stable after the beta testing.

My preference would be to switch back to the original 16kHz, but perhaps @roleoroleo swicthed to 8kHz for other camera models? (I only have y203). 8kHz uLaw is a more commonly supported format, however I did not find any client that did not support 16k.

So, hopefully we can switch back to 16k. If not we probably need to improve the downsampling, because now the 8kHz just drops 1:2 samples.

**Comment by PieVo** [comment]
> @PieVo I use vlc and blueiris
> both streams lost audio, but I saw audio stream parameters in vlc media information

I was thinking on possible reasons for lost audio. This happens when VLC "gives up" in trying to sync audio and video. That's why it still receives frames, but produces no audio. Perhaps frame-loss on network level could cause this, when an (too many) audio packet is lost, the decoder might give up.

In my experience this seems to happen more often when using PCM instead of some compressed audio format.

**Comment by roleoroleo** [comment]
I introduced 8 KHz audio to reduce the amount of data during the test of the rtsp.

Now, it seems that rtsp is stable.
So, I would like to switch back to 16 KHz in the next release.

**Comment by PieVo** [comment]
High stream with audio still running...

BTW. I have to agree with somebody in another topic that volume is quite low compared to other sources... In a future PR we could spend some CPU cycles to increase the volume.

**Comment by roleoroleo** [comment]
How about overclocking? :laughing:

```
/home/yi-hack # cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
796917
/home/yi-hack # cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
796917
/home/yi-hack # cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
1000000
/home/yi-hack # cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq
400000
```

**Comment by bonuzzz** [comment]
my camera is also working. 3 days uptime. all streams without desync.

**Comment by PieVo** [comment]
> How about overclocking? 😆
> 
> ```
> /home/yi-hack # cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
> 796917
> /home/yi-hack # cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
> 1000000
> /home/yi-hack # cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq
> 400000
> ```
👍  Or some power-saving.. When I run "echo  powersave > scaling_governor" it goes to 400M and the camera just makes it with 1 high stream running...
