### ISSUE TITLE
ipc lens correction

### ISSUE THREAD

**Issue by bonuzzz** [roleoroleo/yi-hack-MStar#195]
on y203c I have two modes only
ipc codes are:
02 00 00 00 08 00 00 00 28 10 01 00 04 00 00 00 64 00 00 00

02 00 00 00 08 00 00 00 28 10 01 00 04 00 00 00 00 00 00 00

**Comment by roleoroleo** [comment]
If you want to try to send these messages you can use ipc_cmd.
Try -f option to read binary code from file.

**Comment by bonuzzz** [comment]
commands don't work from console

**Comment by roleoroleo** [comment]
I tried it and it works.
```
/tmp/sd # echo -n -e '\x02\x00\x00\x00\x08\x00\x00\x00\x28\x10\x01\x00\x04\x00\x00\x00\x64\x00\x00\x00' > lens1.bin
/tmp/sd # echo -n -e '\x02\x00\x00\x00\x08\x00\x00\x00\x28\x10\x01\x00\x04\x00\x00\x00\x00\x00\x00\x00' > lens2.bin
/tmp/sd # ipc_cmd -f lens1.bin
/tmp/sd # ipc_cmd -f lens2.bin
/tmp/sd # ipc_cmd -f lens1.bin
```

With the 2nd ipc_cmd, the image becomes distorted.
With the 3rd ipc_cmd, the image returns normal.

**Comment by bonuzzz** [comment]
great!
I used ipc_cmd wrong and with -x, without binary
