### ISSUE TITLE
Yi 1080p Dome

### ISSUE THREAD

**Issue by jackwilk** [roleoroleo/yi-hack-MStar#196]
Is Yi 1080p Dome Camera version 65US supported by yi-hack-MStar ?

**Comment by roleoroleo** [comment]
No, at the moment.
If you want to help me to support it, I need a log of the boot.
See the wiki.

**Comment by naturalorang3** [comment]
Just disassembled my 65US. Here are the 3 identifiable chips:

Hi3518 ERBC?200 DP156?748 1748-CHINA
MS41909 XC7M54C
MEDIATEK MT7601UN 1806-BMAL CTPH3M62

**Comment by roleoroleo** [comment]
Sorry but this platform is not supported.
Check yi-hack-v5 or previous versions.
