### ISSUE TITLE
How to know if mstar or Hi3518e Chipset

### ISSUE THREAD

**Issue by matteopiccioni** [roleoroleo/yi-hack-MStar#197]
Hello,
I'd like to buy a yi camera from Amazon (.it)
How should I know if the camera will be mstar or not?
Thanks
Matteo

**Comment by roleoroleo** [comment]
It's not possible to know the version of the cam.

**Comment by matteopiccioni** [comment]
Thanks,
and after buying and receiving the cam,
how should I understand which version I have?

**Comment by roleoroleo** [comment]
The final way is connecting a serial interface.
See the wiki.
