### ISSUE TITLE
0.3.4 does not saves Configuration properly

### ISSUE THREAD

**Issue by vip9** [roleoroleo/yi-hack-MStar#198]
After setting input fields, form is sent and the properties are fine, but etc/system.conf is a mess.
e.g. Hostname is not saved in /etc/hostname, DISABLE_CLOUD is set from password field instead of "yes/no", NTP_SERVER is default, not from input, TIMEZONE is not set.

**Comment by roleoroleo** [comment]
Clean the cache of your browser with CTRL+F5.

**Comment by vip9** [comment]
Thank you
