### ISSUE TITLE
udhcpc does not send hostname

### ISSUE THREAD

**Issue by vip9** [roleoroleo/yi-hack-MStar#199]
When requesting ip address, there is no hostname send to dhcpd server on router, thus, it is hardly to find/ping/view camera.
Tried options udhcpc options to send hostname, but no luck.
Probably busybox bug?

**Comment by roleoroleo** [comment]
What option are you using?

**Comment by vip9** [comment]
tried -F <hostname> and -x hostname:<hostname>

**Comment by roleoroleo** [comment]
Using "-x hostname:<hostname>" it works.
Captured with wireshark:

![immagine](https://user-images.githubusercontent.com/39277388/85009625-0610df80-b15f-11ea-8c53-97af84d89239.png)

**Comment by roleoroleo** [comment]
And this is the -F option:

![immagine](https://user-images.githubusercontent.com/39277388/85010129-c7c7f000-b15f-11ea-8bb6-a90e60499282.png)

**Comment by roleoroleo** [comment]
I don't know which is the correct option.
12 or 81?

**Comment by vip9** [comment]
I suppose 12, because host name is not fqdn. 
For me, running `udhcpc -i wlan0 -s /home/app/script/default.script -x hostname:`hostname`` worked.
Option 81 produced double hostname entry, `yi-hackyi-hack.lan `

**Comment by vip9** [comment]
Any way to make that command permanent in wifidhcp.sh? Or somewhere else?

**Comment by roleoroleo** [comment]
You could directly change the file wifidhcp.sh.

**Comment by vip9** [comment]
Will it survive an upgrade?

**Comment by roleoroleo** [comment]
No, sorry...

**Comment by vip9** [comment]
Yup, definetely look for the hack to rewrite that file.

**Comment by roleoroleo** [comment]
I added this feature:
https://github.com/roleoroleo/yi-hack-MStar/commit/8ae90a6372558f97a18473df7a61070295f86335
