### ISSUE TITLE
Unable to update 9FUS 1080p Home Camera

### ISSUE THREAD

**Issue by matteopiccioni** [roleoroleo/yi-hack-MStar#200]
Hello,
I have a DID: 9FUSY31.... 1080p Home Camera

For firmware update I use a SDHC 16GB card, FAT32 formatted 
I copy the file home_y25 and sys_y25 in sd card root
I disconnect power from camera, insert sdcard and power on camera..
After a few minutes of orange and blue light the camera boot as usual and I cant go into ip:8080 page
I tryed with the home_y203c and sys_y203c files too (no success).
My camera stock firmware version is: 8.2.0.0A_201912270941

Maybe my camera is not MStar?
Thanks

**Comment by roleoroleo** [comment]
Try Allwinner.

**Comment by matteopiccioni** [comment]
Thanks! It works fine :)

**Comment by spamsool** [comment]
Could you please provide the link to this allwiner software? I also received 2 pcs of 9FUSY31 cameras and I need an hacked firmware for them. Where can I find this allwiner version?

**Comment by wiktorvip** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by spamsool** [comment]
I have just setup the Y31 version of the camera and noticed immediately that the picture quality of y20gam is much worse then the Mstar version y203c. In fact the average video bitrate is almost 3x higher in the y203 version. Is there anything that could be done about it? Allwinner model has the picture which is just too much compressed and looks horrible.

**Comment by roleoroleo** [comment]
I'm sorry but I don't know how to change parameters of the encoding algorithm.
The main process responsible for encoding is rmm and I think all params are hardcoded.

I already tried to remove the logo but without success.
The logo is a bmp image:

- /home/app/main.bmp for high res
- /home/app/sub.bmp for low res

You can try to change it with another bmp but:

- If you change the image size the system crashes (---> no 1x1 pixels image)
- The system doesn't support alpha channel (---> no transparent image)

**Comment by luciust** [comment]
The new 9FUS with 9.5.0 FW also play nicely with Allwinner version

**Comment by spamsool** [comment]
I wonder what are the changes in FW 9.5.0, Mine does not show this version as available to upgrade.

**Comment by luciust** [comment]
Well this is what this $15 camera came with

**Comment by roleoroleo** [comment]
Probably it's a little bit different platform (e.g. different wifi chip).

@luciust 
Are you able to make a dump of the flash?
I would like to study it.

**Comment by luciust** [comment]
> Probably it's a little bit different platform (e.g. different wifi chip).
> 
> @luciust
> Are you able to make a dump of the flash?
> I would like to study it.

Well it's long gone - but what's the dump procedure? I might get another one within a week.

**Comment by luciust** [comment]
> See the wiki.

OK, I'm going to get access to friends camera (it's in transit). Assuming that this non-invasive method works: https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Dump-your-backup-firmware-(SD-card)? Can't ask him to give me access to soldering UART, so I sure hope so! :)

**Comment by roleoroleo** [comment]
Yes, the SD method doesn't change the original firmware.
When you remove the SD, the cam restarts with the normal features.
