### ISSUE TITLE
FTP username/password

### ISSUE THREAD

**Issue by leeablett** [roleoroleo/yi-hack-MStar#201]
Question
I can't see to ftp to the camera are the credentials the same as the web access?

**Comment by roleoroleo** [comment]
Default is root with blak password.
If you want something better read this: https://github.com/roleoroleo/yi-hack-MStar/issues/24

**Comment by Rushmed** [comment]
Blank password is making trouble on FTP clients such as SolidExplorer on android which save credentials an do not allow to leave PW blank.
Would love to have a default password

**Comment by roleoroleo** [comment]
Yes, Allwinner is different.
Try to change SSH password. Is the same as ftp service.

**Comment by Rushmed** [comment]
> Try to change SSH password. Is the same as ftp service.

Thanks, solved the issue. Maybe hint in web UI will be useful for other users.
