### ISSUE TITLE
Could you please add swapfile option like on yi-hack-Allwinner?

### ISSUE THREAD

**Issue by spamsool** [roleoroleo/yi-hack-MStar#218]
Hello,

I would like to ask you for a new feature:
Could you please add the feature to enable swapfile on sd card to yi-hack-MStar - same like it is already implemented in yi-hack-Allwinner?
Thanks :)

**Comment by roleoroleo** [comment]
Sorry, but there isn't kernel support.
It's not possible.

**Comment by spamsool** [comment]
Fair enough :) Thanks anyway!
