### ISSUE TITLE
Update 0.3.3 > 0.3.5 failed?

### ISSUE THREAD

**Issue by hagenuck1** [roleoroleo/yi-hack-MStar#219]
Hi, 
I had installed 0.3.3 and tried to update yesterday using the web interface. Textfeld showed something similar to „waiting for the camera to come back online“ or so in the end. IP was pingable. But the orange light was on all time and either :8080 webintergace, nor FTP was available. 

Tried downgrade to 0.3.3/ 0.3.4/ 0.3.5 using the SD card, but none of them were working, only ping was possible. 

Installed and tried the YI Camera app now and I can see the image, do anybody of you has any idea how to get mstar installed again? Using an YI 1080, so y203 image.

**Comment by roleoroleo** [comment]
Reset the cam and try hack again.

**Comment by hagenuck1** [comment]
Is there any other reset then inserting the sd card with another image version of mstar hack? That's what I've tried at least 5 times.

**Comment by roleoroleo** [comment]
The upgrade procedure overwrites the flash memory partition.
All files are overwritten

If you want to reset the config too, format the sd before the upgrade.

**Comment by hagenuck1** [comment]
Formatting the SD card and flashing 0.3.5 again did the trick, thanks.
