### ISSUE TITLE
ONVIF preset

### ISSUE THREAD

**Issue by amaia81** [roleoroleo/yi-hack-MStar#222]
Hi. Is there a way to set preset positions for the cam without the yi app? Also, How can I extract the PTZ preset profile token to integrate it on an automation in HA? Thanks!

**Comment by roleoroleo** [comment]
At the moment it's not possible.

**Comment by amaia81** [comment]
Hi roleoroleo, thanks for the quick answer!. 

I would like to be able to send a command from HA to the camera to move to a determined preset position I made at the Yi home APP. In order to do so I've been attempting it with the ONVIF.PTZ preset service but it requires the PTZ preset profile token as per the integration instruction https://www.home-assistant.io/integrations/onvif/ and I'm not beeing able to know how to extract that token.

Thanks!!

**Comment by roleoroleo** [comment]
Try the number of the profile.

**Comment by amaia81** [comment]
Yes! That solved it! Thanks

**Comment by amaia81** [comment]
Yes! That solved it! Thanks
