### ISSUE TITLE
Other camera support

### ISSUE THREAD

**Issue by cjgarciao** [roleoroleo/yi-hack-MStar#223]
Hello,
I have a camera with the MStar 313E chipset. U-boot looks for the files 'sys_h305r' and 'home_h305r'. If I use the 'h201c' files and simply rename them, is it possible that it works or almost certainly not?
Thank you,
Carlos.

**Comment by roleoroleo** [comment]
Probably you will brick your cam.

**Comment by cjgarciao** [comment]
But I'll be able to restore the copy of the original firmware, right?
Then, should I compile the new firmware, adding the 'h305r' camera? I guess we'll have to change more things.

Thank you,
Carlos.

**Comment by roleoroleo** [comment]
If u-boot looks for sys and home partitions, you will be able to restore your cam.
You have to extract a backup copy.

If the fw is very similar, you can compile a new version.
But it must be "very similar".
There are a lot of cams based on the same platform where the porting is complicated:
- different size of flash
- different type of partition (squashfs, jffs2, etc...)
- different framebuffer file

You should start by dumping the flash and extracting a bootlog.

**Comment by cjgarciao** [comment]
I think the firmware of my camera is quite similar. The size of flash is 16 Mbytes. In the next link are the bootlog and home and sys partitions (they are jffs2).
https://drive.google.com/drive/folders/16D7-u7PMXaJ4su0IgCVXoXzh6UhJia4s?usp=sharing

Thanks.
Carlos.

**Comment by roleoroleo** [comment]
Ok, I downloaded them.
I will compare with the other firmwares.

**Comment by roleoroleo** [comment]
Do you want to try this hack?
https://drive.google.com/file/d/1BrVfDqoGYDVmvzQBJ8ASALS4Stqkqcer/view?usp=sharing

**Comment by cjgarciao** [comment]
Hello,
It seems to work properly. Then later I will test it well. The camera registers in the cloud and works (and can be deactivated). The web interface works correctly, it seems that the PTZ works too.
The serial console has no shell.
Did you have to make many changes?.
Thank you very much.

**Comment by roleoroleo** [comment]
At the moment I only added the cam model into the list of supported cams.
And I removed a scripts that rename japanese audio files because in your version they don't exist.

**Comment by roleoroleo** [comment]
Please, test it and give me a feedback.
Particularly the rtsp stream.

What the serial prefix? bfus, 9fus, ... ?

**Comment by cjgarciao** [comment]
RTSP in high res works (with a 2-4 seconds of delay). In low res doesn't work. The snapshot works in low res, but not in high res.
The camera is a ieGeek IE80, and the serial (in the web interface) starts by TNPXGAB and finish by BMYVS.

**Comment by meriororen** [comment]
Hi @roleoroleo , sorry @cjgarciao I hijack your thread. I have probably similar camera with you, u-boot looking for sys_h305r and home_h305r. I would like to try the hack too, but to be safe I want to backup the stock firmware, can anyone point me where I should read how to dump the firmware on this device? U-boot boot can't be interrupted but I have a linux shell prompt.

**Comment by roleoroleo** [comment]
If you have a linux shell, simply dump the mtd partitions with dd.

```
cat /proc/mtd > /tmp/sd/backup/mtd.txt

dd if=/dev/mtdblock0 of=/tmp/sd/backup/mtdblock0.bin
dd if=/dev/mtdblock1 of=/tmp/sd/backup/mtdblock1.bin
dd if=/dev/mtdblock2 of=/tmp/sd/backup/mtdblock2.bin
...
```
