### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by Dmitrory** [roleoroleo/yi-hack-MStar#225]
Hi, please don't hit. It might be worth adding uploading videos to Google Drive? It would be very convenient. This was implemented as an add-on for similar cameras, but it would be cool to have it by default.

**Comment by roleoroleo** [comment]
See here:
https://github.com/roleoroleo/yi-hack-MStar/issues/77

The free space on flash is not enough to add all needed programs and libraries.
I can't add it to the base firmware.

**Comment by roleoroleo** [comment]
New repo:
https://github.com/roleoroleo/yi-hack-MStar.gdrive

**Comment by Dmitrory** [comment]
Thanks, great job, everything works well.
