### ISSUE TITLE
How to check what chipset camera has?

### ISSUE THREAD

**Issue by croogie** [roleoroleo/yi-hack-MStar#234]
I'm planning to buy camera and hack it. Is that a way I can distinguish chipset type not having camera in my hands? Or what information I need from owner/store to figure it out by myself?

**Comment by roleoroleo** [comment]
Sorry but it's not possible to know the chipset before buy the cam.
You can check it reading the boot log or opening it.

**Comment by croogie** [comment]
ok, thanks. How I can do that having device? Is there any tutorial for noobs? I'm on MacOS

**Comment by roleoroleo** [comment]
Check the fw version from the app.

**Comment by croogie** [comment]
`8.2.0.0A_201912270941`

**Comment by roleoroleo** [comment]
Probably is Allwinner.
https://github.com/roleoroleo/yi-hack-Allwinner
