### ISSUE TITLE
yi dome 1080 bdfu

### ISSUE THREAD

**Issue by guyyar89** [roleoroleo/yi-hack-MStar#237]
hey,

at 1 of week i need to do downgrade version and after upgrade version beacuse i cant use with the cloud camera,
i need to do this beacuse i get error:
-3030 connection and i dont have problem with network and free space on sd card.

how to fix it?

**Comment by roleoroleo** [comment]
What's model and what's base fw?

**Comment by guyyar89** [comment]
> What's model and what's base fw?

base version is:
4.6.0.0A_201908271549

model is:
h201c

Firmware Version is:
0.3.5

**Comment by roleoroleo** [comment]
Please, explain me better the problem.

**Comment by guyyar89** [comment]
When i want to use with application i get error -3030 error conection

**Comment by roleoroleo** [comment]
Is "Disable cloud" switched off?

**Comment by guyyar89** [comment]
> Is "Disable cloud" switched off?

yes Disable Cloud is off

**Comment by roleoroleo** [comment]
Login with ssh and check if you have an internet connection.
