### ISSUE TITLE
Is any way for making a timelapse?

### ISSUE THREAD

**Issue by knut1er** [roleoroleo/yi-hack-MStar#239]
Is it interesting to make a timelapse. I believe it is possible on Yi Cloud.
Many thanks @roleoroleo  for your work!

**Comment by roleoroleo** [comment]
I think we need ffmpeg to create mp4 files.
It's too big to embed it in the fw.

**Comment by knut1er** [comment]
I should schedule shots & transfers with SSH?

**Comment by roleoroleo** [comment]
Yes, you could schedule shots with crond or externally calling the snapshot web service.

**Comment by knut1er** [comment]
I did not see the web service feature. That’s great!
Thank you

**Comment by Dmario-dev** [comment]
Also looking forward for this feature.
roleoroleo can you provide instruction how to save image to sd card with crond?
When I try to run snapshot.sh from SSH it only saves small white square.

**Comment by roleoroleo** [comment]
See the wki.

**Comment by Dmario-dev** [comment]
@roleoroleo sorry but there is no description of snapshot.sh file.
When I try:
`/home/yi-hack/www/cgi-bin # ./snapshot.sh high >> ../pages/1.jpeg`
The picture is only small white square. Can you please help with this?

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-MStar/wiki/Web-services-description#snapshot
