### ISSUE TITLE
No RTSP tab in web page configuration

### ISSUE THREAD

**Issue by arnaudboub** [roleoroleo/yi-hack-MStar#242]
Hi, i have not the RTSP tab in my web page config
![Capture](https://user-images.githubusercontent.com/10142231/94304103-3abae100-ff6f-11ea-8c56-50f88149ba0d.PNG)
have you an idea
with different firmware, does not work
with diferent SDcard, does not work
?

**Comment by bonuzzz** [comment]
Firmware doesn't have RTSP tab

**Comment by arnaudboub** [comment]
Hi thx
So how to know hash for license ?

Regards

**Comment by roleoroleo** [comment]
No license is needed for this firmware.

**Comment by arnaudboub** [comment]
OK. Excuse me so how to send to drive or a cloud without 6 or 10 seconds like yicloud ? 
Thank you
