### ISSUE TITLE
Cant seek/rewind video on Events page

### ISSUE THREAD

**Issue by maximser** [roleoroleo/yi-hack-MStar#246]
When you play some recorded 1m video on "Motion Events"->"Events" you cant seek/rewind in video player.
Its behaviour reproduces on latest Chrome. On Safari(macos and ios) it want not play at all.
I did some investigation, so: 
to seek/rewind ability would be available, the server had to send some extra Headers "Range" header with a 206 "Partial Content" response . 
At this project uses busyboxs httpd, there is a config `FEATURE_HTTPD_RANGES` (https://github.com/mirror/busybox/blob/a949399d178f7b052ada2099c62621736eafce44/networking/httpd.c#L105-L112) , here is description
```
//config:	Makes httpd emit "Accept-Ranges: bytes" header and understand
//config:	"Range: bytes=NNN-[MMM]" header. Allows for resuming interrupted
//config:	downloads, seeking in multimedia players etc. 
```

So i think that enabling this feature would resolve the problem
here line that needs to be changed https://github.com/roleoroleo/yi-hack-MStar/blob/5badaf57fecde247ddc07143008580101e974aa0/src/busybox/.config#L842

**Comment by roleoroleo** [comment]
You are right.
I enabled this feature in the Allwinner project after this PR https://github.com/roleoroleo/yi-hack-Allwinner/pull/108.
But I forgot to enable in the MStar project.
I will fix it.
