### ISSUE TITLE
Support of YI Dome 1080p

### ISSUE THREAD

**Issue by RestOp** [roleoroleo/yi-hack-MStar#250]
Hello, roleoroleo

Thanks one more time for perfect job!
Would like to know if one of this cams are supported:

old one:
https://www.amazon.es/YI-Vigilancia-nocturna-movimiento-giratorio/dp/B01MR82BSA
![image](https://user-images.githubusercontent.com/46259141/95025653-a72e9200-068b-11eb-8d66-0ff6268d1521.png)

new one:
https://www.amazon.es/YI-Vigilancia-Inalámbrica-Movimiento-Compatible/dp/B07QZRJ98M
![image](https://user-images.githubusercontent.com/46259141/95025656-adbd0980-068b-11eb-9145-a0d6a10470b4.png)

or maybe Xioami
https://www.amazon.es/Camara-Domo-XIAOMI-MIJIA-Smart/dp/B07P12T1G3
![image](https://user-images.githubusercontent.com/46259141/95025722-215f1680-068c-11eb-9c37-6a3a0220c095.png)

probaply you need to see part number and firmware version...

Also in description of features i found PTZ conrol over onvif. Do not you know - if i can control PTZ in Homeassistant?

Thanks a lot!

**Comment by roleoroleo** [comment]
It's not possible to know if it's supported without model details.
Part number and fw version for example.

I think ptz via onvif is supported by last ha.

**Comment by RestOp** [comment]
Thanks, will try to buy!
But normaly PTZ supported with onvif apps?

**Comment by roleoroleo** [comment]
I have only yi home cams. So I don't use ptz with yi.
But I'm using the same onvif server in the sonoff project.
And it works correctly with odm, onvifer and other programs.
So, yes, it's supported.

**Comment by RestOp** [comment]
I have got this one
https://www.amazon.es/YI-Vigilancia-nocturna-movimiento-giratorio/dp/B01MR82BSA
Seems that it is supported, FW 4.6.0
I would like to make a backup of originl FW. Can i make it also as Allwinner method https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Dump-your-backup-firmware-(SD-card) ?
Or i will not be able to return to original FW if i will flash with hack?

Thanks a lot!

**Comment by roleoroleo** [comment]
I didn't find an SD card method with MStar.
Only with a serial connection.
