### ISSUE TITLE
sftp upload 

### ISSUE THREAD

**Issue by bepece1** [roleoroleo/yi-hack-MStar#251]
Hi, is it possible sftp upload ???

**Comment by roleoroleo** [comment]
No, but scp is possible.

**Comment by Chekedaudau** [comment]
Dear roleoroleo, first thank you for your awesome work! Could you please explain how to configure scp for the yicam and is the connection secure? I don't want to upload the images/videos to a server on the internet without a secure connection. Is there any idea to implement an sftp upload? Greetings Thomas

**Comment by roleoroleo** [comment]
At the moment it is not in the plan.
But scp command works.
So you could try to edit ftppush.sh and move ftp to scp.

**Comment by LeidenSpain** [comment]
Hi,

Sorry to reopen the topic, it was just to know if it was still not planned to include support for sftp.
I have a sftp server at home for everything, and it would be very convenient for me to use it without having to create an ftp server.

I have looked at what you say about scp, but I am not sure how to use it

**Comment by roleoroleo** [comment]
sftp is not supported at the moment.
You could try to use scp instead. Probably your sftp server supports also scp protocol.
This is a guide:
https://linuxize.com/post/how-to-use-scp-command-to-securely-transfer-files/

**Comment by LeidenSpain** [comment]
thanks for the reply

yesterday I was looking at that website (I did not know the scp or what it was), but what I understood was all through the command line. And I don't know how to use command line with the camera

I want to be able to upload a copy of the videos to my sftp when something is detected, to have a backup

Regards
