### ISSUE TITLE
[feature request] overlay/watermark date/time on video

### ISSUE THREAD

**Issue by cybersheep** [roleoroleo/yi-hack-MStar#252]
Hi All, I've been using this firmware for a while on my Yi Camera, and it performs well. I just wondered does anyone know if it's possible to easily add a feature to allow the RTSP feed to be overlayed/watermarked with current local date/time from the device? Cheers, Rich.

**Comment by roleoroleo** [comment]
It's not possible, sorry.

https://github.com/roleoroleo/yi-hack-MStar/issues/241

**Comment by cybersheep** [comment]
ok thanks for letting me know. And sorry, i hadn't seen issue 241 as when I checked earlier - i realise now that when I scanned existing issues, i'd only looked at open ones, not closed ones.
