### ISSUE TITLE
No web access

### ISSUE THREAD

**Issue by robertogargon** [roleoroleo/yi-hack-MStar#254]
Hello, I have a yi home 1800 9FUS, I have installed the firmware but I can only access the camera through the application.

No access or by web, rstp, etc ... Why can it be?

a greeting

**Comment by bonuzzz** [comment]
@robertogargon for example modded firmware has not been flashed

**Comment by robertogargon** [comment]
No, I know, the blinking game does it and I restart the camera and it does it normal. I put an older firmware and it returns to do the blinking game

**Comment by roleoroleo** [comment]
What's the original firmware version?

**Comment by robertogargon** [comment]
It's 192.168.1.150  but now it's working without doing anything. I observe it and comment
