### ISSUE TITLE
FTP upload with the directories?

### ISSUE THREAD

**Issue by hetzbh** [roleoroleo/yi-hack-MStar#255]
Hi,

The FTP Upload option is really great for archival purposes.
However, it's copying the files, and without the directory itself (which has the date and time when the video was recorder) the MP4 are useless to find what recorded when.

Is there any way to modify the upload to copy the directories and the files, not just the files? 

Thanks

**Comment by roleoroleo** [comment]
See this commit:
https://github.com/roleoroleo/yi-hack-MStar/commit/e941ad06e77cc3a57da772177ae7f2cb25927785

**Comment by hetzbh** [comment]
So I guess it will be with the next version?

**Comment by roleoroleo** [comment]
Yes. Next version.

**Comment by radokristof** [comment]
@roleoroleo the FTP upload seems to work nice even with DIR_TREE and custom path.
However the folders on the camera (or at least in the web interface) are not deleted, only the containing files. Would it be possible to clean up the folders when all files have been uploaded in a folder?

**Comment by roleoroleo** [comment]
This should already be the case.

**Comment by radokristof** [comment]
I just enabled it now, maybe old directories are not cleaned automatically. I will delete them and see if newly created directories disappear or not.

**Comment by radokristof** [comment]
@roleoroleo well, for me it won't delete the folders...

**Comment by roleoroleo** [comment]
I will check it.

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-MStar/commit/317c96879471d9adf09f023424d2127b76fccdc6

**Comment by radokristof** [comment]
Thank you!

**Comment by roleoroleo** [comment]
Released in 0.3.9.
