### ISSUE TITLE
Camera "hangs"

### ISSUE THREAD

**Issue by bonuzzz** [roleoroleo/yi-hack-MStar#256]
two cameras "hangs" after some time. Checked microsd and seems it lost wifi connection, but records videos to sd. In log it seems something wrong with time. Probably it causes connection lost. real local time when i turned off camera was 21.50
https://drive.google.com/file/d/18I0wCAvhEBzlbcM4BaQoAElDTaBEAIfX/view?usp=sharing
fw is 0.3.6 y203c
another three cameras are working with the same settings.

**Comment by roleoroleo** [comment]
Maybe a problem with timezone?
Try to disable ntpd.

**Comment by bonuzzz** [comment]
@roleo already done. it is the main variant. i created this issue if maybe someone else has the same issue
