### ISSUE TITLE
[question] self build reboots

### ISSUE THREAD

**Issue by bonuzzz** [roleoroleo/yi-hack-MStar#258]
when i compiled fw myself, camera reboots after 30 sec -1 minute from start. i don't see anything strange in log, not kernel panic, fatal error etc. what process or error can cause reboot and in what conditions?

**Comment by roleoroleo** [comment]
In my code, only wd_rtsp.sh when rmm is not running.
In general, linux os when there is a low memory condition or a kernel panic (as you mentioned).
In the code written by yi I don't know.
