### ISSUE TITLE
Onvif on hikvision

### ISSUE THREAD

**Issue by guyguy1989** [roleoroleo/yi-hack-MStar#259]
I try to add camera on hikvision nvr but the chanel is 0 and on nvr its start 1-16
![image](https://user-images.githubusercontent.com/72106500/96329520-6012aa80-1056-11eb-8789-d1a6098cd29f.jpeg)

The rstp work good but i want to add camera onvif beacuse i want it recorder on my nvr

Thanks
Guy

**Comment by roleoroleo** [comment]
It shouldn't matter the channel number.
ch0 and ch1 are only a text string.
Set channel 1 and check if it uses the first profile.

The only difference between onvif and rtsp is the ptz (if the cam is a dome).
When a client want to read the stream with onvif, onvif uses rtsp.
So, if you want to record the stream of your camera you can use rtsp directly or via onvif, it's the same.

**Comment by guyguy1989** [comment]
I can see the camera via rtsp but I want the camera to record on the hikvision recording device and not on the memory card that is inside the camera how can this be done?

**Comment by roleoroleo** [comment]
Add the camera as rtsp.

**Comment by guyguy1989** [comment]
I add but i can view on hikvision record

**Comment by guyguy1989** [comment]
???

**Comment by roleoroleo** [comment]
If rtsp works with vlc it must work with your dvr.

**Comment by guyguy1989** [comment]
I can view record on nvr?

**Comment by myromeo** [comment]
I’ve had some problems with my cameras on annke (hikvision clone) NVR and they seem to have been resolved by changing the transfer protocol to UDP. Maybe worth a try.

**Comment by roleoroleo** [comment]
I tested yesterday the last version with an Hikvision dvr and it works.
I close this issue.

**Comment by guyguy1989** [comment]
Hey again now its work for me, but why on playback its show me always time and not when motion detection?
