### ISSUE TITLE
Turn ON/OFF

### ISSUE THREAD

**Issue by rul3zz** [roleoroleo/yi-hack-MStar#260]
Hello and tnx for this amazing project.
I'm using the camera with Home Assistant, i use without problems PTZ with some rest commands found here.
I wish I could turn off/on the camera via Homa Assistant, can u help me?

Thanks

**Comment by hetzbh** [comment]
This project does not support Home assistant. You'll need to contact Yi support for that.

**Comment by bonuzzz** [comment]
@hetzbh everything is possible
@rul3zz check this link and use with shell_command in ha (with curl)
https://github.com/roleoroleo/yi-hack-MStar/wiki/Web-services-description

**Comment by hetzbh** [comment]
Oh, you're right, i apologize.

**Comment by rul3zz** [comment]
> @rul3zz check this link and use with shell_command in ha (with curl)
> https://github.com/roleoroleo/yi-hack-MStar/wiki/Web-services-description

that's exactly what i was looking for .. thank you very much!!

**Comment by rul3zz** [comment]
> @rul3zz check this link and use with shell_command in ha (with curl)
> https://github.com/roleoroleo/yi-hack-MStar/wiki/Web-services-description

that's exactly what i was looking for .. thank you very much!!

**Comment by rul3zz** [comment]
> @rul3zz check this link and use with shell_command in ha (with curl)
> https://github.com/roleoroleo/yi-hack-MStar/wiki/Web-services-description

that's exactly what i was looking for .. thank you very much!!
