### ISSUE TITLE
Backup video with rsync

### ISSUE THREAD

**Issue by hetzbh** [roleoroleo/yi-hack-MStar#261]
Hi

I've created a page with instructions how to use rsync to backup all/part of the videos in the camera, where to get rsync etc.

The page is located [**here**](https://github.com/hetzbh/yi-cams-backup), with credirs to this project authors.

@roleoroleo -- Could you add a link to this page in your README.md file please?

**Comment by bonuzzz** [comment]
@hetzbh you could run rsync in remote machine without copying binary to camera and it is preferable to run rsync on more powerful machine

**Comment by hetzbh** [comment]
You can't, it fails immediately because it's looking for rsync binaries in both ways.

**Comment by roleoroleo** [comment]
I had already compiled rsync, if you need it.
[rsync.gz](https://github.com/roleoroleo/yi-hack-MStar/files/5397774/rsync.gz)

**Comment by roleoroleo** [comment]
Link added to README.
