### ISSUE TITLE
Not flashing

### ISSUE THREAD

**Issue by procrastinate007** [roleoroleo/yi-hack-MStar#263]
Hi, 

I have the Yi Home Camera 3 and I've tried flashing the bios by downloading the files onto a 16GB fat32 microSD card, but to no avail.... should I exchange the cams for the 1080p home version? Is the home 3 not supported? How can I make this work?

Thank you very much for any input!
Appreciated.

**Comment by roleoroleo** [comment]
Is your cam in the list of supported cameras?

**Comment by procrastinate007** [comment]
I’d say so because it starts with 9FUS..

**Comment by roleoroleo** [comment]
You need fw version.

**Comment by procrastinate007** [comment]
The app says that my current fw version is 8.3.0.0A_201912271707 --- does that mean it isn't compatible? 

Not quite sure how it works... I'll take any recommendations!

**Comment by roleoroleo** [comment]
Try this:
https://github.com/roleoroleo/yi-hack-Allwinner/

**Comment by procrastinate007** [comment]
I COULD KISS YOU!!! LOL THANK YOU!!!
Worked like a Charm , thumbs up all the way bro :D hahaha

(so happy rn)
