### ISSUE TITLE
 PLEASE HELP !! Will these cameras be ok YYS.2016?

### ISSUE THREAD

**Issue by djmalin** [roleoroleo/yi-hack-MStar#264]
hello @roleoroleo, I only have a picture from the box and I would like to buy them, only if it will be possible to install software for them?

- Model. YYS.2016

- SN: BY203CEUW99016913

- DATE: 2019.09

- FCC ID: 2AFIB-YYS2016

- IC: 20436-YYS2016

[https://imgur.com/a/OGmLpWr](https://imgur.com/a/OGmLpWr)

**Comment by hetzbh** [comment]
From looking at the specs, this is an old camera. If you didn't buy it yet, don't buy it.

The cameras that are supported appears in the main page - you can see the list [here](https://github.com/roleoroleo/yi-hack-MStar#supported-cameras). The only way to know for sure if it's supported, is to check the first 4 letters from the camera serial in the sticker (below the camera).
