### ISSUE TITLE
Yi 1080p Home BFUS no flashed 

### ISSUE THREAD

**Issue by mianrelie** [roleoroleo/yi-hack-MStar#266]
Hi!

I tried to flash Yi 1080p Home BFUS...and not flash.

Yi 1080p Home BFUS
Firmware 8.2.0.0A_202007211802

No work for this firm?

Thanks

**Comment by bonuzzz** [comment]
proper firmware for your camera is here: https://github.com/roleoroleo/yi-hack-Allwinner
