### ISSUE TITLE
YI Home Cam 3 (Y25) pairing problem

### ISSUE THREAD

**Issue by mcgnai** [roleoroleo/yi-hack-MStar#267]
Caio a tutti, ho questa cam che ha sempre funzionato fino alla ver y25_0.3.4. Ho provato ad aggiornare all 0.3.6.0 e ora la cam non viene più riconosciuta dall'App YI home. succede questo, apro l'app, aggiungo la cam, imposto ssid e passw del router di casa, gli faccio leggere il qrcode alla cam che lo riconosce e mi dice che si connette alla wi-fi. Poi però quando deve ultimare l'ultimo passaggio e aggiungere la cam in elenco nell'app, si blocca e va in time-out. Poi però la cam se la connetto tramite il browser specificando l'ip, riesco a visualizzare il menu di YI-HACK-MStar ma se la spengo e poi la riaccendo, ricomincia la procedure di pairing. Se provo a flashare un nuovo firmware Mstar, non funziona perchè la cam deve prima fare il paiiring con l'app. Come posso risolvere? Grazie per l'aiuto

**Comment by roleoroleo** [comment]
Check if "Disable cloud" is disabled and try again.
