### ISSUE TITLE
Motion detection image event

### ISSUE THREAD

**Issue by SebLz** [roleoroleo/yi-hack-MStar#270]
Hello,
First of all, I'd like to thanks you for the amazing work done with this firmware.
I'm a happy user of yi-hack-mstar 0.3.7 on 2 yi dome 1080p cameras (BFUSY).
I've recently tried to configure the cameras with homeassistant following the wiki:
https://github.com/roleoroleo/yi-hack-MStar/wiki/Home-Assistant-integration

Everything seems to work fine except for the motion_detection_image event. It's like this event is never fired although all other topics are well present and working. Could this be a bug ? Here are my config files: https://1drv.ms/u/s!AsjIE9TOb08FvDgSAZwGY5HiTLIV?e=LC9fp1

**Comment by roleoroleo** [comment]
What do you use to test the message?

**Comment by SebLz** [comment]
I use MQTT Explorer as well as the lovelace UI and none of them show the motion_detection_image topic

**Comment by roleoroleo** [comment]
Sorry.
I didn't commit the update of the submodule.
I need to release a new version.

**Comment by SebLz** [comment]
Thanks for the quick feedback! I'll test again and report the result whenever the new release is out.

**Comment by roleoroleo** [comment]
If you want to overwrite the binary...
[mqttv4.gz](https://github.com/roleoroleo/yi-hack-MStar/files/5471663/mqttv4.gz)

**Comment by SebLz** [comment]
Just tried it (renamed old one to .old, extracted the new one in "/home/yi-hack/bin" and rebooted) but with this new version topic "status" stays "offline" and I also have no motion_detection_image topic

**Comment by roleoroleo** [comment]
I tested it overwriting the binary.
Status and image are working.
Try to run it manually anch check if there are errors, maybe the configuration is not aligned.

**Comment by SebLz** [comment]
Indeed, my bad I forgot to "chmod +x" the new binary ... it's now working here too :)!
