### ISSUE TITLE
No timestamp burned into recorded video

### ISSUE THREAD

**Issue by denven** [roleoroleo/yi-hack-MStar#276]
- Model: Yi Dome 1080p BFUSY 1EF2C 
- Firmware: V201908271549

I am a little surprised that a surveillance video camera doesn't have a timestamp in their recored videos.

Is this not supported by the product officially or just disabled by this hack?  
Is our project able to  enable or enhance this feature?

Thanks

**Comment by roleoroleo** [comment]
It's not supported.
I added it to the snapshots but I can't add it to the stream.
