### ISSUE TITLE
Kami Yi external cam compatibility

### ISSUE THREAD

**Issue by nicmela** [roleoroleo/yi-hack-MStar#281]
Hey, 
I recently bought a Kami Wire-free outdoor Camera ( https://www.yitechnology.com/kami-wirefree ). Are this firmwares compatible with this cam?

**Comment by roleoroleo** [comment]
What's firmware version?

**Comment by nicmela** [comment]
Not sure if I'm taking it from the right place, searching in Kami Home app I can see in the cam options: 
Actual version: 5.1.0.0A_202004022041

**Comment by roleoroleo** [comment]
At the moment is not supported.
To check if it's possible to support it in the future, I need a dump of the memory. See the wiki.

**Comment by liraneli27** [comment]
Hi,
same question here , only that i bought the kami wire free home security (no sd slot but an mini usb port on the camera)
(https://kamihome.com/wirefree-wk101)

even if the firmwares are compatible - there's a way to update without an SD slot?
when i plug it to my computer nothing happens :|

**Comment by nicmela** [comment]
Okay so... not a disassemble expert here... I managed to open the top lid (hard task not knowing what to do and what can break) and tried to find the 3 uart pads.

![IMG_20201125_203529](https://user-images.githubusercontent.com/74989713/100274512-d7453380-2f5e-11eb-9468-803d5f541a52.jpg)
![IMG_20201125_203551](https://user-images.githubusercontent.com/74989713/100274515-d8766080-2f5e-11eb-831d-7ac69b28c23a.jpg)

Can you help me identify them? Also I will need to buy an adapter, will this work? https://www.amazon.it/Serial-PL2303HX-Adattatore-RS232-download/dp/B07QX66Y95 
![image](https://user-images.githubusercontent.com/74989713/100274822-5c304d00-2f5f-11eb-9846-0e506f0f4655.png)

Thank you!

**Comment by roleoroleo** [comment]
Sorry but from these pictures is not possible to find uart pads.
And it's not possible to check the cpu (Hisilicon, Mstar, Allwineer, etc...).

**Comment by nicmela** [comment]
Aight... it was tricky... but i managed to deasseble it more to checkout the hidden side. Does this helps?
![IMG_20201126_195636](https://user-images.githubusercontent.com/74989713/100385447-f0171d00-3022-11eb-8e52-19c4bfb8b608.jpg)

**Comment by roleoroleo** [comment]
2 news:
1.  Above the chip there are the pads where you can connect the uart adapter: RXD and TXD. GND you can choose the one you want.
2. This cam is based on hisilicon chip, this hack is not compatible.

**Comment by nicmela** [comment]
AIght.. thank you for your time!
I've checked TheCrypt0 project, but seems pretty much dead. Sad :(

**Comment by thoemmes86** [comment]
I would also support and donate a hack for this camera.
Since black week I have two of those cameras which are really nice. 
But like normal for yi, no support for external IOT Systems.

**Comment by nicmela** [comment]
I definitely would also support and donate for this.

**Comment by roleoroleo** [comment]
I can't support it.
The hisilicon platform is completely different.
