### ISSUE TITLE
YRS.3019

### ISSUE THREAD

**Issue by ayasystems** [roleoroleo/yi-hack-MStar#283]
Hi

is YRS.3019 supported? 

Anyone can help me to make a modified firmware?

![IMG_20201126_154029](https://user-images.githubusercontent.com/7864168/100365103-5427ea00-2fff-11eb-8897-9ab97885d2f5.jpg)
![IMG_20201126_154039](https://user-images.githubusercontent.com/7864168/100365105-55591700-2fff-11eb-9544-059cd0d4a37d.jpg)
![IMG_20201126_154026](https://user-images.githubusercontent.com/7864168/100365108-55f1ad80-2fff-11eb-97c4-cc948ad08958.jpg)
![IMG_20201126_154320](https://user-images.githubusercontent.com/7864168/100365109-568a4400-2fff-11eb-9447-0bfdc8517b93.jpg)

Best regards!

**Comment by roleoroleo** [comment]
See allwinner-v2.
r30gb is in beta.

**Comment by ayasystems** [comment]
Thanks!
