### ISSUE TITLE
cardless update

### ISSUE THREAD

**Issue by cheese1** [roleoroleo/yi-hack-MStar#285]
Would be great if one could upgrade the firmware WITHOUT a card inserted to the camera.
the original firmware seems to support that.
https://www2.yitechnology.com/support/answer/id/17/tid/3/qid/3/oid/iamges

**Comment by roleoroleo** [comment]
This type of flash is not supported without a card.
And this is an yi official method.
The bootloader looks for files in sd.

The upgrade you linked it's only a partial update.
