### ISSUE TITLE
PTZ presets not working

### ISSUE THREAD

**Issue by ClaireSoftware** [roleoroleo/yi-hack-MStar#289]
Hello! I have a yi 1080 dome BFUS flashed with the correct firmware. I've been trying to set a PTZ preset. There doesn't seem to be any way to set a preset within the HTTP UI, and onvif viewer doesn't seem to help. Is there any way to set PTZ presets using this device?

**Comment by roleoroleo** [comment]
You can't set preset through the web ui.
You have to use yi app.
