### ISSUE TITLE
Motion detection event list

### ISSUE THREAD

**Issue by jjdiazgarcia** [roleoroleo/yi-hack-MStar#29]
Hello,
I would like to know if it is possible to list motion events in reverse order.
I think it is easier to have recent detections first.
Maybe have an option to order list or, by default, reverse order (first items in the list are recent detections instead of the old ones).
I can create a PR if you agree with the approach of listing events in reverse order

**Comment by roleoroleo** [comment]
Ok, please create a PR.

**Comment by roleoroleo** [comment]
Try version 0.2.2.
