### ISSUE TITLE
FTP Read Only User

### ISSUE THREAD

**Issue by X3fxKupaA6jaHX83Whnn3xcYWnUCYhmjr2e2A8T** [roleoroleo/yi-hack-MStar#290]
Trying to setup a read-only FTP account that only has access to the record folder and no shell.
Works with yi-hack-v4 but not with MStar or Allwinner.
chmod on this folder doesn't seem to work as root in SSH.

```
adduser -h /tmp/sd/record/ -s /dev/null ftp > /dev/null 2>&1
chmod 0744 /tmp/sd/record/
```
**FileZilla:**
Status:	Connection established, waiting for welcome message...
Status:	Insecure server, it does not support FTP over TLS.
Status:	Server does not support non-ASCII characters.
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is your current location
Command:	TYPE I
Response:	200 TYPE is now 8-bit binary
Command:	PASV
Response:	227 Entering Passive Mode (x,x,x,x,65,70)
Command:	LIST
Response:	150 Accepted data connection
Response:	421-Sorry, we were unable to read [.]
Response:	421-Options: -l 
Response:	421-0 matches total
Response:	421 chdir: Permission denied
Error:	Failed to retrieve directory listing
Status:	Connection closed by server

**Comment by roleoroleo** [comment]
/tmp/sd is a fat32 filesystem and it doesn't manage linux permissions.
The only solution is to mount the sd card by changing the dmask and fmask parameters.
But you can't do this operation on the fly (with remount option).
You should umount the sd and mount it again.

```
mount -t vfat -o fmask=0000,dmask=0000 /dev/block/mmcblk0p1 /tmp/sd
```
