### ISSUE TITLE
Force IR Mode ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [roleoroleo/yi-hack-MStar#292]
Hello,

First of all Thanks for the quality of the firmware ;)

Sudden light effects generate a "motion_start" on MQTT, and therefore generate false positive (even in low detection)
As well as switching to IR mode: /

Would it be possible to have an option that forces IR mode?

**Comment by roleoroleo** [comment]
Sorry but I don't have full control of the ir led.
You can only disable ir completely.
But when it's enable, it turns on and off by itself.
