### ISSUE TITLE
Migrated with yi-hack-Allwinner-v2

### ISSUE THREAD

**Issue by mAsHERbtm** [roleoroleo/yi-hack-MStar#293]
Hi, 

How to migrate with yi-hack-Allwinner-v2? I copied the files to SD Card > inserted into camera > restarted > camera not available on http://ip_address:8080

did I do something wrong?

**Comment by roleoroleo** [comment]
You can't.
Mstar, Allwinner and Allwinner-v2 are made for different hw platforms.
You can't move from one to another.
