### ISSUE TITLE
Yi Camera BFUS Firmware version 9.0.19.02_202007141512

### ISSUE THREAD

**Issue by r4zi3lrrr** [roleoroleo/yi-hack-MStar#294]
Hi All,

Newbie here so please be gentle :)

I've purchased a Yi Camera BFUS Firmware version 9.0.09.02_202007141512 from Amazon but really want to get this yi hack on.

I've tried copying over the relevant files to SD card (formatted to FAT 32 with 16gb)  but it doesn't seem to do anything - still can't access camera via web-browser.

Yi app works fine.

Please see attached for my SD card layout.

![image](https://user-images.githubusercontent.com/38400294/102607966-10696180-4121-11eb-9659-15cf865d433d.png)

**Comment by MD-V** [comment]
@r4zi3lrrr,

you will have to extract y20ga_0.2.2.tar aswell. 
There have to be two files on the SD card: one starting with sys_* and one with home_*

Also you should consider to use a more recent version (current version is 0.3.9)

**Comment by roleoroleo** [comment]
Based on the fw version, your cam is not supported.
Try another hack.

**Comment by r4zi3lrrr** [comment]
> Based on the fw version, your cam is not supported.
> Try another hack.

Is there any hack in particular that you can recommend please?

**Comment by r4zi3lrrr** [comment]
> @r4zi3lrrr,
> 
> you will have to extract y20ga_0.2.2.tar aswell.
> There have to be two files on the SD card: one starting with sys_* and one with home_*
> 
> Also you should consider to use a more recent version (current version is 0.3.9)

Thank you will give it a try.

**Comment by r4zi3lrrr** [comment]
If I build my own firmware using SDK using: https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Build-your-own-firmware  would I be able to hack it myself?

**Comment by roleoroleo** [comment]
I don't know, it depends on the model.
But are you sure about the fw version number?

**Comment by r4zi3lrrr** [comment]
Ahh ok.

Camera is a Yi 1080p Home Camera
I got the firmware off the Yi app  - hopefully that's the right place to get it from.

**Comment by roleoroleo** [comment]
Are you sure it isn't 9.0.19.02_202007141512.

**Comment by r4zi3lrrr** [comment]
Apologies amended title now 
Firmware is version 9.0.19.02_202007141512

**Comment by r4zi3lrrr** [comment]
Can we work with this Firmware version 9.0.19.02_202007141512 to action any Yi hack?

The Model of camera is: Yi 1080p Home Camera BFUS?

**Comment by roleoroleo** [comment]
yi-hack-allwinner-v2

**Comment by r4zi3lrrr** [comment]
Thanks mate will try this tomorrow.

**Comment by r4zi3lrrr** [comment]
Hi Guys,

Extracted to SD as per below screenshot, put the SD card into the Yi camera - left it for several minutes but not getting anything else, just a amber light.

Any ideas, please?

![image](https://user-images.githubusercontent.com/38400294/102690287-416a9480-41fc-11eb-8af0-be544dce0111.png)

**Comment by roleoroleo** [comment]
Plwase, move your issue to allwinner-v2 repo.

**Comment by r4zi3lrrr** [comment]
Now worries will do thanks.

**Comment by r4zi3lrrr** [comment]
> Based on the fw version, your cam is not supported.
> Try another hack.



> @r4zi3lrrr,
> 
> you will have to extract y20ga_0.2.2.tar aswell.
> There have to be two files on the SD card: one starting with sys_* and one with home_*
> 
> Also you should consider to use a more recent version (current version is 0.3.9)

Does this apply to the yi-hack-Allwinner-v2 too?
