### ISSUE TITLE
Could not find sys_y203c

### ISSUE THREAD

**Issue by azaz485** [roleoroleo/yi-hack-MStar#299]
Hello :) I have Yi Home 1080p 6FUS,

it is said at **Getting Started** -> **4**. Save both files (for example home_y203c and sys_y203c) on root path of microSD card.

However, I could not find the sys_y203c file.

Can you help me to find it ?

**Comment by roleoroleo** [comment]
Decompress the .tgz file.

**Comment by azaz485** [comment]
Thank you for new response roleoroleo , I have also old issue related with that problem. I am quite new GitHub user, 

thank you again 💯
