### ISSUE TITLE
unable to set timezone

### ISSUE THREAD

**Issue by lvdfrnt** [roleoroleo/yi-hack-MStar#30]
anyone know how to set timezone with this hack? the command below works on hack v4 but unable to get it to "stick" on my 6FUS cameras. I telnet, run command, send reboot command and it does not reboot. Even if i reboot through WEBUI, timezone does not set.

**Comment by sorokin-e** [comment]
Confirm. This way to set TZ doesn't work - https://github.com/TheCrypt0/yi-hack-v4/wiki/Setting-the-Timezone

**Comment by roleoroleo** [comment]
The uclibc compiled by Yi doesn't support timezone.
And I think it isn't a good idea to rebuild all uclibc only for timezones.
But I could verify another way.

**Comment by roleoroleo** [comment]
But what's the purpose to set TZ?
Which is the process you want to speak local time?

**Comment by sorokin-e** [comment]
It's should be useful but not for the processes. Correct TZ helps to fix directory naming in Motion events because currently, it's UTC only. I think TZ also affects using with alternative systems like HA, but I'm not sure )
Thanks in advance.

**Comment by roleoroleo** [comment]
Try 0.2.5.

**Comment by sorokin-e** [comment]
It works. Thanks a lot.
