### ISSUE TITLE
Web Interface can not be reached (was able to reach)

### ISSUE THREAD

**Issue by azaz485** [roleoroleo/yi-hack-MStar#300]
Happy new year. I hope everyone is healthy and enjoy to live!!!! 🥇 

I was able to use Web interface very well yesterday and today :) 

However, I don't know why, web interface
 can not be reached now. 

When I open IP:cam:8080, i only saw this screen, no available settings ()
![image](https://user-images.githubusercontent.com/53823911/103353088-f03e8880-4ab8-11eb-9e34-8bdbf75c9bd5.png)

Moreover, when I click any subsection, it just gives 
![image](https://user-images.githubusercontent.com/53823911/103353123-064c4900-4ab9-11eb-9c97-c20f74259f04.png)

**Comment by roleoroleo** [comment]
Try to downgrade to the previous version and upgrade again.
