### ISSUE TITLE
Yi Dome Guard

### ISSUE THREAD

**Issue by adri94** [roleoroleo/yi-hack-MStar#302]
Is this awesome firmware compatible with the YI dome guard camera ? I can't find which chipset is in it.

Thanks,

**Comment by roleoroleo** [comment]
You need to know the first part of the serial number and the fw revision.

**Comment by adri94** [comment]
Thanks for the reply.
ID is 2AFIB-YRS3019
How can I find SN and FW version ?

**Comment by adri94** [comment]
It worked with the r30gb.
I can't access the server with the name "ip-cam". It works with the IP address though. 

Thanks for your work .
