### ISSUE TITLE
DNS stop working

### ISSUE THREAD

**Issue by floyk** [roleoroleo/yi-hack-MStar#306]
Hello,
I'm using the latest firmware (0.3.9), since one week my camera stop working. After some check, I understand DNS stop working, when I log on SSH and ping www.google.fr, it's write "bad address".

I try to reset the default conf, but it doesn't work. 
Disable cloud is on OFF.

Any idea what I can do?

**Comment by roleoroleo** [comment]
Yes, read this:
https://github.com/roleoroleo/yi-hack-MStar/issues/226
