### ISSUE TITLE
Upgrade Issue BFUS

### ISSUE THREAD

**Issue by cabrauck** [roleoroleo/yi-hack-MStar#310]
Hello. I have some problems writing the firmware via SD card.
I connected the camera to my Wi-Fi using the YI App. Then formatted an 8gb SD with fat32 using diskpart. Both files (y203c) were copied to SD. 
When i insert the SD-Card into the camera nothing happens. Camera behavior is like a a normal startup. 

What i am doing wrong? Any suggestions?
Cheers

Yi 1080p Home BFUS
Stock Firmware: 9.0.19.02_202007141512
Model Suffix | y203c

Tried Fw ver: 0.3.8 and 0.3.9
Tried formatting via: diskpart, Explorer

**Comment by roleoroleo** [comment]
If your firmware is 9.0.19 the cam is not a y203c.
Check here: https://github.com/roleoroleo/yi-hack-Allwinner-v2

**Comment by cabrauck** [comment]
Thanks.
