### ISSUE TITLE
[feature request] Enable turning off sending snapshots

### ISSUE THREAD

**Issue by NeuerUser** [roleoroleo/yi-hack-MStar#311]
It would be great, if the sending of full jpeg images via mqtt could be disabled on user selection. I have no need for this and would prefer to keep the mqtt channel as slim as possible, While most messages are a few bytes, the jpeg images are typically around 500kB.

Maybe just don't send any jpegs if the topic for this is empty?

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/mqttv4/commit/346536f1dcff28517e3fae2e1df625a7cca850cd

**Comment by NeuerUser** [comment]
Great. So, you already implemented it? Will there be a new release for yi-hack, then?

Thanks for your efforts!!!
