### ISSUE TITLE
[Feature request] - WiFi discovery through the Web Gui

### ISSUE THREAD

**Issue by robustini** [roleoroleo/yi-hack-MStar#318]
It would be interesting to be able to WiFi discovery through the Web Gui, in order to associate the cam to a new network without necessarily resetting it or manually acting on the file system.
Or at least the ability to change the connection's SSID and password.

**Comment by roleoroleo** [comment]
I could send you a beta release to test, if you want.

**Comment by robustini** [comment]
> 
> 
> I could send you a beta release to test, if you want.

Sure, thanks!

**Comment by roleoroleo** [comment]
What's your model suffix?

**Comment by robustini** [comment]
BFUS, so h201c.

**Comment by roleoroleo** [comment]
Here it is:
[h201c_0.3.9.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/6083907/h201c_0.3.9.tar.gz)

**Comment by robustini** [comment]
Thanks @roleoroleo!
All work fine except saving the credentials.
At the first error attempt, it always works on the following ones.
After a reboot same thing, first attempt with error.

![immagine](https://user-images.githubusercontent.com/3864712/110020583-0d4a3e80-7d2a-11eb-9fbc-1775f3bd5db0.png)

![immagine](https://user-images.githubusercontent.com/3864712/110020614-176c3d00-7d2a-11eb-9460-1af330dc7b5b.png)

**Comment by roleoroleo** [comment]
I don't understand...
I have never seen this error in all the tests I have done.

**Comment by roleoroleo** [comment]
There is an error server side.
Could you try to run a post action to this page

http://IP:8080/cgi-bin/wifi.sh?action=save

with the following content?
``
{
"WIFI_ESSID":"essid",
"WIFI_PASSWORD":"pwd",
"WIFI_PASSWORD2":"pwd"
}

**Comment by robustini** [comment]
> 
> 
> I don't understand...
> I have never seen this error in all the tests I have done.

I tried again now, always on the first save attempt after a reboot it gives me that problem, on the second and subsequent ones it doesn't.

**Comment by roleoroleo** [comment]
I tried again with my y203c and I have no problems.

**Comment by robustini** [comment]
I repeat, it is a relative problem, so much in reality it saves the settings, what I would not like is that someone else can report it to you in the future. 
I don't think it's my BFUS's fault (i hope).

**Comment by roleoroleo** [comment]
I will release this feature in the next version.
If there is a problem we will see it.
:)

**Comment by robustini** [comment]
@roleoroleo I went back to 0.3.9 because with this firmware and the same saved settings the rtsp doesn't work, don't ask me why.

**Comment by roleoroleo** [comment]
Could you please test this version?
RTSP server should be fixed.
[h201c_0.3.9.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/6095500/h201c_0.3.9.tar.gz)

**Comment by robustini** [comment]
> 
> 
> Could you please test this version?
> RTSP server should be fixed.
> [h201c_0.3.9.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/6095500/h201c_0.3.9.tar.gz)

Sorry, same problem.
I double checked, the configuration is all ok.

**Comment by roleoroleo** [comment]
What's the problem?
It starts and crashes?
It doesnt' start at all?

**Comment by robustini** [comment]
It cannot find the server on port 554.

**Comment by roleoroleo** [comment]
Did you reconfigure the cam after the update?

**Comment by robustini** [comment]
No, I imported the previously saved configuration, but I checked that everything was as before and it is.

**Comment by roleoroleo** [comment]
Ok, I will try again.

**Comment by robustini** [comment]
> 
> 
> Ok, I will try again.

If I can help you I can check if the rtsp server is running correctly after a reboot.
How can I check it from the shell?

**Comment by steef84** [comment]
@roleoroleo is it possible for me to beta test y203c. Got to reconfigure a cam so update is nice to have.

**Comment by robustini** [comment]
No news?

**Comment by roleoroleo** [comment]
[y203c_0.3.9.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/6164421/y203c_0.3.9.tar.gz)
[h201c_0.3.9.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/6164425/h201c_0.3.9.tar.gz)

**Comment by robustini** [comment]
> 
> 
> [y203c_0.3.9.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/6164421/y203c_0.3.9.tar.gz)
> [h201c_0.3.9.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/6164425/h201c_0.3.9.tar.gz)

Perfect, RTSP stream is back!

**Comment by steef84** [comment]
Nice addon to configure wifi via webinterface! Nice possibility to add is function for adding hidden networks also via the webinterface. Now it only scans visible networks.

**Comment by roleoroleo** [comment]
What do you mean?
A text box where enter manually a ssid name?

**Comment by steef84** [comment]
Yes, exactly!
