### ISSUE TITLE
[Feature request] - Delete video directory older than X days

### ISSUE THREAD

**Issue by robustini** [roleoroleo/yi-hack-MStar#321]
I would like to automate the deletion of directories of recorded videos inside /tmp/sd/record not based on the residual percentage of the SD but older than x days.
It would be useful if there was this option in the web gui, alternatively a way to do it in the cron.
I tried this inside the cron but it doesn't work, maybe I'm getting syntax wrong:

find /tmp/sd/record -type f -mtime +7 -print0 | xargs -0 rm; find /tmp/sd/record -depth -type d -print0 | xargs -0 rmdir

Has anyone created a similar automatism in the cron?
Maybe I'm wrong, but in any case I don't find in the web guide the possibility of not recording any video, but leaving the streaming anyway.
It is only possible to always record or do it with motion detect, what if i want to never record?

**Comment by roleoroleo** [comment]
If you set "Disable cloud" you can uncheck "Recording without Cloud".
