### ISSUE TITLE
 Dome Camera U

### ISSUE THREAD

**Issue by ethempekin** [roleoroleo/yi-hack-MStar#324]
I see that Camera X is added as an experimental in the list of supported cameras. Are you working on a hack for Dome Camera U? 
https://kamihome.com/dome-Camera-U/

**Comment by TheTimeWalker** [comment]
It depends on what CPU is used in it as Xiaomi tends to use different kind of CPUs for the same "series". Somebody has to buy one and take that one out and probably make a flash dump.
