### ISSUE TITLE
Reset password for rtsp server and reflashing of firmware

### ISSUE THREAD

**Issue by nupnup-goddamn** [roleoroleo/yi-hack-MStar#326]
Hi, 
I recently set the username and password for rtsp server but apperently i now cant access my rtsp stream. I have reformatted my sdcard to FAT32 and copy the required files to the root folder of the sdcard. 
However, i cant seem to get the firmware of the camera to flash the sdcard. 
I followed the steps from the repo:
1) remove power supply of the camera
2) insert sdcard
3) plug the power supply back in

However, i dont get the yellow flashing light. 

Did i do the reflashing correctly? will reflashing the fimrware help me to reset the password setting of the rtsp as well?

**Comment by roleoroleo** [comment]
When you already flashed a version, you can't reflash it.
Because the system save the md5 sum of the image.
You have to flash a previous version and then upgrade again.

**Comment by nupnup-goddamn** [comment]
Thanks it works! may i also ask how can i improve the framerate of the rtsp streaming? which script can i edit?

**Comment by roleoroleo** [comment]
Sorry, it's not possible to change framerate.

**Comment by nupnup-goddamn** [comment]
I see. Thanks anyway for resolving my re-flashing issue! Cheers
