### ISSUE TITLE
Build P2P Client on Android

### ISSUE THREAD

**Issue by ricardojlrufino** [roleoroleo/yi-hack-MStar#334]
I wanted to develop my own P2P client, to have an application with time-based access control.
Can you help me, what tools can I be using ?!

**Comment by roleoroleo** [comment]
Use C language and the toolchain "MStar MSC3XX SDK.zip".
Copy the binary in your SD and start it from /tmp/sd/yi-hack/startup.sh

**Comment by ricardojlrufino** [comment]
same as:
https://github.com/roleoroleo/yi-hack-Allwinner/issues/264#issuecomment-804913019

**Comment by roleoroleo** [comment]
https://drive.google.com/file/d/1nEPkKyf7Xd8vsDFt1E1HGsxW4zS75d4t/view?usp=drive_link
Let me know when you complete the download.
