### ISSUE TITLE
MJSXJO2HL support

### ISSUE THREAD

**Issue by NikDevx** [roleoroleo/yi-hack-MStar#340]
Hello @roleoroleo 
Is it possible to support this camera ? (1080p with magnetic support) . Thanks

**Comment by roleoroleo** [comment]
I don't know.
What chip is it? 
What fw version?

**Comment by NikDevx** [comment]
> I don't know.
> What chip is it?
> What fw version?

@roleoroleo 
Chipsize 16 Mbytes, Blocksize 64KiB
chip is hi3518ev300
wifi chip is Marvell 88W8977
fw version - 4.0.9_0112
model - isa.camera.hlc6 (MJSXJ02HL/hlc6)

**Comment by roleoroleo** [comment]
This platform is not supported.
Check yi-hack-v4

**Comment by NikDevx** [comment]
> This platform is not supported.
> Check yi-hack-v4

Thanks
