### ISSUE TITLE
wifi ssid not changed after reboot

### ISSUE THREAD

**Issue by divemasterjm** [roleoroleo/yi-hack-MStar#346]
I've tried many times changing ssid from web fronted in many cameras and after reboot always returns to the old ssid.
sometimes is changed after reboot but suddenly goes back again to the old ssid

**Comment by roleoroleo** [comment]
I tested again this feature and it works correctly.
Please, give me more details.

**Comment by divemasterjm** [comment]
Basically it works but after reboot in a minute turns back to the old ssid 

JuanMa

**Comment by roleoroleo** [comment]
Cloud is enabled or disabled?

**Comment by divemasterjm** [comment]
disabled

**Comment by divemasterjm** [comment]
hi, ive tried with cloud enabled and it works, the problem must be when cloud is disabled
regards

**Comment by roleoroleo** [comment]
To understand better due to the double negation.
Cloud disabled = switch enabled?

![immagine](https://user-images.githubusercontent.com/39277388/115991943-551f7080-a5cb-11eb-829a-895cda87b1af.png)

**Comment by divemasterjm** [comment]
Yes, it is.
