### ISSUE TITLE
Bricked on update (9FUS)

### ISSUE THREAD

**Issue by Schany79** [roleoroleo/yi-hack-MStar#348]
Hello,

my 9FUS bricked after update from 0.2.2 to 0.2.5. It doesn´t start anymore.
I´ve tried to flash it again with all kinds of possible files for 9FUS.
The only thing what the camera does is blinking in yellow.

Can you please help me here?

Thanks,
Sascha

**Comment by roleoroleo** [comment]
?!?
Is it a MStar cam?

**Comment by Schany79** [comment]
It´s a Yi-Home-1080 with Serial 9FUS... 
Where can I see if it is a MStar?

**Comment by roleoroleo** [comment]
It depends on the chip used but you can see reading original fw version.
If you are using hack 0.2.2 probably it's not a Mstar.

**Comment by Schany79** [comment]
I think from your Git. For a year or so...
The Cam has the 0.2.2 Firmware and under Maintenance (on the Cam´s Website) I tried to update the cam to 0.2.5
I think my SD Card crashed while the update started. Then I tried it with your newest Version for the 9FUS.

**Comment by Schany79** [comment]
Firmware (Original) is 8.20.0A_202007211802 (I have 4 Cams with the exact same firmware - all the same cams)

**Comment by roleoroleo** [comment]
Your cam requires this hack:
https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by Schany79** [comment]
Oh Man! That´s right! Thank you.... It works!
