### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by hetzbh** [roleoroleo/yi-hack-MStar#350]
Hi,

Is there a way to set the IP to static and set the parameters? it's a bit frustrating to hunt the IP of each camera...

Thanks

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-MStar/issues/208

**Comment by hetzbh** [comment]
While the #208 is a good manual solution, it looks like the app itself does not update the IP, only the parts that you added (web GUI etc) are updated.

**Comment by roleoroleo** [comment]
I don't understand, sorry.

**Comment by SeriousPat** [comment]
> #208

Does not work: https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/347

**Comment by SeriousPat** [comment]
I found out, that the IP Bug i reported has to with my DLAN AP.
Without the DLAN AP, the Cams get everytime the right reserved ip from my router.
but i can test it for you, if you want that

**Comment by roleoroleo** [comment]
Maybe there are 2 dhcp servers on your lan.

> but i can test it for you, if you want that

Yes please, if you have time.
