### ISSUE TITLE
Novice questions: usage with YI Home

### ISSUE THREAD

**Issue by gmourasilva** [roleoroleo/yi-hack-MStar#355]
Hi

I just found this repo and I'm stoked with this hack! I have a Yi 1080p V3 Home (9FUS, sold in Amazon Canada) cam and I am planning in hacking it, but before I do it, hacking means that I'll lose access to the camera via the Yi Home app in iOS?

Sorry, I looked at the README and wiki and I didn't find any info related to this.

Thanks

**Comment by roleoroleo** [comment]
There is a switch in the main page of the hack.
You can switch it on and off and choose if you want to break the connection with the cloud (and with the app) or not.
