### ISSUE TITLE
Video not recording after upgrading to 0.4.1

### ISSUE THREAD

**Issue by jd1900** [roleoroleo/yi-hack-MStar#357]
Last 1st of May I updated to 0.4.1.

Since then, I receive the motion events, but there are no new recording. The last recording is from the moment before the update.

I didn't change anything in the configuration.

I've tried disabling and enabling recording with no luck.

Any idea of how to fix this?

**Comment by jd1900** [comment]
I've just realized that I can't access the official app.

**Comment by roleoroleo** [comment]
If you want to use the app, uncheck the option "Disable cloud".

**Comment by jd1900** [comment]
It is unchecked.

![image](https://user-images.githubusercontent.com/63632981/117142175-b1467980-adaf-11eb-8bd4-373badc54f9c.png)

**Comment by roleoroleo** [comment]
Did you solve the problem?

**Comment by jd1900** [comment]
No. How could I?

**Comment by roleoroleo** [comment]
The cam is configured as in the image above and you can't connect with yi app.
Correct?
Does rtsp work?

**Comment by jd1900** [comment]
Correct.

I can see the image of the video and screenshots, but I can't see new recording or use the app.

**Comment by roleoroleo** [comment]
I have never seen a problem like this.
Try to downgrade to 0.4.0 and check if it works.

**Comment by jd1900** [comment]
Is there a way to do that or reinstall 0.4.1 without having to extract the SD card?

It isn't quite accesible after installing in the cealing.

**Comment by jd1900** [comment]
One weird thing.
I've tried disabling cloud, and the time is wrong:
![image](https://user-images.githubusercontent.com/63632981/117543276-5e252e80-b01c-11eb-9f9c-02eecad0874b.png)

I have NTP enabled, but it doesn't work.

However, when I re-enable the cloud back, it works again:
![image](https://user-images.githubusercontent.com/63632981/117543301-8319a180-b01c-11eb-9cbf-cec255a33e3f.png)

I've tried when disabling the cloud every possible configuration, but still no luck.

**Comment by jd1900** [comment]
One more thing. It stuck in 25% when trying to connect in the official app. When the cloud is disabled it stucks in 5%

**Comment by roleoroleo** [comment]
> 
> 
> Is there a way to do that or reinstall 0.4.1 without having to extract the SD card?
> 
> It isn't quite accesible after installing in the cealing.

Copy the files of the old version in /tmp/sd through ftp.
And restart.

**Comment by roleoroleo** [comment]
Are you sure that the cam is able to connect to internet?
Wifi signal, firewall, etc...

**Comment by jd1900** [comment]
> Are you sure that the cam is able to connect to internet?
> Wifi signal, firewall, etc...

It seems that the problem is **related to the DNS server**.
I can't reach any server at all:
![image](https://user-images.githubusercontent.com/63632981/117551720-bd4c6880-b047-11eb-8293-c9624c16103b.png)

However, the DNS server is well set in /tmp/dns1 and /tmp/resolv.conf

Furthermore, if I created a hosts file and add servers, the manually added servers work.

**Comment by jd1900** [comment]
After downgrading everything works back again, but I've lost all my config.
I luckily backuped it up. 
I have upgraded back again, and restored the configuration.

It seems to work fine back again, at least the DNS.

Thank you!
