### ISSUE TITLE
Toggle "Switch on/off the camera" in web GUI is not working

### ISSUE THREAD

**Issue by Smosia** [roleoroleo/yi-hack-MStar#360]
Looks like toggle "Switch on/off the camera" in web GUI is not working.
When I turn off the camera with that toggle rtsp steam and motion detection process continues.

My camera is: Yi home camera 3 9FUS. 
Software version: 4.2.0

**Comment by roleoroleo** [comment]
I know, the maning of this switch is not clear.
It doesn't switch on/off the stream but it replicates the feature of the switch in the original yi app.

**Comment by Smosia** [comment]
Looks like there is no way to disable video from camera without rebooting. 

Any proposals about it?

**Comment by Smosia** [comment]
Is it possible to add new command to mqtt advertise that would call start_rtsp(), stop_rtsp() from service.sh?
Or there is another way to call these functions from HomeAssistant?

**Comment by roleoroleo** [comment]
https://www.home-assistant.io/integrations/rest_command/

**Comment by Rushmed** [comment]
> I know, the maning of this switch is not clear.
> It doesn't switch on/off the stream but it replicates the feature of the switch in the original yi app.

For me its still not clear what this switch is doing. Could you please explain?

**Comment by roleoroleo** [comment]
It enable disable the communication between the app and the cam.
Stream, audio and detections.
