### ISSUE TITLE
Crontab without asterisks?

### ISSUE THREAD

**Issue by tulkas84** [roleoroleo/yi-hack-MStar#364]
Hi, 
I am triying to set up a cron for reboot every day but the web interface only allows this special chars: \ | ! " $ % & / ( ) ' ? ^ [ ] @ < > , ; . : - _ 

Is a mistake or i am missing something? I want to write "0 1 * * * /sbin/reboot"

Thanks!

**Comment by roleoroleo** [comment]
You are right :)
The asterisk is allowed in the crontab field.
But there is a bug at the moment:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/77#issuecomment-848963138

**Comment by roleoroleo** [comment]
Maybe I fixed it with this commit:
https://github.com/roleoroleo/yi-hack-MStar/commit/c5ba66ba89983ae7a5dab40fd65788772448552e

**Comment by galinowski** [comment]
I manually tested your fix c5ba66b and it worked, thanks!
