### ISSUE TITLE
Issues with my 1080p Dome camera

### ISSUE THREAD

**Issue by twosheds** [roleoroleo/yi-hack-MStar#367]
I've loaded the roleoroleo firmware to my camera , model BFUS, and the installation appeared to go well except that the camera is recording continuously. I wasn't expecting this as my 2 older 1080p Dome cameras ( running the orginal Yi-Hack-V4) don't do this. I've tried various combinations of settings to get it to record when it only detects motion but the changes don't appear to make any difference. I've also tried to FTP & SSH to the camera but neither will connect as they require a root password. Neither the default password ( which I assumed was blank) nor any set via the web interface work. I'm using the same methods as I do on my 2 older cameras. Apart from re-installing the firmware again, is there anything else I can try to get it to work correctly?

**Comment by roleoroleo** [comment]
Default password for ssh is blank, as you already tried.
Are you able to access to the web interface?

Try to clean the cache of your browser or try to reinstall a previous version.
