### ISSUE TITLE
Can i use this hack with my Yi 1080p Dome cam...

### ISSUE THREAD

**Issue by yonigold1** [roleoroleo/yi-hack-MStar#369]
I have a Yi 1080p Dome thats serial number begins with 6FUS, however the firmware on the camera is `1.9.3.0E_###########` does the firmware need to be 4.6.0 (which is listed in on the supported camera table) or is 4.6.0 just the version of the hacked firmware?

**Comment by roleoroleo** [comment]
If your cam has 1.9.3 it's probably a hisilicon model and it's not supported by this hack.
Check yi-hack-v4 or yi-hack-v5

**Comment by yonigold1** [comment]
okay will do thank you!
