### ISSUE TITLE
How to open proxychains settings in GUI?

### ISSUE THREAD

**Issue by areyoufserious** [roleoroleo/yi-hack-MStar#378]
How to open proxychains settings in GUI?
Manual in readme is not actual

**Comment by roleoroleo** [comment]
There is no GUI for proxychains, sorry.
Check this wiki:
https://github.com/roleoroleo/yi-hack-MStar/wiki/Use-proxychains-ng-to-connect-your-app-(thanks-to-@x571)

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-MStar/commit/92899f999f289043476198d517ab8f0645297abb
