### ISSUE TITLE
Crontab does not save the command

### ISSUE THREAD

**Issue by NikDevx** [roleoroleo/yi-hack-MStar#381]
Command saved success
![Снимок экрана 2021-08-30 в 16 52 48](https://user-images.githubusercontent.com/45577540/131350205-615ae678-a322-4050-8457-a6035913e7fb.png)

But after rebooting I see this
![Снимок экрана 2021-08-30 в 16 53 35](https://user-images.githubusercontent.com/45577540/131350282-2478bbe3-4f8a-4a0b-a0c6-e9d014f92202.png)

**Comment by roleoroleo** [comment]
It should work:
https://github.com/roleoroleo/yi-hack-MStar/commit/c5ba66ba89983ae7a5dab40fd65788772448552e
Try 0.4.2.

**Comment by NikDevx** [comment]
> It should work:
> [c5ba66b](https://github.com/roleoroleo/yi-hack-MStar/commit/c5ba66ba89983ae7a5dab40fd65788772448552e)
> Try 0.4.2.

Thanks. That helped!

**Comment by NikDevx** [comment]
Hello
0.4.2 and 0.4.3 not working `speaker.sh`

```
{
"error":"false"
"description":""
}
```

**Comment by roleoroleo** [comment]
Please open a new issue if not related to crontab.
