### ISSUE TITLE
h201c - 0.4.3 no PTZ

### ISSUE THREAD

**Issue by MadTomT** [roleoroleo/yi-hack-MStar#396]
Hi
Just upgraded from 0.4.1 to 0.4.3 and PTZ appears to have stopped working in Oniver and TinyCam Pro.
It does appear to work via the camera web gui.

Have I missed enabling something ? 

Thanks

**Comment by MadTomT** [comment]
Hi,
I've updated the files and that does allow PTZ to work, but everything is so much slower.  It was like this before I changed the files, so I don't think it's that. Web access to the camera works, but is sluggish, access via Oniver & TinyCam times out.

If I downgrade to 0.4.1 then it works again.

**Comment by MadTomT** [comment]
Anyone any ideas on this before I downgrade ? Is 0.4.2 much different to 0.4.1 ? Any issues to be aware of ?
Thanks

**Comment by roleoroleo** [comment]
I will release a new version.

**Comment by MadTomT** [comment]
Ok great

**Comment by roleoroleo** [comment]
Do you want to try this?
[h201c_0.4.3.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/7360805/h201c_0.4.3.tar.gz)

**Comment by MadTomT** [comment]
I've gone back to 0.4.1 and it seems more stable.

**Comment by roleoroleo** [comment]
Did you also check the 0.4.2?
