### ISSUE TITLE
Please add proxychains settings in GUI

### ISSUE THREAD

**Issue by areyoufserious** [roleoroleo/yi-hack-MStar#399]
Adding and testing proxychains servers via ssh takes a lot of time and makes insane
please add it on UI like in other hacks, just a copy solution

**Comment by vin-w** [comment]
i voted for this feature too.
And if possible I hope the backup could be able to restore the proxychains.conf too. This could help if people reset and restore the camera with proxychain on.

**Comment by areyoufserious** [comment]
> i voted for this feature too. And if possible I hope the backup could be able to restore the proxychains.conf too. This could help if people reset and restore the camera with proxychain on.
thanks
where I can vote?

**Comment by roleoroleo** [comment]
It's not hard but I have to find the time.

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-MStar/commit/92899f999f289043476198d517ab8f0645297abb
