### ISSUE TITLE
pairing process not valid but camera works

### ISSUE THREAD

**Issue by busubs** [roleoroleo/yi-hack-MStar#400]
Hello

i have yi-hack 0.4.3. 
my problem:

reset camera -> waiting to connect -> i prepare qr code on my phone -> connecting to wifi -> wifi is connecting -> camera works but on my phone after 2min i have fail :(

ftp camera works, http works, but app no :/ any idea?

**Comment by vin-w** [comment]
You need proxychain for camera to work?

**Comment by roleoroleo** [comment]
What's your serial?
*FUS or *FCN?

**Comment by dontbesoshy** [comment]
> What's your serial?
> *FUS or *FCN?

Fus

**Comment by busubs** [comment]
> What's your serial? *FUS or *FCN?

*FUS

**Comment by busubs** [comment]
> You need proxychain for camera to work?

No

**Comment by roleoroleo** [comment]
Never seen this problem.
Check if cloud process is running.

**Comment by Cyberflow187** [comment]
@roleoroleo  : Does the Cloud process needs to be enabled ?

**Comment by roleoroleo** [comment]
cloud process runs normally when the cam is not hacked OR when you switch off the switch "Disable cloud".
cloud process doesn't start when the cam is hacked AND you switch on the switch "Disable cloud".

To check if it's running, open a shell and run ps command.

**Comment by busubs** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/79911315/141787088-be38f7ae-864f-4561-8da4-8cde25a07877.png)

ps in SSH

**Comment by busubs** [comment]
and now i disabled cloud
![image](https://user-images.githubusercontent.com/79911315/141787637-3665d5bf-bd25-49a3-82a6-b99110d9ca8b.png)

ps in SSH
![image](https://user-images.githubusercontent.com/79911315/141787620-d2952a52-4a71-4f04-b50e-f31762b4fce1.png)

again - after reboot i listen (welcome to yi home camera...)

**Comment by roleoroleo** [comment]
The process is correcly running when switch is off.
I don't know why the cam doesn't complete the pairing process.

You could try to set the wifi credentials with this procedure:
https://github.com/roleoroleo/yi-hack-MStar/wiki/Change-WiFi-credentials-(deprecated-from-0.4.0)

**Comment by busubs** [comment]
[log_no_wifi_dev.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/7545847/log_no_wifi_dev.tar.gz)

The first launch works, but when I switch and turn on the camera it start reset after blue pulse led

**Comment by fearpro13** [comment]
Yi Dome Guard
Model: YRS.3019

Camera does work the same way as described here. It always finishes pairing with audio "pairing timeout" error. After that hack starts to work without any issues. After reboot "pairing" is required to be done again, and done again with error

**Comment by roleoroleo** [comment]
You should try to force the wifi connection using the web interface of the hack.
If it doesn't work, a reset of the cam is needed.
Long press the back button and reconfigure the cam from scratch.

**Comment by fearpro13** [comment]
"Wifi connection force" does not work neither configured before applying hack in config file or through web interface when hack is already done.
Camera resets does not help
Actually i do have 2 cameras of same model, both behaved the same

**Comment by roleoroleo** [comment]
Did you try another wifi ap?

**Comment by fearpro13** [comment]
Yes, but another ap is connected to original ap as a client through wifi. Nothing works.
Is it possible to force ethernet interface instead?
