### ISSUE TITLE
saving the parameters on the advance mqtt page does not work.

### ISSUE THREAD

**Issue by laquiche-secu** [roleoroleo/yi-hack-MStar#402]
Hello,

saving the parameters on the advance mqtt page does not work.

Looking in the browser console, there is an error

Thank you
Roman

![image](https://user-images.githubusercontent.com/64662410/141258950-51fe3744-c168-4353-8c6d-b37a74ddea38.png)

**Comment by roleoroleo** [comment]
Which version?

**Comment by laquiche-secu** [comment]
Firmware Version | 0.4.3
Base Version | 4.6.0.0A_201908271549
 I try many parameters on this page, chrome or firefox, same error

**Comment by roleoroleo** [comment]
No way to repeat your problem.
Firefox or Chrome...
When I save, it completes successfully.
Are you using special chars or special strings inside the text field?
