### ISSUE TITLE
Support for 9CUS

### ISSUE THREAD

**Issue by borodiliz** [roleoroleo/yi-hack-MStar#41]
Hi,

Thanks for your work with this hack!

I've just received two Yi Outdoor Camera 1080p 9CUS Firmware: 3.0.0.0D_201809111054
It's this model supported? If not , I will try to dump logs / rootfs / home

Thanks and regards,
Borja

**Comment by roleoroleo** [comment]
I need a bootlog to know if it's a MStar and if I can support this model.

**Comment by JHenzi** [comment]
Did you ever get the dump, didn't look like it. Just picked this up on sale, I can try v4 or see about providing them if you suggest this over v4.

**Comment by roleoroleo** [comment]
The hardware is different.
If it loads v4, doesn't load mine.
I didn't receive any dump.

**Comment by Dreamoffice** [comment]
Hi 
i also got a Yi Outdoor Camera 1080p 9CUS, is there a chance to get the hack running?

**Comment by UlfgarIlFabbro** [comment]
La 

> 
> 
> Did you ever get the dump, didn't look like it. Just picked this up on sale, I can try v4 or see about providing them if you suggest this over v4.

The v4 version loads and boots quietly but many features are missing such as onvif and ftp upload. Can your version work?

**Comment by roleoroleo** [comment]
If your cam works with v4 it can't work with MStar or Allwinner.
