### ISSUE TITLE
is this cam compatable 

### ISSUE THREAD

**Issue by skeltonmfc** [roleoroleo/yi-hack-MStar#42]
Will this cam work with this hack ?

![CAM](https://user-images.githubusercontent.com/57748067/70220609-c2b0cf80-173e-11ea-9f3c-dbca5e15a368.jpg)

**Comment by roleoroleo** [comment]
I need to analyze the bootlog if you want to know if it's compatible.
See issue https://github.com/roleoroleo/yi-hack-6FUS_4.5.0/issues/10
