### ISSUE TITLE
Add "flush" option?

### ISSUE THREAD

**Issue by hetzbh** [roleoroleo/yi-hack-MStar#420]
Hi,

When using the FTP Upload (and delete files after uploading) - sometime the camera is losing connection to the NAS (not related to the camera) to upload, and due to this connection lost, the card still has the old videos and it's not uploading the old footage to the NAS.

Would you consider adding an option to "flush" all the MP4 content from the SD card (that has not been uploaded) to the NAS? if not, which script should I run in order to force everything to be uploaded?

Thanks

**Comment by roleoroleo** [comment]
Sorry but I don't understand what behavior you would like.
