### ISSUE TITLE
Camera compatiblity

### ISSUE THREAD

**Issue by ThibautBascoulergue** [roleoroleo/yi-hack-MStar#421]
Hello, I have a Xiaomi Camera model : MJSXJ105CM with 4.0.9_0426 firmware. Is it compatible with the hack please ?

Thank's.

**Comment by roleoroleo** [comment]
I don't know.
I need a backup of the flash to know.

**Comment by ThibautBascoulergue** [comment]
Do you have a procedure for making a backup of the firmware so that I can drop it off somewhere?

**Comment by roleoroleo** [comment]
It's a tricky task.
Check the wiki.
