### ISSUE TITLE
Request Extend support ieGeek IE82

### ISSUE THREAD

**Issue by fabiex75** [roleoroleo/yi-hack-MStar#422]
Hi, can you add support for IeGeek IE82, please ? I can't find any information about chipset or other.
Thanks in advance

**Comment by fabiex75** [comment]
..if I may be useful for additional information, let me know.

**Comment by roleoroleo** [comment]
It depends on the platform.
Please, start opening the cam and taking some snapshot of the board.

**Comment by fabiex75** [comment]
Thanks.I post some screenshots. Let me know if i can help in any way.![image](https://user-images.githubusercontent.com/44639348/152638524-d9255f4a-9c5f-49d1-a0d6-6d1f4da09aed.jpeg)
![image](https://user-images.githubusercontent.com/44639348/152638642-3f715f9f-0718-482f-89fc-10eb03110ff2.jpeg)

**Comment by roleoroleo** [comment]
PleasePlease also the other side.

**Comment by fabiex75** [comment]
![image](https://user-images.githubusercontent.com/44639348/152736126-32f82aef-53c8-4b32-a2fb-9766305495ac.jpeg)

**Comment by roleoroleo** [comment]
I can't see the cpu..
Is there another board?

**Comment by idanny76** [comment]
> No...this is the only One.Maybe Photo is not clear or under wifi module ?

Could be inside the upper part where the camera is encased in.

**Comment by fabiex75** [comment]
I don't know how open it more
How can I open it without broken ?

[image](https://user-images.githubusercontent.com/44639348/154422530-df1a77f6-8f0e-47f2-947c-f63a6556ac40.jpeg)
![image](https://user-images.githubusercontent.com/44639348/154422558-c8ab1f37-ee27-43c7-b6ee-2608409674c1.jpeg)

**Comment by idanny76** [comment]
> I don't know how open it more How can I open it without broken ?
> 
> ![image](https://user-images.githubusercontent.com/44639348/154422839-20cb3c24-1ce2-47cc-9df7-88b795f90657.jpeg)
> 
> ![image](https://user-images.githubusercontent.com/44639348/154422888-20dee442-91d2-4aca-9d73-416198e22243.jpeg)

I think it can be separate in half. If there are no visible screws holding those two half together, then they should snap off. You may need to use some force to snap it. There is always a chance it might break, but I think it should come apart..... there is definitely a line showing a separation.  
![154422888-20dee442-91d2-4aca-9d73-416198e22243](https://user-images.githubusercontent.com/85074566/154491626-9de39ae9-3b22-480d-a672-a78153179810.jpeg)

**Comment by fabiex75** [comment]
Sorry guys but at first attemp I ear little crack and I'm stopped. So, I try to flash with ie80 experimental and works. Now I can connect to my ie82 in http on port 8080. Can I have to do some tests for ensure that all is ok ? Thanx as always

**Comment by roleoroleo** [comment]
Do you know the firmware version?
I mean the original one.
