### ISSUE TITLE
Yi Home QY21 & Yi Dome Guard YRS.3521

### ISSUE THREAD

**Issue by a-camacho** [roleoroleo/yi-hack-MStar#423]
Hi guys,

Just received these two cameras and didn't check model number and firmware before.

Do you think there is any way that I can flash the firmware on them ?
Could I provide anyone with the firmware dumped.

Thanks a lot

**Comment by roleoroleo** [comment]
Share the firmware dumped.
I will check the version.

**Comment by adamcodes716** [comment]
I just bought the YRS.3521 but haven't opened it yet.   Is there any update on whether or not the custom firmware will work with this camera?

**Comment by roleoroleo** [comment]
I don't know which model is.
Please, share a backup.

**Comment by adamcodes716** [comment]
> I don't know which model is. Please, share a backup.

Sure, I'd be happy to do that.  Is there a procedure to do this?  I had assumed that we couldn't SSH into it without the custom firmware.

**Comment by roleoroleo** [comment]
Check the wiki.

**Comment by a-camacho** [comment]
> > Check the wiki.
> 
> The wiki in github? It is empty except for a one line message. I did not see anything in the readme that talked about taking a backup. Do you have a link to the documentation that you are referencing?

I think it is here : https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Dump-your-backup-firmware-(SD-card)

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)

**Comment by adamcodes716** [comment]
> https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)

Thank you very much!  Here is the firmware.  Please let me know if I can provide anything else.

https://drive.google.com/file/d/1slPkDypPS1zIdxMTvvfLHEX88xzoer79/view?usp=sharing

**Comment by roleoroleo** [comment]
> > https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)
> 
> Thank you very much! Here is the firmware. Please let me know if I can provide anything else.
> 
> https://drive.google.com/file/d/1slPkDypPS1zIdxMTvvfLHEX88xzoer79/view?usp=sharing

Your cam is a r35gb, already supported.

**Comment by idanny76** [comment]
> > > https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)
> > 
> > 
> > Thank you very much! Here is the firmware. Please let me know if I can provide anything else.
> > https://drive.google.com/file/d/1slPkDypPS1zIdxMTvvfLHEX88xzoer79/view?usp=sharing
> 
> Your cam is a r35gb, already supported. Check allwinner-v2

Thank you very much for your hard work and the time you put into this.

**Comment by Alexselutin** [comment]
> > https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)
> 
> Thank you very much! Here is the firmware. Please let me know if I can provide anything else.
> 
> https://drive.google.com/file/d/1slPkDypPS1zIdxMTvvfLHEX88xzoer79/view?usp=sharing

send mtdblock again, the link doesn't work.
I really need it
