### ISSUE TITLE
YI 1080P home compatibility

### ISSUE THREAD

**Issue by mrgoodcat** [roleoroleo/yi-hack-MStar#426]
Hi , 
i have a YI 1080P home, but can't flash it (nothing happen after insert the SD). 
SN seems to be (i get this from the barcode in the rear)
BFUSY44EHLZO4C200810
Can you help me ?
thanks

**Comment by roleoroleo** [comment]
What is the fw version (in the app)?

**Comment by mrgoodcat** [comment]
Hi, 
thanks for replay. After wrote this i found the FW and other your (?) hack that seems fit better on my situation and i ask the same with more details , like FW 9.0.19.02_202007141512
here the link to the other request
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/372
thanks,
