### ISSUE TITLE
Can't save configuration after upgrading to v0.4.5: "Error while saving" message

### ISSUE THREAD

**Issue by Hall9k** [roleoroleo/yi-hack-MStar#431]
I've just upgraded to v0.4.5 via "Online FW upgrade"

Edit 1: I've been able to load a previously saved config file and settings were restored, but afterward setting changes can't be saved; same message: "Error while saving"

**Comment by roleoroleo** [comment]
You are right.
I don't know why, but jq is broken.
I will release a new version asap.
In the meantime, use this one:
[jq.gz](https://github.com/roleoroleo/yi-hack-MStar/files/8302878/jq.gz)

**Comment by Hall9k** [comment]
Thank you very much roleoroleo. 
Sorry but I don't understand what I have to do with that file,  jq.gz
Should I copy it in a sd card?
Thanks for all your work

**Comment by Madaraxa** [comment]
> Thank you very much roleoroleo. Sorry but I don't understand what I have to do with that file, jq.gz Should I copy it in a sd card? Thanks for all your work

Now a New Version ist out (0.4.6) which should have fixed the issue
