### ISSUE TITLE
/bin/busybox is missing poweroff and halt support

### ISSUE THREAD

**Issue by meskilla** [roleoroleo/yi-hack-MStar#433]
which leads to a poweroff: applet not found message.

Did you strip it for filesize reasons? Reboot works and is listed in busybox 4.6.0 functions.

What is the safest way to shutdown the cam with a mmc vfat partition still mounted and possibly recording? I can't just cut the power cord, as this will lead to vfat corruption. Is there a stop script instead of shutdown jobs that could kill jobs and safely unmount /tmp/sd before I cut the power ?

**Comment by roleoroleo** [comment]
It's stripped by yi.

At the moment there is no way.
You should send reboot command, wait 5 seconds and remove power cord.

**Comment by meskilla** [comment]
is there a shell script to safely unmount /tmp/sd first?

**Comment by roleoroleo** [comment]
No, but I can try to add it.

**Comment by Lin-Admin** [comment]
> 
Thanks. This would be very helpful!

**Comment by roleoroleo** [comment]
For MStar I added it. Next release...
