### ISSUE TITLE
Home Assistant ONVIF reboot command doesn't work

### ISSUE THREAD

**Issue by apmillen** [roleoroleo/yi-hack-MStar#437]
I have integrated the my Yi Dome 1080p camera into Home Assistant using ONVIF and the stream and PTZ all work as expected. However the reboot command does not seem to do anything to the camera.

Am I missing something?
If this isn't a feature the firmware offers, is there another way of rebooting the camera remotely?

Thanks in advance!

**Comment by roleoroleo** [comment]
Reboot via onvif is not currently supported.
I could try to add it but I need time...
At the moment you can use this service:
http://ip:8080/cgi-bin/reboot.sh

**Comment by apmillen** [comment]
Works like a charm. Thank you!

**Comment by roleoroleo** [comment]
Check the last release of the hack.
I added the feature:
https://github.com/roleoroleo/yi-hack-MStar/commit/bcb052bbebbebc701634bf4cb8a3febe45d2e1ec

**Comment by apmillen** [comment]
Ahhh brilliant! I'll give it a go when i get a chance!
