### ISSUE TITLE
cron reboot once a day

### ISSUE THREAD

**Issue by gmourasilva** [roleoroleo/yi-hack-MStar#443]
Hi 

I have a camera that is saving files on an SFTP server. It looks like sometimes files are not copied, which doesn't have to my other camera (another brand). Not sure if it is something with my network or the firmware, but I know that it is fixed by rebooting the camera in the admin panel.

Decided to create a cron job in the web panel to reboot once a day but it doesn't work.

```
0 0 * * * sudo reboot
```

What is the right command to reboot? Tried `reboot` and `sudo reboot` but it didn't work.

Thanks

**Comment by roleoroleo** [comment]
Use
`reboot -f`
but add some sync.

**Comment by gmourasilva** [comment]
Sorry, what do you mean by "but add some sync"? Tried `45 * * * * reboot -f` and it didn't work

**Comment by roleoroleo** [comment]
`45 * * * * sync; sync; sync; reboot -f`

**Comment by gmourasilva** [comment]
That worked like a charm, thank you
