### ISSUE TITLE
Commands in the console to create a login and password RTSP stream 

### ISSUE THREAD

**Issue by NeroWard** [roleoroleo/yi-hack-MStar#456]
Prompt commands in the terminal to manually set the RTSP stream login and password and start a secure RTSP stream

**Comment by roleoroleo** [comment]
Use -u option for the user and -w option for the password.
Please note that the stream is not secure, there is no encryption.

**Comment by roleoroleo** [comment]
Use -u option for the user and -w option for the password.
Please note that the stream is not secure, there is no encryption.
Just authentication.

**Comment by NeroWard** [comment]
An example of a command?

**Comment by roleoroleo** [comment]
What's your model suffix?

**Comment by NeroWard** [comment]
https://github.com/niceboygithub/AqaraCameraHubfw/tree/main/binutils
I have an Aqara G2, but this project uses your work to make RSTP work. Perhaps I need to use the updated rRTSP from your project

**Comment by NeroWard** [comment]
Could you build rRTSP into an executable for me? My Linux knowledge is not enough to do it myself

**Comment by roleoroleo** [comment]
It's not a simple task.
I need the sdk tool to build a source for your platform.
Cross compiler, libc libraries, etc...

**Comment by NeroWard** [comment]
> `rRTSPServer -r both -c h264 -C h264 -a alaw -p 554 -n 0 -u user -w password`

The console says "invalid option".Even if you enter each argument separately

**Comment by roleoroleo** [comment]
Probably he changed the source code or it's a very old version.
