### ISSUE TITLE
Help please - which firmware to use for my camera

### ISSUE THREAD

**Issue by r4zi3lrrr** [roleoroleo/yi-hack-MStar#459]
Hi,

My camera is on firmware version 8.2.0.0A_201912270941 according to the yi app

Camera is a 9FUSY Yi 1080p Camera Home.

Trying to flash it with y203c_0.4.7 but getting no where fast.

When I extract the files using winrar it creates 2 files on the sd card - home_y203c & sys_y203c.

Upon inserting the card the into the sd card of the camera, it just boots up as normal.

Can you please advise?

**Comment by roleoroleo** [comment]
y20ga
https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by r4zi3lrrr** [comment]
Thank you that worked.
