### ISSUE TITLE
Yi Home 1080p BFUS wont flash

### ISSUE THREAD

**Issue by mspace00** [roleoroleo/yi-hack-MStar#46]
I just picked up a few BFUS versions of the YI 1080p Home camera and I cannot get it to flash the y203c firmware. Following the instructions using 512mb card fat 32 with the two files on root. The camera boots normally and does not load new firmware.

Existing camera firmware: 4.5.0.0B_201909041616

Am I missing a step here?

**Comment by roleoroleo** [comment]
Please retry with another sd.

**Comment by mspace00** [comment]
Tried a few and was able to get the firmware update to start, but it never completes. I don't have a 16gb (only bigger and smaller) so I ordered one and will report back. Thanks

**Comment by mspace00** [comment]
New SD card did the trick. Thank you for all the hard work!
