### ISSUE TITLE
The y203c firmware kills my SD cards

### ISSUE THREAD

**Issue by korikori** [roleoroleo/yi-hack-MStar#465]
Hi, I'm running two Home 6FUS cams and they work fine with the y203c firmware, but one of the cams has now made two different SD cards read-only and thus unusable. I believe that this may be due to the increased work temperature, but of course I'm open to other ideas. Anyway, do you have any suggestions on SD cards that work well? The two "dead" ones are both ADATA purple ones, one 32 and one 64 GB. I also wonder if this could be due to their larger-than-suggested size compared to the readme?

Thanks in advance.

**Comment by roleoroleo** [comment]
Unfortunately it can happen that the SD gets damaged.
FAT32 file system is not strong enough against reboots, especially if swap file is enabled.
Probably it's just a software failure: try to format again the sd card.
