### ISSUE TITLE
"http://IP:8080/cgi-bin/preset.sh?num=NUMBER" doesn't work

### ISSUE THREAD

**Issue by jimloki** [roleoroleo/yi-hack-MStar#467]
Hi,

I'm using a Yi Dome Camera X with the latest firmware (yi-hack-MStar 0.4.8). I was previouly on yi-hack-MStar 0.4.4 and everything was OK.

When I use the command http://ip:8080/cgi-bin/preset.sh?num=NUMBER, I have an error message:
`{
"error":"true",
"message":"Invalid action received"
}`

After a little digging, I found out that the right command is http://ip:8080/cgi-bin/preset.sh?action=go_preset&num=NUMBER

**Comment by roleoroleo** [comment]
I fixed the wiki.
Thanks.
