### ISSUE TITLE
Random reboot on Yi Dome Camera X

### ISSUE THREAD

**Issue by jimloki** [roleoroleo/yi-hack-MStar#471]
Everything was OK on version 0.4.4, but starting from 0.4.5 until the latest one (0.4.8) I have random reboots.
I tried to reset to yi-hack default and reconfigure everything but the problem is still there. What can I do to help investigate?

**Comment by roleoroleo** [comment]
I added thumbnails between 0.4.4 and 0.4.5.
Try to disable the option "Snapshot for recorded video".

**Comment by jimloki** [comment]
No reboots for more than 3 days after disabling "Snapshot for recorded video". Thank you

**Comment by jimloki** [comment]
No reboots for more than 3 days after disabling "Snapshot for recorded video". Thank you
