### ISSUE TITLE
ir leds dosent work

### ISSUE THREAD

**Issue by masyanich** [roleoroleo/yi-hack-MStar#476]
y203c
6FCNY
0.4.8

Thank you very much for this mod, I have a problem - I bought this camera at a flea market, but after installing the mod - ir leds (although I hear a click when turning on the camera) doesn’t work for me, the toggle for ir leds is set to on in yi hack web, but nothing happens, unfortunately I don’t know what settings were in native application, maybe it was disabled there or is it a hardware problem, can I somehow turn on the backlight from the operating system? The second question is how to connect the native application after installing the mod, after the "reset"  in yi hack web  wifi settings are dosent droped. Thank you!

**Comment by roleoroleo** [comment]
This switch
![immagine](https://user-images.githubusercontent.com/39277388/208310427-1ce8274c-9753-4a4c-924e-2b790ae18055.png)
should work.
If it doesn't work and the room is dark, probably it's a hardware failure.

To connect the native application, reset the cam using the back button and follow the procedure in the app.
