### ISSUE TITLE
Forget web interface password

### ISSUE THREAD

**Issue by matthieup240** [roleoroleo/yi-hack-MStar#477]
I forgot the password defined few month ago to access the web interface on port 8080.
Is there a solution to modify or reset this password ?

Thanks

**Comment by roleoroleo** [comment]
You could try to enter with putty, the password is different (default blank), and edit manually /home/yi-hack/etc/system.sh

**Comment by maattatoio** [comment]
same issue: I can't log in the web interface but I know that pass is correct and so the username.
how can I log in?
please I'm really a beginner

**Comment by roleoroleo** [comment]
If you are able to login with ssh (putty) you can change the web password editing /home/yi-hack/etc/system.conf
