### ISSUE TITLE
x-content-type-options: nosniff header with cloudflare tunnels

### ISSUE THREAD

**Issue by Klay4** [roleoroleo/yi-hack-MStar#478]
Hi,
I encountered this problem by putting the camera under a zero trust cloudflare tunnel.
When I access the web page everything was black except the sidebar.

<img width="1440" alt="Screenshot 2022-12-29 at 19 19 41" src="https://user-images.githubusercontent.com/39599216/209997670-5df5438a-ce05-4371-a554-587ecdd986ae.png">

## Identification of the problem
After some digging, I found that theoretically tunnel/cloudflared/somewhere in the CF Proxy is adding the x-content-type-options: nosniff header, and those resources do exist but the origin server isn't returning the proper content types.

> Content Type / Media Type (MIME Type) is the identifier for the file format/contents.
The CF Proxy / somewhere is adding the nosniff header, a security feature, to stop the browser from trying to guess the content type of the file (which could be a security risk with user uploaded content and probably other reasons I don't remember/know). The root problem though is your origin server (the camera running yi-hack) isn't properly returning content types for the files.

<img width="512" alt="Screenshot 2022-12-29 at 19 24 37" src="https://user-images.githubusercontent.com/39599216/209997863-9aca4ac9-9dd1-4d6c-9458-f10befbc9e0b.png">
<img width="833" alt="Screenshot 2022-12-29 at 19 31 31" src="https://user-images.githubusercontent.com/39599216/209997899-33a7e24e-9735-4ba9-8504-3054c17cd19c.png">

## WorkAround Fix
Easiest workaround fix for this is probably just to add a transform rule setting the content-type for files ending in .js

In your zone/website, Rules => Transform Rules => Create Transform Rule => Modify Response Header, then something like this:

![image](https://user-images.githubusercontent.com/39599216/209998780-565436a6-fc77-402a-a236-981381ce042f.png)

Thanks to TylerO#3235 for helping me identify and solve the problem.

**Comment by roleoroleo** [comment]
Do you know a solution for this?
Could I change something server side?
