### ISSUE TITLE
ssh/tenet details

### ISSUE THREAD

**Issue by truxntrax** [roleoroleo/yi-hack-MStar#48]
Hi,

Really liking the firmware, but I cannot get the mqtt notion detection to work.  So, have enabled ssh, and was going to check via top, that mqtt is running.  However, what are the login details please for me to check this?

Many thanks

John

**Comment by roleoroleo** [comment]
root with blank password

**Comment by truxntrax** [comment]
Thanks, I can see mqttv4 is running.  However, I am "listening" using mqqt tools in home assistant, and I can't see the camera sending any messages to indicate motion_start/ motion_stop...
I have double check settings: mqtt server, user, password, port etc...  I have enabled and disabled mqtt, but can't "hear" any messages.  Is there anything else I need to set?

Many thanks for quick reply!

John

**Comment by truxntrax** [comment]
Doh!  I had disabled motion detection in the yi app interface.  All seems to be working now. 

Many thanks

John

**Comment by roleoroleo** [comment]
Interesting.
What flag did you disable in the app?

**Comment by truxntrax** [comment]
There is a motion on off toggle switch option in the yi app. I had set this to off, as am using zoneminder for the motion detection.

**Comment by roleoroleo** [comment]
Could you make a screenshot, please?

**Comment by truxntrax** [comment]
Sure.
![Screenshot_2019-12-13-18-20-19-899_com ants360 yicamera international](https://user-images.githubusercontent.com/21132925/70822485-926bcf80-1dd5-11ea-9ceb-b78abdf2ea55.jpg)
