### ISSUE TITLE
Yi Dome X - Using YI app to view recordings are not functioning properly

### ISSUE THREAD

**Issue by johnwilliever** [roleoroleo/yi-hack-MStar#486]
Hi, I recently installed the hack on my YI Dome X cameras. Works great but it seems the viewing of recordings on official app is broken. It will only allow playing the first recording and if I swipe the seek to another recording time, it will only go back and play to the first recording. I already tried formatting the sd card and even disable snapshots but still not working properly.

The YI Home Camera app version I am using is 6.0.4_20230117085839.

**Comment by roleoroleo** [comment]
I think it's a timezone problem.
Next release should fix it.

**Comment by johnwilliever** [comment]
It's working now. You just need to reformat the sd card. Thanks.
