### ISSUE TITLE
Motion detection missings on new 0.4.9 firmware version

### ISSUE THREAD

**Issue by agsola** [roleoroleo/yi-hack-MStar#487]
Since last firmware I'm having issues with the motion detection sensor.

![image](https://user-images.githubusercontent.com/472079/220595547-ca3bfdee-3bee-4720-805b-52d4fd5e9174.png)

![image](https://user-images.githubusercontent.com/472079/220595603-1853f5ea-37a7-4efe-a98c-f082226ad0c6.png)

It doesn't report any motion in the last 16 hours, but we've it is false. 
It seems that it stopped reporting 16 hours ago.

I had no issues with this in the previous firmware.

I'm with the latest ha integration (yi-hack_ha_integration 0.4.4).

**Comment by roleoroleo** [comment]
Please, check the configuration in the app and toggle on/off/on motion detection.
With the new app you should have new detection options.

**Comment by roleoroleo** [comment]
You are right, this sentence should be true: "You don't need to enable motion detection, it's always enabled.".
But the last app release added some new settings about cloud detections and you should check what's your current mode.

**Comment by AirmakZ** [comment]
Hi all!
Is is possible that new Yi app makes some changes in the camera or something regarding the motion detection?
Y have 3 cams updated with 0.4.9 and two of them don't have connection (router blocking). In this ones motion detection is working properly.
The other one is using 0.4.9 too but it connected few times to Yi app.
In this camera I'm observing the following:

- Camera is disconnected from internet.
- The mqtt motion detector is not working.
- I connect the camera to yi app. and disable an enable the motion detection.
- mqtt starts working properly.
- I disable the Cloud Mode or activate the router blocking.
- mqtt motion detection stops...

To recover from this I need to repeat all these steps.

**Comment by roleoroleo** [comment]
What is your model suffix?

**Comment by AirmakZ** [comment]
Yeah... important detail, right?
Sorry... it's y203c
