### ISSUE TITLE
What frequency cam xmit data to FTP?

### ISSUE THREAD

**Issue by paologalli64** [roleoroleo/yi-hack-MStar#490]
Hello, I'm using YI Dome Camera X original firmware 4.0.0*	and  Mstar y30.
All seem ok, but i dont understand when camera send .mp4 to ftp server.
When i turn on camera, all data in SD card where sent to ftp, but after this trasmission, when start again the sync?
On the SD card new files .mp4 where created every x mnutes, but no trasmitted to ftp server .
I would be like that ftp was aligned continusly
Can you help me?
Thanks
Paolo

**Comment by roleoroleo** [comment]
system.sh near the end:
`echo "* * * * * sleep 40; /home/yi-hack/script/ftppush.sh cron" >> /var/spool/cron/crontabs/root`
The script runs every minute with 40 secs offset.
