### ISSUE TITLE
Date and time overlap

### ISSUE THREAD

**Issue by maldini89** [roleoroleo/yi-hack-MStar#491]
If possible, please add a date and time overlay to the video stream. It would be very convenient to see this when viewing the archive.

**Comment by roleoroleo** [comment]
Sorry but it's not possible.

**Comment by denven** [comment]
I guess it is likely to achieve this by rewriting video files from the camera RTSP stream, rather than having it from recorded files on the camera.

**Comment by roleoroleo** [comment]
The cam should decode the h264 video stream, add the tag and then encode again the stream.
There are no resources to do this job.

**Comment by denven** [comment]
> The cam should decode the h264 video stream, add the tag and then encode again the stream.
> There are no resources to do this job.
> 

Yes, that's what I am saying. Not on the camera, instead, do this job at a client end when reading the stream and encode the stream into video files with the time.

**Comment by roleoroleo** [comment]
Yes, you are right.
Maybe it's better with a hardware accelerated device.

**Comment by maldini89** [comment]
If so, is it possible to expect this dream to come true? :)
