### ISSUE TITLE
9FUS - firmware 0.4.9 : RTSP don't work

### ISSUE THREAD

**Issue by LeidenSpain** [roleoroleo/yi-hack-MStar#492]
Hi,

I have a camera that had firmware 0.4.7 and RSTP worked perfectly.
I have updated to the latest version because the integration with Home Assistant has indicated it to me, and now I find that the RSTP does not work

I have tried to connect it with VLC and I don't really see anything, which used to work before.

Let me know if I can provide any information that will help locate the problem.

Regards

**Comment by roleoroleo** [comment]
There are no changed in the last update about rtsp.
Please, try to reconfigure the cam.

**Comment by LeidenSpain** [comment]
Hi,

I've downgraded to 0.4.7 and it's working again.
I update again and tell how it went.

Updated to 0.4.9 and it has stopped working

**Comment by LeidenSpain** [comment]
and without touching anything, just went back to go.
I'll keep an eye on it as it seems somewhat unstable

**Comment by roleoroleo** [comment]
What about 0.4.8, just to understand where look for the problem.

**Comment by LeidenSpain** [comment]
I haven't even tried 0.4.8
Before I had 0.4.7, it worked, so I went back to that to do the tests.

By the way, I have both cameras with 0.4.9, I just connected through VLC, and it has worked without problems on both.

I don't know what to tell you, what used to give me a problem in both cameras now seems to work fine
