### ISSUE TITLE
Yi Home 1080 AI - RFUSY62FPS

### ISSUE THREAD

**Issue by digitarenet** [roleoroleo/yi-hack-MStar#493]
I have a new Yi Home 1080 AI with code RFUSY62FPS
Seem that is not supported, it is correct?

It's possible that it will be supported in near future?
May I help in any way to support this version?

**Comment by roleoroleo** [comment]
Please, make a backup copy and share it with me.

**Comment by digitarenet** [comment]
Hi have the backup, how can I share it with you?

**Comment by roleoroleo** [comment]
If you don't want to upload the file here, you can use a cloud share with a security system.
It depends on what you use.

**Comment by digitarenet** [comment]
Ok perfect, this is the file:

[backupYI.zip](https://github.com/roleoroleo/yi-hack-MStar/files/11171548/backupYI.zip)

**Comment by roleoroleo** [comment]
y291ga
https://github.com/roleoroleo/yi-hack-Allwinner-v2
