### ISSUE TITLE
CamHash - RTSP panel missing in MStar fw web interface

### ISSUE THREAD

**Issue by PaulPastis** [roleoroleo/yi-hack-MStar#494]
Hi everyone,

I am trying to follow the steps  described in the video below to enable and use the RTSP with a Yi Camera:
https://www.youtube.com/watch?v=j5IxqWOHomA&t=356s

The camera is a Yi Dome 1080p --> BFUSY1EEQY
The applicable fw is home_h201c and sys_h201c.   Other fw from yi-hack v4 and v5 are not processed by the cam.
The hack m-star works fine, but I don't see the RTSP panel on the web cam interface.

In order to use the RTSP on a RTSP server, the HashCam shall be used.
I expect to get the RTSP panel on the WebCam interface retrived at the address 192.168.1.xxx:8080, though there is not.

Question:
Is it reasonable to expect the RTSP panel,available for the Yi-Hack mstar version as in the Yi-Hack V4 and V5?
Is there any command or preference to use to enable the RTSP configuration panel?
IS there any other way to get the HashCam?

Thankssss a lot for patience and support

![web interface Yi-Hack M-Star](https://user-images.githubusercontent.com/128374945/226322891-64f041a9-9cf6-42b5-a2ed-72dcc8e0ad32.png)
![WebInterface Yi-Hack V4](https://user-images.githubusercontent.com/128374945/226322899-f7da28ed-2a52-494e-a02d-f7c7f4f7b7eb.JPG)

**Comment by roleoroleo** [comment]
You don't need the camhash.
With this hack/model RTSP is already enabled.
