### ISSUE TITLE
[h201c] Yi 1080p Dome BFUS -  can't enable snapshot feature from settings 

### ISSUE THREAD

**Issue by majkers** [roleoroleo/yi-hack-MStar#495]
Hi,
Enabling snapshot feature doesn't work because after restart it stays disabled:

![image](https://user-images.githubusercontent.com/21099773/226613974-fb0b50eb-a111-4a20-b192-0ecf2c7cd04d.png)

**Comment by roleoroleo** [comment]
Try to clean the cache of the browser.

**Comment by majkers** [comment]
Thing that helped was to manually add option to file responsible for storing this info

**Comment by majkers** [comment]
OK in incognito window when added snapshot option to system.conf manually, it started to save this value
