### ISSUE TITLE
[h201c] Yi 1080p Dome BFUS FTP password reset each camera restart

### ISSUE THREAD

**Issue by majkers** [roleoroleo/yi-hack-MStar#496]
Hi,
each time I restart camera my FTP password resets. I have connect via SSH and use passwd command to make it work again.

**Comment by roleoroleo** [comment]
Is it properly saved in the sytem.conf config file?

**Comment by majkers** [comment]
No it is not:

`FTP_USERNAME=
FTP_PASSWORD=
SSH_PASSWORD=THIS_IS_MY_PASSWORD`

of cource I changed my password there

**Comment by majkers** [comment]
You can check https://github.com/roleoroleo/yi-hack-MStar/issues/495 Also snapshot option in not properly saved

**Comment by roleoroleo** [comment]
Are you using weird chars?
Please, try with a stupid password. Maybe a problem in the string validation algorithm.

And as I said in the other issue, clean the cache of the browser; I changed the js code in the last update.

**Comment by majkers** [comment]
the only weird char might be @

**Comment by roleoroleo** [comment]
@ is supported.
I tested with my cam and it works.
Are you using version 0.4.9?

**Comment by majkers** [comment]
OK. I opened new incognito window

![image](https://user-images.githubusercontent.com/21099773/229062408-66784ebc-00f0-4115-8368-5512d285f871.png)

and set new root password to 123Test

and in system.conf only this:

![image](https://user-images.githubusercontent.com/21099773/229062518-4cbe6310-e840-462c-8baa-d3330e4f3739.png)

**Comment by majkers** [comment]
Yes I am using 0.4.9 version

**Comment by roleoroleo** [comment]
There is a misunderstanding.
FTP_PASSWORD field is the password used to put files to a ftp server (see Events page).
If you want to login from your PC to the cam through FTP, the right field is SSH_PASSWORD
Are you able to login with a ftp client to the cam with "123Test" as a password?

**Comment by majkers** [comment]
I don't know what is wrong with 0.4.9 firmware @roleoroleo After a few days of working average load grows a lot and I see my RTSP stream from go2rtc project do not run fluently. So I restart my camera and it won't come back online. Just like it is bricked. I had to downgrade and upgrade to make it work again. I think I will go back to 0.4.8 version and close this issue for now. Unfortunately IMHO 0.4.9 is not stable

**Comment by roleoroleo** [comment]
Sorry but I wasn't able to find the stability problem.

**Comment by majkers** [comment]
One time it even didn't start record process... Maybe next version will fix those issues :) I keep my fingers crossed
