### ISSUE TITLE
Contributing to 9FUS

### ISSUE THREAD

**Issue by NickAnderegg** [roleoroleo/yi-hack-MStar#50]
Hi @roleoroleo,

I couldn't get in touch with you via email, so I thought I'd try this. I'd like to assist with developing yi-hack-MStar. I have a Yi 1080p Home v3, which is the 9FUS with the 4.2.0 firmware. I see that it is listed in the README as "Work in progress," so I want to avoid duplicating work. Do you have a fork or branch for this firmware?

![IMG_1144](https://user-images.githubusercontent.com/542937/70856087-cf9e9300-1ea3-11ea-875b-eef4cf91ab9a.JPG)

**Comment by roleoroleo** [comment]
See
https://github.com/roleoroleo/yi-hack-MStar/issues/34

**Comment by roleoroleo** [comment]
Try the last version.

**Comment by VikIborra** [comment]
I have 9FUS cameras but are v1, not v3. Maybe it's the problem.

**Comment by kubawolanin** [comment]
Hi @roleoroleo 
First, thank you for your work on this. 
I use both yi-hack-v4 from @TheCrypt0 on Yi Outdoor and Yi Dome 720p and now flashed my *Yi Home 9FUS* with your hack.
I'm impressed how many useful features you've included there!
I really wish I could use PTZ on my TheCrypt0-s based Dome (`1.9.1.0J_201809191135`).

Just wanted to confirm that I successfuly flashed `y203c` into `9FUSY21CQSUEPO191010`. 
I tried `y25` with no luck. Simply copied both unpacked files into 32GB microsd card, didn't rename any files.
Maybe that'll help someone.
![image](https://user-images.githubusercontent.com/2270505/76696726-d600fe80-668e-11ea-8c87-13e053fb6765.png)

Thanks again!

**Comment by roleoroleo** [comment]
Thank you for your report.
About your Dome, I think it's possible to add ptz to the cam.
Probably there are the same ipc commands.
But I can't do it without the hardware.
