### ISSUE TITLE
Can someone help me? My camera is yi 1080p home camera 4FCN.

### ISSUE THREAD

**Issue by krishuang0610** [roleoroleo/yi-hack-MStar#500]
Can someone help me?
My camera is yi 1080p home camera 4FCN
I've been unsuccessful using y23 from the repository. I've downloaded versions from multiple repositories with no success.
![image](https://user-images.githubusercontent.com/78089003/231452593-50d91474-65cd-48f5-8f04-7c8e20ecae60.png)
![image](https://user-images.githubusercontent.com/78089003/231452715-aeb1948e-734d-4bce-94bd-bb2a60a198e0.png)

**Comment by roleoroleo** [comment]
What's the firmware version?

**Comment by krishuang0610** [comment]
> What's the firmware version?
Thank you.
This problem has been solved. I put all the versions in the TF card, and the update has been successful. After the update is successful, it shows Yi 1080p Home 4FCN ===> h201c, not Yi 1080p Home 4FCN ==>y23 in the list.
![image](https://user-images.githubusercontent.com/78089003/232046064-1067ed96-f5f1-45f0-a4c4-7e5423e20415.png)
