### ISSUE TITLE
ir-led bug

### ISSUE THREAD

**Issue by Sapphire1989** [roleoroleo/yi-hack-MStar#514]
in night vision mode bug: diode flashes two times and dimming after an equal time (3 seconds)
6FUS YYS.2016
SYSTEM
Firmware Version | 0.5.2
Base Version | 2.1.0.0E_201809191630
Model Suffix | y23

https://github.com/roleoroleo/yi-hack-MStar/assets/140055764/c7dcab4c-2ba9-43a3-9bd5-15a17b7e93c5

can i upgrade firmware to y203c? I tried putting new *_y203c files on the sd card for updating, but nothing happens

**Comment by roleoroleo** [comment]
I'm sorry but this behavior is not under my control.
It depends on the Yi firmware.
You could try to increase the distance between the bed and the cam, but I don't know if it fix your problem.

**Comment by kabakakao** [comment]
I am having the same issue with my "BirdCam".
Unfortunately I have no choice to increase the distance.
Any further ideas?
