### ISSUE TITLE
Yi Home 1080p - BFUSY21XXX

### ISSUE THREAD

**Issue by mikejenbrown** [roleoroleo/yi-hack-MStar#518]
Hi,
Hoping someone could direct me or advise if this camera will work at all with any of the Yi Camera Hack firmwares currently available.

The camera specs are as follows:
Yi Home 1080p 
BFUSY21XXX
Firmware - 4.5.0.0C_201910080934

Any adivce or info would be greatly appreciated!

Mike

**Comment by roleoroleo** [comment]
MStar y203c
