### ISSUE TITLE
v0.49 Directories are wrongly deleted by the auto cleaner

### ISSUE THREAD

**Issue by denven** [roleoroleo/yi-hack-MStar#520]
I think this may rarely happen, but it happened to my device today,

I wrote a real-time uploader program to upload files to OneDrive, and I check video files from OneDrive when I am not home. It works for several months. Today I found that some video files are missing, I thought the camera ran into failure or something, but I can access the camera from Yi-Home official app. Then I supposed the uploader program may have some bug results in some upload failures.

I checked the uploader program logs when I returned home, my uploader program's last restart date was a long time ago, and it is working without reboot, so the camera never rebooted recently as well (each time the camera reboots, the uploader program will generate a new log). I checked the uploaded folders in OneDrive and the existing folders on my camera SD card.  OneDrive already has some folders that are not shown on SD card (which were deleted by the yi-hack auto-cleaner), but some older directories on SD card are still there 2023Y09M01D05H, 2023Y09M01D10H. Video file folders between some time ranges are missing (not uploaded/may be wrongly deleted before being uploaded).
- 2023090221-2023090223 (3 hours)
- 2023090300 (1 hour)
- 2023090303-2023090304 (2 hours)
- 
![image](https://github.com/roleoroleo/yi-hack-MStar/assets/16745984/fa7360cc-455a-4a28-8d4d-dfa5255a564c)

![image](https://github.com/roleoroleo/yi-hack-MStar/assets/16745984/f6539869-53aa-4ef4-8b2d-a30beea31e96)

![image](https://github.com/roleoroleo/yi-hack-MStar/assets/16745984/e98ee6c1-2aaf-4bf1-aac3-8d7e1b1b721a)

![image](https://github.com/roleoroleo/yi-hack-MStar/assets/16745984/bc49738a-c23b-4b10-acb9-a11b326e9e77)

So the issue is that: **yi-hack has some bug that it doesn't always clean files/directories from old to newer consecuitively, some newer files are deleted wrongly, and older files/directories are still kept.**

the yi camera hack auto video cleaning configuration, I set the free space to 90% (which I originally took it as the threshold percentage to clean) 
![image](https://github.com/roleoroleo/yi-hack-MStar/assets/16745984/30f3b7c7-49fe-476f-8332-5eae24379122)

**Comment by denven** [comment]
I guess the cleaner may not work or calculate and find the right folders to delete properly when the used sd card storage ratio is smaller.

**Setting a smaller value like 10-50% is likely to avoid or reduce the risk of newer files/directories wrong deletion since each time it will clean only a smaller portion of the old files from the existing folders.**

**Comment by roleoroleo** [comment]
The script seems to be ok, it's very simple.
Maybe there is another cleaning procedure inside the yi processes.
I didn't check this case.

**Comment by denven** [comment]
> I guess the cleaner may not calculate and find the right folders to delete properly when the used SD card storage ratio is smaller.
> 
> **Setting a smaller value like 10-50% is likely to avoid or reduce the risk of newer files/directories wrong deletion since each time it will clean only a smaller portion of the old files/folders from the existing folders.**

I checked the script `clean_records.sh` code, and it looks fine, however, it doesn't work properly for `ls -lt` to sort the folders by modification time. Otherwise, I cannot understand why the folder's modification time is changed and results in the wrong sort. I dont know if any other process that will change the record folder mtime.

![image](https://github.com/roleoroleo/yi-hack-MStar/assets/16745984/cad28da9-340c-49e3-b726-14286bf1dcfa)

I am not sure if it is a bug of the `ls`, but when removing the `-t` option, it will list folders by name, I think it is okay to remove it since all the folders are named by yyyy**Y**mm**M**dd**D**hh**H** format, they will be sorted and ordered by the created time from earlier to recent time by default.

![image](https://github.com/roleoroleo/yi-hack-MStar/assets/16745984/dda3875c-31e3-451f-a54c-18cbeda8d7bb)

![image](https://github.com/roleoroleo/yi-hack-MStar/assets/16745984/961e812d-4b8c-41c2-9e57-b0c83f2afcf5)

Then the fix is to change the `t` to `r`
` ls -lt | grep -v tmp | grep -v timelapse | tail -n1 | awk '{print $9}'`
to
` ls -lr | grep -v tmp | grep -v timelapse | tail -n1 | awk '{print $9}'`
``
