### ISSUE TITLE
Proxychains-ng not working

### ISSUE THREAD

**Issue by vin-w** [roleoroleo/yi-hack-MStar#522]
Steps:
1.  new cam installed the firmware 0.5.2
2. proxychains added Server list in webpage
3. on restart  vi /home/yi-hack/etc/proxychains.conf => emptyfile

Another Qns: how to confirm if proxychains is running on cam?

**Comment by vin-w** [comment]
fallback to old firmware and it works

**Comment by vin-w** [comment]
fallback to old firmware and it works

**Comment by roleoroleo** [comment]
> Steps:
> 
>     1. new cam installed the firmware 0.5.2
> 
>     2. proxychains added Server list in webpage
> 
>     3. on restart  vi /home/yi-hack/etc/proxychains.conf => emptyfile

Is the file empty after clicking "SAVE AND TEST CONFIGURATION" before restarting?

> Another Qns: how to confirm if proxychains is running on cam?

From webgui it's not possible, you can check with a ssh session with ps command.
