### ISSUE TITLE
[Question] Is this dual-lens model supported?

### ISSUE THREAD

**Issue by wxrl** [roleoroleo/yi-hack-MStar#528]
https://www.amazon.com/YI-Dual-Lens-Security-Expanded-Dual-Screen/dp/B0C71LQ85X

The S/N starts with **A767**Q00...
Sorry for the intruding. Thanks!

**Comment by roleoroleo** [comment]
Based on the S/N I think it's not supported.
But I need to analyze a dump of the flash to know it exactly.

**Comment by wxrl** [comment]
Thanks for the reply.
I tried to dump the firmware following the instructions shown below but nothing was dumped to the uSD card...
https://github.com/roleoroleo/yi-hack-Allwinner/wiki/Dump-your-backup-firmware-(SD-card)

**Comment by roleoroleo** [comment]
No, you don't need it.
If the procedure doesn't work, probably it's a different platform and it's not supported.
