### ISSUE TITLE
difference between DOME and cloud DOME

### ISSUE THREAD

**Issue by grigoroff** [roleoroleo/yi-hack-MStar#53]
Hi,
i have YI-CLOUD DOME 1080P 6FUS with 0.2.0 (https://github.com/TheCrypt0/yi-hack-v4/releases) flashed firmware and i try to "upgrade" with yours.
I download h201c files and drop to clean FAT32 SDcard. But nothing changed and no yellow blink led on boot... I try with 4 different SDcard but nothing changed.

my questions are : 

1- Did the YI DOME 1080P 6FUS firmware can flash YI-CLOUD DOME 1080P 6FUS ?
2- I have ssh access can I flash manually and reboot ?

thanks for your work and answers.

**Comment by roleoroleo** [comment]
If you are using v4 version  you can't use my version.
The hardware platform is different.

**Comment by grigoroff** [comment]
thanks for your reply.
just to be sure i understood well : 
I use V4 but it's not the problem. The problem is DOME and CLOUD-DOME are different hardware.

that it ?

**Comment by roleoroleo** [comment]
Yes.
My version works only on MStar platform (MStar ARM cpu).

**Comment by grigoroff** [comment]
:-(
ok thanks a lot 

ps : my yi home 6FUS working like a charm with your and last release.
thanks again
