### ISSUE TITLE
ssh key

### ISSUE THREAD

**Issue by ranrinc** [roleoroleo/yi-hack-MStar#54]
Is there a possibility to turn of password and used SSH keys instead. So its more secure? If yes, where is the setting to not allowing plain text password?

Thanks for the great work

**Comment by roleoroleo** [comment]
You can follow a "normal" dropbear guide.
Generate a key on your client device:
`ssh-keygen -b 4096`

Login to your camera and create the file /home/yi-hack/.ssh/authorized_keys
`touch /home/yi-hack/.ssh/authorized_keys`

Copy your key form ~/.ssh/id_rsa.pub to /home/yi-hack/.ssh/authorized_keys using vi (copy and paste).

Correct the file permissions:
`chmod 0600 /home/yi-hack/.ssh/authorized_keys`

Restart the cam:
```
sync
reboot -f
```

If you want to disable the password login, edit /home/yi-hack/script/system.sh and add the option "-s" to dropbear.

**Comment by roleoroleo** [comment]
Please note that you need to repeat this configuration if you update a new release.

**Comment by ranrinc** [comment]
@roleoroleo Thanks... got it working..

**Comment by roleoroleo** [comment]
See wiki.
