### ISSUE TITLE
[Feature Request] RTSP ch0_0 always used when single resolution chosen

### ISSUE THREAD

**Issue by myromeo** [roleoroleo/yi-hack-MStar#541]
Would it be possible to implement a change where the primary rtsp URL is always used if a single resolution is selected, for example, when selecting ‘Both’ you have a high and low resolution channels, when selecting high it only presents ch0_0 and but when selecting low res only ch0_1 is presented. 

Is it possible that when only low is selected it is made available on ch0_0 rather than ch0_1 ? This would avoid some compatibility issues with certain NVR’s (Hikvision / Annke for example)

**Comment by roleoroleo** [comment]
For this purpose you can use the option "ONVIF Profile":
![immagine](https://github.com/roleoroleo/yi-hack-MStar/assets/39277388/94b0ce64-c2d5-4155-b8e1-4b308ff0cfe6)
