### ISSUE TITLE
udhcpc does not respect hostname

### ISSUE THREAD

**Issue by vip9** [roleoroleo/yi-hack-MStar#544]
`  816 root      0:00 udhcpc -i wlan0 -b -s /home/app/script/default.script -x hostname:yi-hack`
that does not respect hostname, which could be configured different in webui.

Problem is, when you have more then one cameras.

version 0.5.5

**Comment by vip9** [comment]
it is wifi camera, (udhcpc -i wlan0)

**Comment by roleoroleo** [comment]
I already fixed this problem but I forgot to push it.
https://github.com/roleoroleo/yi-hack-MStar/commit/9cf96db961f320970b8267acae4eabce592f9836
