### ISSUE TITLE
No access to webinterface

### ISSUE THREAD

**Issue by shruxx** [roleoroleo/yi-hack-MStar#546]
Hi,

maybe I'm too stupid to get it done. I''ve a Yi Home 1080P with FW 4.5.0.0C_201910080934
It worked before with y203c. After I resetted it and flashed it again, there is no possibility to access web or ssh. I would like to use the hack.

BR

**Comment by roleoroleo** [comment]
Try to downgrade to a previous version and then upgrade again.
