### ISSUE TITLE
FTP Question

### ISSUE THREAD

**Issue by idanny76** [roleoroleo/yi-hack-MStar#548]
Can I use FTP if there is no SD Card in the camera? Would it save it internally and upload it. For example if I have no memory card in the camera, I still get the short motion clips from the Yi cloud. Didn't know if I could get FTP motion clips without the sd card.

**Comment by idanny76** [comment]
Also can I update without an SD card? I am assuming is not possible, but just wondering.

**Comment by idanny76** [comment]
I had to leave some cameras without sd cards. I was hoping to view the cameras remotely with the app just live view. For some reason the cameras are online through a mobile hotspot connection, but are not communicating with the app. I can connect to the yi-hack by IP through the phone, but app will not connect to camera. I do not have cloud services disabled.

**Comment by roleoroleo** [comment]
afaik is not possible to store video inside the cam without a sd card.
So it's not possible to use ftp to send them to a server.

About firmware update, I'm not completely sure but I think it's possible.

Is there any firewall rule in the hotspot?
