### ISSUE TITLE
BFUS - RTSP and Synology problem

### ISSUE THREAD

**Issue by cfus98** [roleoroleo/yi-hack-MStar#55]
I have two Yi cameras. The yi_home_1080p is working fine with Synology Surveillance station and the yi_dome (BFUSY...) stopped working after flashing newest yi-hack firmware. 

I can see the RTSP feed in the web gui (ptz tab) and VLC but the feed fails with Surveillance Station. I have tried rtsp://IP-CAM/ch0_0.h264 and rtsp://IP-CAM:554/ch0_0.h264 (user defined setup)

Camera FW: 4.6.0.0A_201908271549
Hack version: h201c

Any suggestions would be welcome or is this a bug that needs fixing?

Thanks for making this.

**Comment by roleoroleo** [comment]
With which version did it work correctly?
With which version did it stop working?

**Comment by cfus98** [comment]
It was working with the 2.2 version (Nov 29). Then for some reason the camera stopped working two days ago and I downloaded 2.3 (Dec 22) and reflashed. The firmware seems to be working everywhere but Synology Surveillance Station (version 8.2.6-6009). I cannot see a recent update in the Synology logs.

**Comment by roleoroleo** [comment]
Please, try again with 0.2.2.

**Comment by DaveThe** [comment]
I have the same problem with 0.2.4 version.
Synology does not see any onvif camera.
Home assistant with motion eye see the camera but show a grey screen.

have you any suggestions?

**Comment by roleoroleo** [comment]
Probably is the same issue described here: https://github.com/roleoroleo/yi-hack-MStar/issues/36
And I can't solve it at the moment.

**Comment by roleoroleo** [comment]
> 
> 
> I have the same problem with 0.2.4 version.
> Synology does not see any onvif camera.
> Home assistant with motion eye see the camera but show a grey screen.
> 
> have you any suggestions?

I'm trying with motioneye (standalone, not hassio add-on) and I have no problems.
I added as a RTSP cam with rtsp://IP-CAMERA/ch0_0.h264 and it works fine.

**Comment by cfus98** [comment]
Hi roleoroleo, I updated to the new firmware 0.2.4 and now the rtsp feed works perfectly with my synology nas. Thanks for fixing it.

**Comment by roleoroleo** [comment]
I didn't fix it intentionally.
Please verify if it works on the next 0.2.5.

**Comment by nathankellenicki** [comment]
I posted in #36, however unfortunately 0.2.5 didn't fix the issue for me (homebridge-camera-ffmpeg).

**Comment by ady-crow** [comment]
Hi roleoroleo. did i see you say that ONVIF is NOT working on Synology at the minute?
Will save me time if you confirm

thanks for the hard work

**Comment by roleoroleo** [comment]
Yes, at the moment it's not working.
Synology implementation is not standard imho.

**Comment by ady-crow** [comment]
Thanks

Ady

Sent from my iPad

On 23 Nov 2020, at 18:24, roleo <notifications@github.com> wrote:

﻿

Yes, at the moment it's not working.
Synology implementation is not standard imho.

**Comment by roleoroleo** [comment]
Released a new version: https://github.com/roleoroleo/yi-hack-MStar/commit/b644f1427e6e190e4be22bb1895be4e372f0edd7
