### ISSUE TITLE
yi-hack-MStar 0.2.3 + BFUS cam - Low security ONVIF

### ISSUE THREAD

**Issue by chuk4ik** [roleoroleo/yi-hack-MStar#56]
Used ONVIF Device Manager 2.2.250. Connect from another location to an external ip camera (YI home 1080p). The program at the link http: // wan_ip_cam / onvif / device_service - receives full information on a stream of the form rtsp: // login: pass@IP-CAM/ch0_0.h264 without requesting a login / password.

Those. in fact, the program highlighted the login and password for access via http rtsp and ONVIF

ONVIF Device Manager 2.2.250
https://sourceforge.net/projects/onvifdm/

Sorry for the bad English.

PS: If necessary, I can attach screenshots. I am not an expert in all of these ONVIF and RTSP, but somehow it is very not safe.

**Comment by roleoroleo** [comment]
Yes i know. At the moment it's a "feature".
But I can remove it, if necessary to publish the service.

**Comment by chuk4ik** [comment]
> 
> 
> Yes i know. At the moment it's a "feature".
> But I can remove it, if necessary to publish the service.

And can this be done on / off "features"?
Perhaps it will be convenient for someone. I just turned off ONFIV for now. It may not look special to me (to curious hackers), but I’m afraid to shine logins / passwords.

**Comment by roleoroleo** [comment]
I will remove login info in the next release.

**Comment by roleoroleo** [comment]
Please try the last release.
