### ISSUE TITLE
To thinking: Change the bitrate of the video stream

### ISSUE THREAD

**Issue by chuk4ik** [roleoroleo/yi-hack-MStar#57]
Is it possible to make settings for increasing/changing the bitrate of the video stream?

Now the camera writes with a bitrate of ~1.2Mbit/s. For a picture in HD, this is very small, which leads to the appearance of squares and artifacts in the picture with fast movement.

I can assume that the bitrate is software stabbed. There probably should be a file with bitrate parameters for the video, maybe someone knows exactly where it is?

If possible, it should affect the size of the mp4 file. And maybe it will somehow affect the work of the YI service. I would test on my camera if I knew where this can be changed.

**Comment by roleoroleo** [comment]
You could try to play with setprop and getprop.
Take a look at the /home/app/init.sh
But I don't know what can happen, especially at the rtsp stream.
