### ISSUE TITLE
Comparing resolutions

### ISSUE THREAD

**Issue by ranrinc** [roleoroleo/yi-hack-MStar#58]
Hi @roleoroleo,

I have been using yi-hack 4 on my old cam and used yours on newer cam since yi-hack 4 doesnt support it. However I'm wondering why the resolution of rtsp old cam which is not 1080 is much2 better then rtsp running your fw on 1080 cam... is there something that I did wrong?

**Comment by roleoroleo** [comment]
I've never used an old cam but the quality of this doesn't seem so bad to me.
However, I don't know how to improve it.
H264 frames are created directly from the kernel driver with YI's default settings.
Then send it to live555 to stream it.
