### ISSUE TITLE
9FUSY25xxx need firmware

### ISSUE THREAD

**Issue by egs2003** [roleoroleo/yi-hack-MStar#61]
What firmware do I need for this camera?
Attached I have a picture of the QRCode. The camera from the inside PCB side.  I have marked the UART pins. I have pulled and attached a DUMP of the original firmware (4.2.0.0H_201909041620). The dump I have made according to the description "https://github.com/roleoroleo/yi-hack-MStar/wiki/Dump-your-backup-firmware". The addresses of the partitions were the same.
if I use the script with the end address minus 1, I get an error message because of the multiple of 64

used commands
sf read 0x21000000 0x1d0000 0x1e0000
py script.py --timeout 1 --step 64 com5 115200 0x21000000 0x211e0000
sf read 0x21000000 0x3b0000 0xc30000
py script.py --timeout 1 --step 64 com5 115200 0x21000000 0x21C30000

Also the BOOT log. There is possibly a WLAN password in the dumps, but only a test WLAN. 
Hope I can contribute to the development and get a working software in return.

![Platine Voderseite](https://user-images.githubusercontent.com/8488313/71640258-10a9ec00-2c87-11ea-97a7-383ad70a968d.png)
![Gehäuse mit QRCode](https://user-images.githubusercontent.com/8488313/71640259-10a9ec00-2c87-11ea-94eb-08eb7805aaa3.png)
![Platine Rückseite](https://user-images.githubusercontent.com/8488313/71640260-11428280-2c87-11ea-8f40-0fc9b77d452e.png)

[putty.log](https://github.com/roleoroleo/yi-hack-MStar/files/4013933/putty.log)

**Comment by roleoroleo** [comment]
It seems that your dump has a problem with a file.
In any case I have compared the content with this https://github.com/roleoroleo/yi-hack-MStar/issues/34 and it is the same.
So you can try the version y25_0.2.3.tgz

PS I updated the wiki.

**Comment by egs2003** [comment]
What do you mean with "It seems that your dump has a problem with a file."
Can i use my dump to get back to the original firmware if necessary?

**Comment by roleoroleo** [comment]
There is a file (oss binary in /home/app) with a lot of "0" in the middle.
Probably an error during the dump.
At the moment I think you cannot use it as a restore, but I can "repair" it if necessary.
Try to repeat the dump, only the home partition.

**Comment by egs2003** [comment]
uff, this took me several hours

**Comment by roleoroleo** [comment]
Yes, I know.
If you don't want, it is not necessary.

**Comment by egs2003** [comment]
y25_0.2.3.tgz is working for me. thx
here is the new dump, the bytes are already swapped
[dump.zip](https://github.com/roleoroleo/yi-hack-MStar/files/4016025/dump.zip)

**Comment by roleoroleo** [comment]
I'm sorry, I was wrong: the corrupt oss file was the other, not yours.
I confirm that you can use your dump as a restore of the original fw.
Thanks for your support in correcting the wiki.
