### ISSUE TITLE
Can't flash camera

### ISSUE THREAD

**Issue by SamPhoenix91** [roleoroleo/yi-hack-MStar#62]
I am trying to flash the camera with the firmware, but cannot get it to download.

It runs Yi, but when I boot with the SD card in nothing happens.

This is the camera: 
https://www.amazon.co.uk/gp/product/B07P8ZY7PB/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

**Comment by arhunt35** [comment]
I had this. The way I got it to work was to format sd card in the app, pop into computer then copy across the files. I think the cam didn't like the way the card was formatted

**Comment by supermanscottbristol** [comment]
Any joy?  I'm suffering the same thing.
SD Card works fine in the camera, formatted from camera, firmware added but it doesnt flash on bootup.

**Comment by roleoroleo** [comment]
There are three possibilities: there are problems with the SD, you are using the wrong file (y203c, h201c or y25) or your cam is not supported.

**Comment by supermanscottbristol** [comment]
Thanks @roleoroleo  - Just got there.  I reformatted, made a 16gb partition on the card and for whatever reason that worked !?

Thank you for the hard work @roleoroleo

**Comment by roleoroleo** [comment]
Too much time since the last post.
Open a new issue if necessary.
