### ISSUE TITLE
Upgrade from older version

### ISSUE THREAD

**Issue by Vannixxo** [roleoroleo/yi-hack-MStar#68]
When upgrading (I've got a version before the MStar renaming) will I lose the settings? And should we delete the firmware files from the SD or it is the same to leave them there?
Thanks

**Comment by roleoroleo** [comment]
Yes, you will loose the settings.
Is not possible to mantain them during a fw update.
No you don't need to delete the file because the bootloader saves a md5 sum and executes the upgrade only if the files are different.

**Comment by Vannixxo** [comment]
Perfect thanks
