### ISSUE TITLE
Feature Request: What do you think about optional streaming to multicast address

### ISSUE THREAD

**Issue by egs2003** [roleoroleo/yi-hack-MStar#69]

**Comment by roleoroleo** [comment]
Try the test program available on live555:

1. Create a h264 file using h264grabber redirected to stdout.
2. Rename it test.264
3 Run testH264VideoStreamer

[testH264VideoStreamer.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/4052574/testH264VideoStreamer.tar.gz)

**Comment by egs2003** [comment]
I don't know how to test it or what to do. I'm just a user. I don't know the cameras that well

**Comment by roleoroleo** [comment]
What client program do you use to consume multicast RTSP?

**Comment by egs2003** [comment]
Vlc

roleo <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 14:35:

**Comment by roleoroleo** [comment]
I tried the test program but doesn't work.

**Comment by roleoroleo** [comment]
Too much time since the last post.
Open a new issue if necessary.
