### ISSUE TITLE
Feature Request: What do you think about recording in activity region

### ISSUE THREAD

**Issue by egs2003** [roleoroleo/yi-hack-MStar#70]

**Comment by roleoroleo** [comment]
what do you mean exactly?

**Comment by egs2003** [comment]
I'd like to be able to mark areas in the video that are being monitored. So motion detection only in the highlighted area.

**Comment by egs2003** [comment]
I'd like to be able to mark areas in the video that are being monitored. So
motion detection only in the highlighted area.

Am Mo., 13. Jan. 2020 um 08:37 Uhr schrieb roleo <notifications@github.com>:

**Comment by roleoroleo** [comment]
The motion detection algorithm is not under my control.
Is made directly by the Yi drivers.
I can't modify it.

**Comment by egs2003** [comment]
Can this driver be accessed to modify it?

**Comment by roleoroleo** [comment]
No sources unfortunately.
