### ISSUE TITLE
Help needed to identify cam

### ISSUE THREAD

**Issue by frankcom** [roleoroleo/yi-hack-MStar#72]
Hello, I highly appreciate your work on yi-Hack, but now I need some help :)
I have bought a "Mibao" cam on Amazon a few months ago and I am currently using the recommended YI IoT app to make it working.
I highly expect that the device is being a "YI Technology" cam, but I do not know how I can identify, which type of cam.
There is only the text "Smart Camera" on the label - no exact description.
Any idea how I could verify it? 
Many thanks

**Comment by roleoroleo** [comment]
The model number and the labels are a good start.
But I suggest you to open it and take some pictures.

**Comment by frankcom** [comment]
Thanks for your quick reply. I hope attached material helps.
![IMG_20200117_175349](https://user-images.githubusercontent.com/6085914/72630745-4cb1a200-3953-11ea-9fdb-8e2872410215.jpg)
![IMG_20200117_174643](https://user-images.githubusercontent.com/6085914/72630746-4cb1a200-3953-11ea-8ecd-70c0b5f3bf73.jpg)
![IMG_20200117_175437](https://user-images.githubusercontent.com/6085914/72630747-4d4a3880-3953-11ea-96ce-f4b11fa3796c.jpg)
![IMG_20200117_175454](https://user-images.githubusercontent.com/6085914/72630748-4d4a3880-3953-11ea-8bbe-4799726bb36f.jpg)

**Comment by roleoroleo** [comment]
In the pictures I can't see anything that makes us understand architecture.
But it doesn't look like anything known.
I think that my firmware will not work on this.

**Comment by frankcom** [comment]
Thanks, I hoped for positive response as the app which is working is from yi technology :)
