### ISSUE TITLE
Allow deleting of folders/videos from webserver [Motion Events] tab

### ISSUE THREAD

**Issue by Zireael** [roleoroleo/yi-hack-MStar#75]
Hi
A minor request, but would it be possible to add option to delete videos stored on memory card through the webserver interface on the [Motion Events] tab?
A tickbox by each video file and **#Delete Selected** button.

Thanks in advance!

**Comment by roleoroleo** [comment]
Ok i will try to find some time to do it.

**Comment by roleoroleo** [comment]
Please, try the last version.
