### ISSUE TITLE
Feature Request: Rotate image by 90° for portrait mode

### ISSUE THREAD

**Issue by Zero545** [roleoroleo/yi-hack-MStar#76]
Hello,

I am using the camera to film inside my terrarium. To cover all relevant spaces I had to rotate the camera by 90°. Would it be possible to include a 90° (or 270°) rotated portrait mode (similar to the 180° rotated mode for ceiling mount)?

**Comment by roleoroleo** [comment]
The official software doesn't support this feature.
Sorry but I can't do it.
