### ISSUE TITLE
Option to disable motion detection

### ISSUE THREAD

**Issue by jamie01** [roleoroleo/yi-hack-MStar#81]
Is it possible to disable the motion detection completely? I would like to keep the option of recording videos when motion is detected, but only do this at certain times (controlled via home-assistant).

I could toggle the option to disable video recording when not connected to the cloud (I have cloud disabled) but this requires a reboot of the camera each time (although it appears I can just login and execute /home/app/mp4record at any time to enable recording again).

Edit: I enabled cloud and tried to disable motion detection in the app but even then it records video! So for now I have hacked together a bash script and put it in cgi-bin which can kill or launch the mp4record process on demand, I'm fine with that unless you can think of a better way?

**Comment by roleoroleo** [comment]
I was just thinking of a similar solution: a cgi script that executes and stops mp4record.
If you want you can do a pr.
