### ISSUE TITLE
Variable MAC address / static IP

### ISSUE THREAD

**Issue by arhunt35** [roleoroleo/yi-hack-MStar#83]
Both of my cameras produce different MAC addresses when I turn off / on. They cycle through three different ones. This has made assigning a single static IP on my router impossible. Is it possible to either permanently fix the MAC address or set a static IP on the camera?

**Comment by roleoroleo** [comment]
You could try to edit /home/app/init.sh and add these line before `ifconfig wlan0 up`:
```
ifconfig wlan0 hw ether xx:xx:xx:xx:xx:xx
```

**Comment by arhunt35** [comment]
Thanks for the super quick reply (and for the project as well - it's excellent).  I'll give it a go.

**Comment by arhunt35** [comment]
This worked for me.  Thanks again.

**Comment by roleoroleo** [comment]
If you upgrade the fw, you need to repeat the operation.

**Comment by arhunt35** [comment]
Thanks.  I figured that would be the case.  Is there an easy way to add this to the web interface? If you can point me in the right direction I'll give it a go.

**Comment by roleoroleo** [comment]
It's a long chain but is possible.
You have to modify:

- the .html page where you want to put the box;
- the .js file with the same name of the page;
- the cgi (shell script) called by js ajax function;
- the .conf file where you want to store the configuration parameter;
- the init.sh file that read .conf file at boot and set the address.
