### ISSUE TITLE
0.2.7 Y25 - hostname cannot be changed

### ISSUE THREAD

**Issue by egs2003** [roleoroleo/yi-hack-MStar#92]

**Comment by roleoroleo** [comment]
Which version?

**Comment by egs2003** [comment]
0.2.7

roleo <notifications@github.com> schrieb am Di., 25. Feb. 2020, 20:31:

**Comment by roleoroleo** [comment]
I solved this issue.
Wait for the next release.

**Comment by Chekedaudau** [comment]
Same problem in 0.2.7 y203c...

**Comment by egs2003** [comment]
problem solved with release https://github.com/roleoroleo/yi-hack-MStar/releases/tag/0.2.8
