### ISSUE TITLE
I need the pathname of the recorded motion event in the MQTT message

### ISSUE THREAD

**Issue by egs2003** [roleoroleo/yi-hack-MStar#96]

**Comment by roleoroleo** [comment]
What version?
h201c, y203c or y25?

**Comment by egs2003** [comment]
Y25

roleo <notifications@github.com> schrieb am So., 1. März 2020, 17:40:

**Comment by roleoroleo** [comment]
Try this beta:
[y25_0.2.8.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/4272250/y25_0.2.8.tar.gz)

**Comment by egs2003** [comment]
Seems to work. I got the file names and again I also can change the hostname. See https://github.com/roleoroleo/yi-hack-MStar/issues/92
