### ISSUE TITLE
Feature request - software lock camera at IR mode

### ISSUE THREAD

**Issue by mojo965** [roleoroleo/yi-hack-MStar#97]
Is it possible to software lock camera at IR mode? I mean IR filter still off. I dont want to hear clicks/noises when camera is automatically changing mode to IR and back to normal. The clicks/noises as I think are made by the IR filter turning on and off. I need camera still working at IR mode and be absolutely quiet. I'm using it to see what my cats do when nobody's home. Clicks/noises made by camera are very interesting for cats ...
If it's not possible to do it with software I will have to cut wires inside camera.
And by the way - great job. My 2 YI home cameras are working perfect with synology surveillance station without spying "cloud" servers.
Sorry my bad English ...
Marcin.

**Comment by roleoroleo** [comment]
Sorry for the late reply.
For my knowledge it is not possible to lock IR mode.
