### ISSUE TITLE
Why is there no dropdown menu for Detection sensitivity

### ISSUE THREAD

**Issue by egs2003** [roleoroleo/yi-hack-MStar#99]
![image](https://user-images.githubusercontent.com/8488313/75781417-68370780-5d5d-11ea-9866-96f1d18ca165.png)

**Comment by roleoroleo** [comment]
Because I'm not a good web programmer.
:)

**Comment by egs2003** [comment]
added in https://github.com/roleoroleo/yi-hack-MStar/pull/117
